### ISSUE TITLE
webUIUpload/upload.feature:94 failed

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#6713] opened 2022-04-01 14:46 UTC
see https://drone.owncloud.com/owncloud/web/24343/62/15
seems like the server replied with 500 see https://drone.owncloud.com/owncloud/web/24343/62/10 from line 309
```
{"level":"error","service":"storage","pkg":"rhttp","traceid":"00000000000000000000000000000000","datatx":"simple","error":"Decomposedfs: could not symlink child entry: symlink ../../../../../90/57/0b/5b/-c117-469e-82e1-83a3ae9fd9b7 /srv/app/tmp/ocis/storage/users/spaces/19/98a781-f160-416a-b020-f7120cb71805/nodes/19/98/a7/81/-f160-416a-b020-f7120cb71805/big-video.mp4: no such file or directory","time":"2022-04-01T13:29:39Z","message":"error uploading file"}
{"level":"error","service":"storage","pkg":"rhttp","traceid":"00000000000000000000000000000000","host":"127.0.0.1","method":"PUT","uri":"/data/simple/6dfc6439-759e-4357-a9a6-c71e0a96d6bd","url":"/data/simple/6dfc6439-759e-4357-a9a6-c71e0a96d6bd","proto":"HTTP/1.1","status":500,"size":0,"start":"01/Apr/2022:13:29:38 +0000","end":"01/Apr/2022:13:29:39 +0000","time_ns":719475700,"time":"2022-04-01T13:29:39Z","message":"http"}
```

ToDo: check if we can reproduce that

**Comment by saw-jan** [comment] 2022-04-19 10:35
Couldn't reproduce as of now

**Comment by kiranparajuli589** [comment] 2022-04-25 06:45
tests are passing consistently in the recent ci builds. closing for now!

**Comment by kulmann** [comment] 2022-05-09 11:16
Also re-appeared in https://drone.owncloud.com/owncloud/web/25418/67/16 and in general saw it failing quite a lot the last days

**Comment by individual-it** [comment] 2022-05-09 11:26
Does not look like the original bug
are we waiting log enough to confirm the file was uploaded?
here the ocis log output (from https://drone.owncloud.com/owncloud/web/25418/67/11)
![image](https://user-images.githubusercontent.com/2425577/167400449-13712a00-59e8-42cb-91c8-0e03599b37cc.png)

**Comment by saw-jan** [comment] 2022-05-16 06:42
Could be same issue as https://github.com/owncloud/web/issues/6978#issuecomment-1127249567

**Comment by SwikritiT** [comment] 2022-05-17 07:26
> Could be same issue as [#6978 (comment)](https://github.com/owncloud/web/issues/6978#issuecomment-1127249567)

The tests passed in multiple runs https://drone.owncloud.com/owncloud/web/25645/10/16. Probably the same issue.

**Closed by SwikritiT** 2022-05-17 07:26 UTC
Labels: QA:team, QA:p2
