### ISSUE TITLE
Uploading/creating files is broken after reloading page in some views

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#6362] opened 2022-02-03 12:47 UTC
### Steps to reproduce
1. Go to "shared with me" or "shared with others" view and reload the page
2. Return to home view and try to create/upload anything

### Expected behaviour
Uploading/creating works 

### Actual behaviour
Instead of the call "webdav/eos/user/.../filename" for creation "dav/public-files/eos.../filename" is called and fails (see screenshots). The issue might be related to https://github.com/owncloud/web/issues/6326 because also the breadcrumb disappears in personal view by steps to reproduce.

![Screenshot from 2022-02-03 13-31-32](https://user-images.githubusercontent.com/7430156/152345534-f7da37ac-5436-4e71-befd-2b9f64c45618.png)

Reload of the page with personal view fixes it
![Screenshot from 2022-02-03 13-36-48](https://user-images.githubusercontent.com/7430156/152345530-efc054fd-9d4d-4cc9-9ea2-805cb611b885.png)

Tested in CERNBox and https://ocis.ocis-web.latest.owncloud.works

**Comment by pascalwengerter** [comment] 2022-02-09 08:55
@elizavetaRa could you check out if it's still present on current master? @fschade got https://github.com/owncloud/web/pull/6391 merged yesterday and I can't reproduce it anymore

**Closed** 2022-03-08 17:48 UTC
Labels: Early-Adopter:CERN
