### ISSUE TITLE
Move personal quota fetching to a sane location

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#7093] opened 2022-06-07 09:59 UTC
As followup of https://github.com/owncloud/web/pull/7053, where it surfaced during review:

We currently fetch the quota of the personal storage while loading the personal space. As above mentioned PR allows to query different personal spaces (based on backend side permissions), it makes less sense to keep querying the quota in the folder loader task, since it might not even be the own personal space (i.e. quota information unavailable to the logged in user).

We need to look into a more sane place to query the backend for personal space quota. Since the quota of the personal space is displayed in the user menu from the `web-runtime` package we should at least move it closer to that component (i.e. not files app, but runtime).

--------
Just FYI / context, which is already covered by a different ticket: https://github.com/owncloud/web/issues/6930
Apart from the low hanging fruit we need to decide when and how we want to update the personal space quota:
1. after any successful write-request (copy, move, delete, restore, upload, file modification via an editor, ...)
  a. by re-calculating the quota information in the frontend code
  b. by re-querying the quota information from the backend
2. as a background job with rather low frequency (same as notifications, which also might need a lower request frequency)

**Comment by tbsbdr** [comment] 2022-07-27 13:08
duplicate of #6930 (note decision)

**Closed by tbsbdr** 2022-07-27 13:08 UTC
Labels: Type:Bug, Priority:p3-medium
