### ISSUE TITLE
Investigate `webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:236` failure in nightly

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#7000] opened 2022-05-18 03:55 UTC
Build: https://drone.owncloud.com/owncloud/web/25679/36/20

<details>
<summary>webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:236</summary>

```
  @mailhog @public_link_share-feature-required
  Scenario: creating a public link with "Uploader" role makes it possible to upload multiple files via files-drop page # features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:236
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (247ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has created folder "simple-folder" in the server
    Given user "Alice" has shared folder "simple-folder" with link with "create" permissions in the server
    When the public uses the webUI to access the last public link created by user "Alice" in a new session
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (228ms).
  Using: chrome (94.0.4606.61) on Linux platform.

√ Element <#files-drop-container> was present after 512 milliseconds.
    And the public uploads file "'single'quotes.txt" in files-drop page
    And the public uploads file "new-lorem.txt" in files-drop page
 Error while running .setElementValue() protocol action: An unknown server-side error occurred while processing the command. – unknown error: DevTools didn't return objectId

   TimeoutError: An error occurred while running .setValue() command on <input[type=file]>:   (Session info: chrome=94.0.4606.61),  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 4.15.0-177-generic x86_64); unknown error: DevTools didn't return objectId
   {"status":-1,"state":"","code":"","value":{"message":"unknown error: DevTools didn't return objectId","error":["  (Session info: chrome=94.0.4606.61)","  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 4.15.0-177-generic x86_64)"]},"errorStatus":13,"error":"An unknown server-side error occurred while processing the command. – unknown error: DevTools didn't return objectId","httpStatusCode":200}
       at Page.uploadFile (/var/www/owncloud/web/tests/acceptance/pageObjects/filesDropPage.js:33:23)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:230:6)
    Then the following files should be listed on the files-drop page:
      │ 'single'quotes.txt │
      │ new-lorem.txt      │
√ Element <.upload-info-successful-uploads span.oc-resource-name> was visible after 30 milliseconds.
    ✖ failed
      AssertionError [ERR_ASSERTION]: Could not find following files:
      new-lorem.txt
          + expected - actual

          -1
          +0

          at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:239:10)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    And as "Alice" the content of "simple-folder/'single'quotes.txt" in the server should be the same as the content of local file "'single'quotes.txt"
    - skipped
    And as "Alice" the content of "simple-folder/new-lorem.txt" in the server should be the same as the content of local file "new-lorem.txt"
    - skipped
```
</details>

**Comment by sushmita56** [comment] 2022-05-19 03:49
The issue is not reproducible both locally and in CI, so is closing here and will be reopened if needed.

**Comment by SagarGi** [comment] 2022-05-30 06:04
Re-appeared in yesterday's nightly build. Needs further investigation.

**Comment by SagarGi** [comment] 2022-06-03 07:36
Fails on while setting up the input files value in CI. Tried to reproduce it locally and also in CI https://drone.owncloud.com/owncloud/web/26018 but not possible. Closing for now as passing in recent builds. Can be opened if reappeared.

**Closed by SagarGi** 2022-06-03 07:36 UTC
Labels: QA:team
