### ISSUE TITLE
Drive alias: one of the space does not open with the same alias

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7715] opened 2022-09-29 12:50 UTC
related to https://github.com/owncloud/web/pull/7430

Steps:

- Create 2 spaces with the same name "new space"
- rename one space to "renamed" space
- try to open "new space"

Expected: "new space" space has been opened
Actual: "renamed" space has been opened

https://user-images.githubusercontent.com/84779829/193035456-58c1b2ae-8d7d-4616-9def-de1a4cbb7f80.mov

**Comment by kulmann** [comment] 2022-09-29 13:15
Same as in https://github.com/owncloud/web/issues/7714

This is a known regression from the drive alias PR. Since duplicate drive aliases are allowed it is not possible at the moment to know which of the spaces to open (applies for the files view and the trash bin of the space). You will only ever see the first space/trash with this drive alias. To fix this we need https://github.com/owncloud/web/issues/6247 (next on my list to implement).

Of course a GA blocker. Let's keep this issue here open, as it shows pretty well what happens when not using ids for resolving spaces. The linked ticket only lists the requirements.

**Closed** 2022-10-10 12:37 UTC
Labels: Type:Bug, Priority:p2-high
