### ISSUE TITLE
Forward user to space when creating one selection based

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8837] opened 2023-04-17 14:46 UTC
### Steps to reproduce
1. Select (multiple) files
2. Open context menu
3. Click on "Create space from selection"
4. Enter name
5. Hit "Create"

### Expected behaviour
After creation I get forwarded to the space because I want to work in it: Add users, edit description texts etc.

### Actual behaviour
I remain in the files app and need to manually navigate to my new space.

**Comment by JammingBen** [comment] 2023-04-17 16:02
Hmm I'm unsure about the expected behaviour 🤔 Throwing the user into a completely new view might be confusing for some, don't you think? Also, one could argue that as a user, you'd expect to stay on the current page because you want to create more spaces from other resources.

IMO it would be best to let the user decide, something like "Space was created. Go there?". But I think we don't have a component that could handle that at the moment.

**Comment by hurradieweltgehtunter** [comment] 2023-04-17 19:06
You are right, it is a decision which leaves one group of users behind. But in my point of view, the chance of a user creating multiple spaces after each other without doing sth with it or configuring it is smaller than a user, who creates a space and wants to do sth with it.

But I like your idea of having an option. Like a checkbox (I'd prefer it checked as default): "Take me to the space after creation"

**Comment by JanAckermann** [comment] 2023-04-19 08:36
Also want to add, that creating a space with a lot of data (copy actions) might take quite long, so you might change the browser tab and do something else, and be quite confused if you are in a different view some minutes later. I think this was the main reason why we've decided against that behaviour (we've already spoken about that in the team)

**Comment by hurradieweltgehtunter** [comment] 2023-04-19 08:55
> Also want to add, that creating a space with a lot of data (copy actions) might take quite long, so you might change the browser tab and do something else, and be quite confused if you are in a different view some minutes later. I think this was the main reason why we've decided against that behaviour (we've already spoken about that in the team)

You are assuming two things:
- "lot of data": Needs to be proven, if people are creating spaces this way with lots of data.
- "change the browser tab and do sth else": While this is valid for parts of our users there are also users, who don't use browser tabs. While writing the docs, it was requested to explain the term "browser tab" (ffs...). My guess: If you know how to work with multiple tabs, you won't get confused if you get forwarded to your newly created space automatically.

While your points are surely valid, it represents edge cases IMO. Also, more importantly, think about what we want to encourage the user to do. 
The complete workflow is: Create a space, configure the space, work with the space. We should 
IMO, when creating a space, we should encourage the user to configure the space furthermore. Therefore, forward to it.
If we don't forward, the chance, that the space gets forgotten or not further configured is higher.

**Comment by kulmann** [comment] 2023-04-19 11:05
I do agree that the user wants to work with the space immediately after creation, but the create+copy process is async! The user is allowed (and for a long running task even encouraged) to continue to work on other stuff. So we can't just redirect after the create+copy was finished.

I can imagine two solutions at the moment:
1. show a toast (maybe even one that doesn't auto-close) which tells the user about the space being created successfully and contains a link to the newly created space
2. a backend side notification that does the same (I prefer this one). That needs backend side work...

**Comment by tbsbdr** [comment] 2023-04-26 07:16
on hold until we receive further feedback from users. @kulmann iirc your proposal is what we mentioned in the sprintplanning, like it 👍
but, lets see if the feature is even understood und gets adoption.

**Comment by kulmann** [comment] 2024-07-18 14:38
Didn't hear any further feedback about the feature at all. Closing here as either a) it seems to be nearly irrelevant or b) it just works as expected for most people.
Thanks for the valuable input!

**Closed by kulmann** 2024-07-18 14:38 UTC
Labels: Category:Enhancement, Priority:p4-low, Topic:UX-Design
