### ISSUE TITLE
`webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:155` failed with ocis on the latest nightly build

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#6948] opened 2022-05-12 05:25 UTC
### Description
Sharing indicator test `webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:155` failed with ocis on the latest nightly build.
Needs further investigation

Build link https://drone.owncloud.com/owncloud/web/25516/60/15

### Build Log
```console
@disablePreviews @issue-2060
  Scenario: sharing indicator for file uploaded inside a shared folder # features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:155
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (243ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server
    And the administrator has set the default folder for received shares to "Shares" in the server
    And these users have been created with default attributes and without skeleton files in the server:
      │ username │
      │ Alice    │
      │ Brian    │
    And user "Alice" has created folder "simple-folder" in the server
    Given user "Alice" has shared folder "/simple-folder" with user "Brian" in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 716 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 146 milliseconds.
√ Element <#files-view> was visible after 443 milliseconds.
    When the user opens folder "simple-folder" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 26 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 108 milliseconds.
    And the user uploads file "new-lorem.txt" using the webUI
√ Element <#upload-menu-btn:not([disabled])> was visible after 24 milliseconds.
√ Element <#files-file-upload-button> was visible after 29 milliseconds.
√ Element <#upload-info> was visible after 34 milliseconds.
    Then the following resources should have share indicators on the webUI
      │ fileName      │ expectedIndicators │
      │ new-lorem.txt │ user-indirect      │
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-lorem.txt' or @data-test-resource-path='/new-lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 24 milliseconds.
waiting for 500ms ...
Timed out while waiting for element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-lorem.txt' or @data-test-resource-path='/new-lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]//*[contains(@class, "oc-status-indicators-indicator")]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10001ms)
undefinedShare indicators not found on first try, Retrying again
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-lorem.txt' or @data-test-resource-path='/new-lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 24 milliseconds.
waiting for 500ms ...
Timed out while waiting for element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-lorem.txt' or @data-test-resource-path='/new-lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]//*[contains(@class, "oc-status-indicators-indicator")]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10014ms)
undefined    ✖ failed
      AssertionError [ERR_ASSERTION]: Expected share indicators to be the same for "new-lorem.txt": expected [user-indirect] got []
          + expected - actual

          -false
          +true

          at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:1157:14)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by saw-jan** [comment] 2022-05-12 09:14
Tried to reproduce with older oCIS. There is a `flock` error log whenever the test fails.
```json
{
  "level":"error",
  "service":"storage-users",
  "pkg":"rgrpc",
  "traceid":"00000000000000000000000000000000",
  "error":"remove /home/sawjan/.ocis/storage/users/spacetypes/personal/e89ed8c4-b00d-41f2-b9d4-4e5f57453ee6.flock: no such file or directory",
  "node":"marshaling error: json: unsupported value: encountered a cycle via *node.Node",
  "time":"2022-05-12T14:55:19+05:45",
  "message":"could not convert to storage space"
}
```
So, during nightly, the cause of the failure was https://github.com/owncloud/ocis/issues/3757.

The ocis issue has been fixed and I couldn't reproduce with the latest oCIS server. Maybe the test has become more stable with the latest oCIS. So, closing here. Let's see if it appears again.

**Closed by saw-jan** 2022-05-12 09:14 UTC
Labels: QA:team
