### ISSUE TITLE
[QA] User search never reports more than 200 matches

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#5499] opened 2021-07-09 11:04 UTC
Seen in web-3.3.1 running on core 10.8.0-beta2

* Provision 1000 users, e.g. via ldap.
* Type a search that matches many. In my case, `hundred and` would match ca 900 users.
* The dropdown shows 5 and 195 more. BAD. The number is too low.
* After clicking open the "195 more" buttin, there is no additional "... more" button. BAD.

![image](https://user-images.githubusercontent.com/1108546/125068741-1b341580-e0b6-11eb-9b12-66735ab13cea.png)

**Comment by fschade** [comment] 2021-07-11 18:05
we use [owncloud-sdk](https://github.com/owncloud/owncloud-sdk) to obtain the users. The default settings for users [perPage](https://github.com/owncloud/owncloud-sdk/blob/5efc4310ba2ce24e228662b342b2a2cb472b8aa7/src/shareManagement.js#L399) is set to 200. 

the issue is fixed in [5506](https://github.com/owncloud/web/pull/5506) by adding a configuration option how many users should be listed.

this is fine ATM but should be replaced by a pagination in one of the next sprints. We create a bugfix release tomorrow because of https://github.com/owncloud/web/pull/5501 and this could also be included if we decide.

keep this open till confirmed that this is the way to go

**Comment by jnweiger** [comment] 2021-07-12 08:16
IMO an acceptable fix would be to show the correct count of search results instead of "195 more results" -- pagination would be awesome there, but even if we can technically only show the first xxx results, informing the user of the actual number is helpful.

**Closed** 2021-07-27 20:31 UTC
Labels: Priority:p3-medium, Type:Bug
