### ISSUE TITLE
e2e tests failing in nightly build in suite `e2e-tests-app-provider`

### ISSUE THREAD

**Issue by prashant-gurung899** [owncloud/web#11855] opened 2024-11-06 04:57 UTC
### Description

Nightly build is failing in the following scenario. Need some investigation and fix for it.
https://drone.owncloud.com/owncloud/web/48809/14/14

``` feature
Scenario: open office suite files with Collabora and onlyOffice (attempt 1, retried) # tests/e2e/cucumber/features/app-provider/urlJourneys.feature:10
   ✔ Before # file:/var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:28
   ✔ Given "Admin" creates following users using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:4
       | id    |
       | Alice |
   ✔ And "Alice" logs in # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ And "Alice" creates the following files into personal space using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:70
       | pathToFile       | content              |
       | OpenDocument.odt | OpenDocument Content |
   ✖ And "Alice" creates the following resources # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:7
       | resource           | type           | content                |
       | MicrosoftWord.docx | Microsoft Word | Microsoft Word Content |
       locator.fill: Timeout 30000ms exceeded.
       Call log:
         - waiting for locator('[name="app-iframe"]').contentFrame().locator('[name="frameEditor"]').contentFrame().locator('#area_id')
         -   locator resolved to <textarea readonly id="area_id" autocorrect="off" spellcheck="false" autocapitalize="none" autocomplete="extremely_off"></textarea>
         -   fill("Microsoft Word Content")
         - attempting fill action
```

**Comment by anon-pradip** [comment] 2024-11-06 08:46
Fixed by: https://github.com/owncloud/web/pull/11856 while testing locally. Let's see today's nightly build, and if its status is green then we can close this issue.

**Comment by saw-jan** [comment] 2024-11-06 09:01
> Fixed by: #11856 while testing locally. Let's see today's nightly build, and if its status is green then we can close this issue.

Please, do ocis bump. that will show if it works or not

**Comment by amrita-shrestha** [comment] 2024-11-07 05:02
do fail on ocis bump https://drone.owncloud.com/owncloud/web/48844/15/14

**Comment by anon-pradip** [comment] 2024-11-07 06:32
Confirming the issue is now resolved from the PR: https://github.com/owncloud/web/pull/11860 since no failures are occuring on CI for `app-provider`. Closing this

**Closed by anon-pradip** 2024-11-07 06:32 UTC
Labels: QA:team

**Comment by saw-jan** [comment] 2024-11-08 04:18
Related config was changed in https://github.com/owncloud/ocis/pull/10335 and drone-ci fixed by PR https://github.com/owncloud/web/pull/11863
