### ISSUE TITLE
Context menu by deleted shown inside of the rows (CERNBox)

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#5927] opened 2021-10-19 16:17 UTC
We face the problem with the context menu by deleted files in https://github.com/cernbox/web/tree/qa, so far didn't find what causes it. Appeared about a month ago.

### Steps to reproduce
1. go to "deleted files" view (not code difference in CERNBox web to owncloud web  https://github.com/cernbox/web/commits/master/packages/web-app-files/src/views/Trashbin.vue)
2. All other views are not affected by this bug

### Expected behaviour
Context menu appears on click

### Actual behaviour
Context menu is shown inside of the row

### Environment general
- latest web https://github.com/cernbox/web/commit/f6465ee8c6f7ca2033be3e98eef3cdcb522a43f1 + our changes
tested with owncloud-design-system: 
- 11.0.0
- 10.0.0
- https://github.com/cernbox/owncloud-design-system/tree/qa (our changes rebased on latest-->11.0.0)

#### Browser log
running in puppet, the html DOM element for the context menu is a different one than in other views
![contextmenu_newqa](https://user-images.githubusercontent.com/7430156/137949879-235e5819-4b9c-45cb-9342-534fce7aa67d.png)

locally the error doesn't appear with the same environment
![contextmenu_local](https://user-images.githubusercontent.com/7430156/137949863-cf11d4bd-aed8-49f5-85d3-898598fa0666.png)

**Comment by fschade** [comment] 2021-10-21 09:26
we reproduced it in a zoom meeting, the reason why this only happens is that the fileid contains a colon `context-menu-drop-pxid:000...`.

@elizavetaRa checks internally if this is a bug or the id needs to be in this format.
On our side we need to clean the ids and keep care that the format is always valid

**Comment by elizavetaRa** [comment] 2021-10-21 09:44
@ishank011 @diocas

**Comment by kulmann** [comment] 2021-11-02 10:44
I'd prefer to create the clean id in web (see helpers/resources.js from the files app) and then just use it as a given field in ODS. Reason: I think that the components in ODS should not modify data (in an ideal world) + we probably need the same clean id in web as well. What do you think?

**Comment by diocas** [comment] 2021-11-04 16:21
I understand that ODS should not modify data, but in practice we're complementing data. :)
I would counter that the fact that we use id's in the html (on the octable component) is an internal implementation detail and therefore should be hidden (web).

**Comment by fschade** [comment] 2021-11-08 19:33
@elizavetaRa can you please test https://github.com/owncloud/owncloud-design-system/pull/1766 if fixes the problem?

**Comment by fschade** [comment] 2021-11-10 09:58
i close the issue which is fixed by https://github.com/owncloud/owncloud-design-system/pull/1766. Please bump ODS to `v11.2.1`

**Closed by fschade** 2021-11-10 09:58 UTC
Labels: Type:Bug, Early-Adopter:CERN
