### ISSUE TITLE
Public Share is not displayed in "Shared with others" page

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/web#3841] opened 2020-07-28 07:30 UTC
### Steps to reproduce
1.  from ocis repo start phoenix `bin/ocis server` . For details about the setup, check the section `run tests > with Ocis backend` https://owncloud.github.io/clients/web/testing/
2. Create a folder: `folder1`
3. Create a public share with name `Public Link` for `folder1`
4. Browse to `Shared with others` page
5. `folder1` is not listed here

### Expected Behavior
1. Run normal phoenix setup with owncloud core backend
2. Repeat above steps from step 2 to step 5
3. `folder1` is listed here

**Comment by pascalwengerter** [comment] 2021-04-08 14:47
Can not reproduce, @HariBhandari07 can you confirm this still fails for you?

**Comment by pascalwengerter** [comment] 2021-06-03 10:53
Closed since I can't reproduce and received no answer

**Comment by HariBhandari07** [comment] 2021-06-03 12:20
@kiranparajuli589 @Talank  can you guys please confirm if this issue is resolved?

**Comment by Talank** [comment] 2021-06-04 07:48
Putting this in the backlog and adding a QA label.

Todo:
- [ ] Need to confirm if this issue is resolved

**Comment by Talank** [comment] 2021-06-07 08:08
Reopening to confirm if the issue is resolved.

**Comment by SwikritiT** [comment] 2021-06-07 08:35
I cannot reproduce this issue either. Maybe it has been solved . I'm closing this issue for now.

**Closed** 2021-06-07 08:35 UTC
Labels: QA:team, Type:Bug
