### ISSUE TITLE
[OCIS] sharing expiration date input not present

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#4169] opened 2020-10-15 08:48 UTC
With ocis trying to set an expiration date is not possible.

### Correct behavior
![Screenshot from 2020-10-15 14-32-59](https://user-images.githubusercontent.com/19869344/96099819-65a3af80-0ef3-11eb-9fac-ac53779c9ca0.png)

### Actual behavior
![Screenshot from 2020-10-15 14-32-52](https://user-images.githubusercontent.com/19869344/96099843-6b00fa00-0ef3-11eb-8bed-28c9441f76de.png)

**Comment by kulmann** [comment] 2021-12-03 13:27
Closing because this is not a bug in the web ui. As soon as oCIS supports expiration for "people" shares and it announces it in the capabilities, the web ui will automatically respect that and show the expiration date input field.

**Closed by kulmann** 2021-12-03 13:27 UTC
Labels: Type:Bug
