### ISSUE TITLE
Declined share disappears from the shared-with-me page

### ISSUE THREAD

**Issue by jasson99** [owncloud/web#2514] opened 2019-11-21 06:14 UTC
### Steps to reproduce
1.Share a file with eg: user1
2.Login as user1
3.Browse to the shared-with-me page
4.Delete the accepted share

### Expected behavior
When we delete the share from the shared-with-me page, the share should be present in the files list in declined state. The page reload should not be needed.

### Actual behavior
When we delete the share from the shared-with-me page, the share simply disappears from the page and the page needs to be reloaded to get the deleted shared in declined state.

**Comment by PVince81** [comment] 2020-02-27 15:54
Confirmed as I have just observed this.

**Comment by pascalwengerter** [comment] 2021-06-15 12:08
Not sure what this ticket is about since declining and deleting seem to get mixed up. Closing it as outdated since a lot of fixes around accepting/declining shares have been recently merged

**Closed by pascalwengerter** 2021-06-15 12:08 UTC
Labels: Type:Bug
