### ISSUE TITLE
Successful login redirects to different page than originally requested

### ISSUE THREAD

**Issue by willmackay** [owncloud/web#9738] opened 2023-09-27 22:54 UTC
### Steps to reproduce
1. Log out of Owncloud Web and close the window
2. Click a link to a specific directory
3. Get redirected to login page
4. Enter login credentials
5. Get redirected to a different directory than originally requested

### Expected behaviour
After login, I'd like to be redirected to either the directory I originally requested, or the root of my personal file share. Either one is fine.

### Actual behaviour
Instead, I get redirected to a directory in someone else's share which I looked at months ago. I'm not sure why, but Owncloud seems to be remembering this as the place to take me after I log in. It's the same directory every time.

### Environment general
**Operating system**: Debian GNU/Linux 11 (bullseye)

**Backend (ownCloud Core or Infinite Scale)**: Infinite Scale

**Are you using an external user-backend, if yes which one:** No

### Environment ownCloud Infinite Scale
**Version:** 4.0.1

**Updated from an older Infinite Scale or fresh install:** Updated from 2.0.0

**Where did you install Infinite Scale from:** GitHub releases page, binary Linux amd64 download

### Client configuration
**Browser / Operating system:** Reproducible on Chrome on Windows 10 and Safari on iOS. Doesn't matter which device I access Owncloud from.

**Comment by JammingBen** [comment] 2023-10-20 14:29
I can't reproduce this on my system, it always redirects to the requested folder after login. Could you try cleaning your browser storage and cookies and try again?

**Comment by willmackay** [comment] 2023-10-20 18:21
I have tried clearing cookies and storage, and the issue still occurs. One thing I've noticed is it doesn't happen if I log out manually - then, on next login, I get redirected to the page I requested. It only happens if I'm logged out because of my session expiring.

**Comment by JammingBen** [comment] 2023-12-13 11:59
Closing as duplicate of https://github.com/owncloud/web/issues/10064.

**Closed by JammingBen** 2023-12-13 11:59 UTC
