### ISSUE TITLE
back swipe causes images to not load

### ISSUE THREAD

**Issue by gedw99** [owncloud/web#8004] opened 2022-11-20 10:16 UTC
### Steps to reproduce
1. on safari desktop, go to: https://web.owncloud.com/index.html#/files/spaces/personal/demo/Photos?scrollTo=Teotihuacan.jpg&sort-by=name&sort-dir=asc&items-per-page=100
2. navigate to the 2nd or 3rd image
3. use the swipe action to go back

### Expected behaviour

going back shoudl show the previous image

### Actual behaviour

It does not show the image

### Environment general
**Operating system**:
mac, safari.

**Backend (ownCloud Core or Infinite Scale)**:

OCIS

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no just demo, demo user

### Environment ownCloud Infinite Scale
Version
[ownCloud Enterprise Edition ](https://owncloud.com/)10.11.0 (stable)

### Environment ownCloud Core
**Web server:**

**Database:**

**PHP version:**

**Version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and put the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well-sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to diligently
remove *all* hostnames, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by gedw99** [comment] 2022-11-20 10:19
same bug is also in chrome.
in chrome the back swipe on the touchpad does not work, but the classic browser backbitten does and it gets the same error

<img width="1280" alt="Screenshot 2022-11-20 at 11 18 31" src="https://user-images.githubusercontent.com/53147028/202896721-243c687a-7821-4ba6-b795-5cfa64099fd4.png">

<img width="1280" alt="Screenshot 2022-11-20 at 11 17 46" src="https://user-images.githubusercontent.com/53147028/202896726-43019bd6-62c4-454e-90f6-0aba7b520f4e.png">

**Comment by kulmann** [comment] 2022-11-21 16:14
Thanks for reporting 💪 added the issue to https://github.com/owncloud/web/issues/7979 where we currently collect and actively work on improvements for the `preview` app.

**Comment by JanAckermann** [comment] 2023-12-11 14:34
Closing here, because I am not able to reproduce anymore and we changed a lot of code since

**Closed by JanAckermann** 2023-12-11 14:34 UTC
Labels: Type:Bug, Priority:p3-medium
