### ISSUE TITLE
Selecting "delete all"

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6305] opened 2022-01-25 04:00 UTC
### Steps to reproduce
1. login to web with oCIS as the backend, showing all the files folders at the root (top) level of any user
2. select all files for batch action
3. select to delete all files

### Expected behaviour
At step 2, maybe do not select the `Shares` folder - it is known to be a special folder that cannot be deleted, moved etc.

### Actual behaviour
All files cannot be deleted, because the `Shares` folder is a special folder that cannot be deleted

### Environment general
Current master branch.

**Comment by phil-davis** [comment] 2022-01-25 04:02
I suggest that "Select all" be made smarter, and know what are "special" resources for which the multi-resource batch actions are not relevant. For such resources, do not have a checkbox to select/deselect them, and do not auto-select them when the user does "select all"

**Comment by phil-davis** [comment] 2022-01-25 06:42
@kulmann and others. Please give your opinion.

If we agree that this is a useful enhancement to make, then we can leave the failing scenario in expected-failures, thisand when the issue is worked on, a developer can make the scenario pass.

If the existing behavior is decided to be OK, then I will adjust the test scenario so that it explicitly does "select all" followed by deselect of the Shares folder, and that will pass already.

**Comment by pascalwengerter** [comment] 2022-01-25 09:47
Adding @tbsbdr and @pmaier1  here since it's a product decision (firstly and independently of how we implement & handle it in acceptance tests later)

**Comment by kulmann** [comment] 2022-01-26 09:41
The `Shares` folder doesn't have delete permissions. What do you think about just skipping the files in a batch-delete that have no delete permissions?
Question is: What should happen with the skipped items? They still have their checkbox ticket (could be cleared, which might raise confusion).

**Comment by phil-davis** [comment] 2022-01-26 09:58
Note: I think that this "mixed" permissions in a file list only occurs in a few cases:
- the `Shares` folder in the root has no delete permission, but all other resources in the root are owned by the logged-in user and can be deleted
- Favorites - the resources there could come from the user, or of all sorts of received shares, so could have different permissions

But in these cases it is all-or-nothing:
- in the Shares folder - everything can be "deleted". As the share receiver, doing that is actually an "unshare/decline" of all the shares. Nothing "really" gets deleted.
- Inside a particular received share in Shares: either the logged-in user has delete access to all the resources listed, or it is read-only and so no delete access at all.
- In shared-by-me the user is the owner of everything and can delete anything
...

I haven't looked to see what happens when in a read-only received share. Are we already smart enough not to even show the "batch delete" UI elements?

**Comment by kulmann** [comment] 2022-01-26 10:23
> I haven't looked to see what happens when in a read-only received share. Are we already smart enough not to even show the "batch delete" UI elements?

Lol, actually we have code in place that hides the `Delete` batch action as soon as **one** of the selected files/folders is not deletable. So now I need to ask: how can I reproduce the issue? Following the steps from the ticket description leads to not having a `Delete` batch action available at all.

**Comment by phil-davis** [comment] 2022-01-26 10:33
Hmmm - I haven't watched the "video" of the test scenario. So maybe it fails because there is no `Delete` batch action shown at all! And that means that there will (with the current web software) never be a `Delete` batch action available at the root level after doing "select all".

Maybe it is OK then - to delete all the real resources at the root level, the user has to "select all" then unselect "Shares", and then the `Delete` batch action should appear.

Or make `Shares` not selectable at all, because it can't be deleted, renamed etc anyway, so it has no valid/useful batch actions.

PM and UX issue - someone other than me can decide :)

**Comment by kulmann** [comment] 2022-01-26 10:50
Technically you can navigate into the `Shares` folder, that's part of the context menu and that needs adding it to the selection model. I don't want to magically skip folders during `Select all` and unfortunately we don't know in any way that the `Shares` folder is a special folder. But since the `Shares` folder will be gone anyway with the share jail I think we don't need to invest time now to fix it for the `Shares` folder in particular.

But: In general we should think about the UX for allowing a `Delete` without magically having to know which folder to deselect. The information that a file/folder can't be deleted is only indirectly visible at the moment (lack of certain available actions). But that's a different issue. This issue here can be resolved by investigating if the test needs fixing (or removal?).

**Comment by phil-davis** [comment] 2022-01-26 10:57
> This issue here can be resolved by investigating if the test needs fixing (or removal?).

If someone decides that the existing behavior is the way it will stay (until "share jail" changes makes "the system" different anyway), then I will adjust the test so that it explicitly deselects `Shares` before doing "delete all" batch action. And we can close this issue.

**Comment by pmaier1** [comment] 2022-01-26 13:53
Having "Shares" exposed as a folder in the resource listing is just a temporary thing. It will move into its own nav item soon, making this discussion obsolete. Any temporary workaround in the tests is fine, I think.

**Comment by phil-davis** [comment] 2022-01-26 14:39
PR #6319 adjusts the test scenario. We can close this issue after that PR is merged.

**Closed** 2022-01-26 15:58 UTC
Labels: Topic:UX-Design, Interaction:Question
