### ISSUE TITLE
Overwrite file dialog issues

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2027] opened 2019-09-23 16:07 UTC
### Steps

1. On disk, prepare two files "1.txt" and "2.txt"
1. In Phoenix, select "Upload file"
1. Select **both** files
1. Wait for upload
1. Select "Upload file" again
1. Select **both** files
1. Confirm overwriting for both

### Expected
Confirming twice will overwrite both files.

### Actual
Confirming "1.txt" works.
Confirming "2.txt" is not possible because the "OK" button is grayed out.

### Version
git master ee3b72eb083085296d0bde9da2f40a049d585d63

In a more general note, I think we should bring back the more advanced overwrite dialog we had before.

**Comment by LukasHirt** [comment] 2019-09-24 13:48
The current overwrite dialog needs to be dropped actually. It goes against requirements for Phoenix. Was implemented due to different project and brought to Phoenix as well. The overwrite should happen automatically if the versioning is enabled and if it's disabled then it needs to get cancelled.

**Comment by pascalwengerter** [comment] 2021-06-15 11:48
Can't reproduce on current `master`, seems to be fixed by introducing a bulk action. Closing it for now.

![Screenshot 2021-06-15 at 12-48-15 Jo - Alle Dateien - ownCloud](https://user-images.githubusercontent.com/16822008/122047382-ff4f9380-cdd7-11eb-819d-dfd3c8e2623b.png)

**Closed by pascalwengerter** 2021-06-15 11:48 UTC
Labels: Type:Bug, feature:files
