### ISSUE TITLE
"Open advanced search" button leads to empty page

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/web#9539] opened 2023-08-03 16:31 UTC
### Steps to reproduce
1. Login to ocis.ocis-web.daily.owncloud.works
2. Click "Open advanced search" button

![CleanShot 2023-08-03 at 18 26 36](https://github.com/owncloud/web/assets/214010/d731597f-c52b-4b64-a4e1-6d0ccc095cc0)

### Expected behaviour
Advanced search UI should open

### Actual behaviour
Empty page opens

![CleanShot 2023-08-03 at 18 28 09](https://github.com/owncloud/web/assets/214010/e93fc6a4-1d30-494d-b17e-751ddd80b280)

### Environment general
**Operating system**:

```
% sw_vers
ProductName:		macOS
ProductVersion:		13.5
BuildVersion:		22G74
```

**Backend (ownCloud Core or Infinite Scale)**:

```
[Log]  ownCloud Web UI 7.1.0-rc.3  (index.html-6e5abc89.mjs, line 9)
[Log]  Infinite Scale 3.1.0-beta.1+d65476ff0 Community  (index.html-6e5abc89.mjs, line 9)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale

**Version:**

```
[Log]  ownCloud Web UI 7.1.0-rc.3  (index.html-6e5abc89.mjs, line 9)
[Log]  Infinite Scale 3.1.0-beta.1+d65476ff0 Community  (index.html-6e5abc89.mjs, line 9)
```

### Client configuration

**Browser:**

```
% /usr/libexec/PlistBuddy -c "print :CFBundleShortVersionString" /Applications/Safari.app/Contents/Info.plist
16.6
```

**Operating system:**

```
% sw_vers
ProductName:		macOS
ProductVersion:		13.5
BuildVersion:		22G74
```

@tbsbdr FYI

**Comment by JammingBen** [comment] 2023-08-04 05:53
@tbsbdr Please correct me if I'm wrong, but this is expected behaviour, although a bit confusing in that case. You'll get redirected to the search result page because usually, it holds additional filters. It seems that this instance neither has tags, nor fulltext search implemented. Hence you don't see any advanced filters.

**Comment by tbsbdr** [comment] 2023-09-06 14:22
Jep, I'd also say, that the icon is misleading.
proposing here a solution: https://github.com/owncloud/web/issues/9664

**Comment by JammingBen** [comment] 2023-10-26 07:33
Resolved via https://github.com/owncloud/web/pull/9858.

**Closed by JammingBen** 2023-10-26 07:33 UTC
