### ISSUE TITLE
Public folder with single file resolves into the default app for this file

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9184] opened 2023-06-07 10:07 UTC
### Steps to reproduce
1. Make sure `options.openLinksWithDefaultApp` is enabled (which it is by default).
2. Create a folder and upload a PDF file into it
3. Share folder via public link
4. Open the public link

### Expected behaviour
The folder should be opened, file list should be displayed. `options.openLinksWithDefaultApp` should only affect single shared files, not folders.

### Actual behaviour
The file is being opened in the PDF viewer.

**Comment by JanAckermann** [comment] 2023-06-11 23:45
I am not quite sure if the problem is the `openLinksWithDefaultApp` option itself.

It seems that a shared folder with a single file containing will be rendered via the ResourceDetails template.
If this behavior is wanted, I think that it's fine that the file will be opened with the default editor. 

I think this behavior was implemented before and the new option had no impact on that. 

@kulmann @tbsbdr 
I need to know about the expected behaviour

@kulmann has this something to do how ocis is resolving the links maybe?

**Comment by kulmann** [comment] 2023-06-12 08:43
expected behaviour is like @JammingBen described it in the issue. A folder with a single file in it should be displayed as a list. Users need to be able to add additional files (create / upload), delete or rename the one existing file, and so on.

**Closed** 2023-07-03 06:17 UTC
Labels: Type:Bug, Priority:p3-medium
