### ISSUE TITLE
Disable avatar requests

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5077] opened 2021-05-07 05:27 UTC
It is not possible to change avatar in OCIS.
Disable this feature until is available to avoid network latencies.

**Comment by pascalwengerter** [comment] 2021-05-07 08:52
Took a look into that, turns out we're actually already checking for this in the frontend but the backend doesn't communicate it inside the capabilities. I'll open corresponding issues in `oCIS` and `core` to do so.

Please note that we're already tackling this in #5073 and https://github.com/owncloud/owncloud-design-system/pull/1282 which will improve the situation a lot.

**Comment by pascalwengerter** [comment] 2021-05-07 09:06
oc10 issue: https://github.com/owncloud/core/issues/38708
oCIS issue: https://github.com/owncloud/ocis/issues/2031

**Comment by kulmann** [comment] 2021-05-12 13:45
PR in oCIS: https://github.com/owncloud/ocis/pull/2036/files

**Comment by kulmann** [comment] 2021-05-12 13:45
PR in oc10 is already merged: https://github.com/owncloud/core/pull/38722

**Comment by kulmann** [comment] 2021-05-16 07:20
Since both PRs are merged I'll close this issue. Respective backend releases are pending though.

**Comment by ishank011** [comment] 2021-05-21 12:01
Observed with e229c60e423266cb55da9747851109afbfb4688d, reva 3aba8fae57b05a3e4b128decc005353393fe801d and ocis  34a8ed3816203c5beffbada29031464ec98c2575

**Comment by ishank011** [comment] 2021-05-21 12:03
Should have been enabled by https://github.com/cs3org/reva/pull/1694, as the default value for the `profile_picture` attribute is false

**Comment by ishank011** [comment] 2021-05-21 12:08
Reproducible at ocis.owncloud.works as well

**Comment by pascalwengerter** [comment] 2021-05-23 09:17
@ishank011 the issue is that we'll have to wait for the ownCloud 10.8 release to make the frontend respect the new capability. The issue is technically fixed yet not released. We can leave the ticket open or closed, no preference I suppose

**Comment by kulmann** [comment] 2021-06-18 11:56
There is an open PR in Web ( https://github.com/owncloud/web/pull/5178 ) for respecting the new capability, but we have to wait for the ownCloud 10.8 release which happens in early July.

**Closed** 2021-07-19 12:33 UTC
Labels: Early-Adopter:CERN, Topic:Performance, p3-medium
