### ISSUE TITLE
Archiver is broken for public links

### ISSUE THREAD

**Issue by fschade** [owncloud/web#6515] opened 2022-03-03 10:55 UTC
oCIS at the moment is not able to create archives for public links that are password protected.
The feature is currently disabled in the web sources and should be enabled as soon as oCIS is capable of it.

https://github.com/owncloud/web/blob/e7fdd98c041e57865d855e521b91186e1e3b1570/packages/web-app-files/src/views/PublicFiles.vue#L111

**Comment by pascalwengerter** [comment] 2022-03-18 16:01
Closed as duplicate of #6423

**Closed by pascalwengerter** 2022-03-18 16:01 UTC
Labels: Type:Bug
