### ISSUE TITLE
upload of big file 10gb takes time to be seen in web after upload completed

### ISSUE THREAD

**Issue by bishwasojha** [owncloud/web#7956] opened 2022-11-14 06:22 UTC
# Description
When a big file 10gb is uploaded, after the upload is completed, the file is not seen in web. And after some minute then file is seen in web.

### Steps to reproduce
1. upload big file 10gb in web
2. wait for it to upload 
3. After upload is completed, uploaded file isnot seen in web

### Expected behaviour
File should be seen in web after the upload is complete.

### Actual behaviour
File isnot seen in web after the upload is complete. After some minute file is seen in web.

### Environment ownCloud Infinite Scale
**Version:**  owncloud/ocis:2.0.0-rc.1
**Updated from an older Infinite Scale or fresh install:** fresh install
**issue is reproduced with oCIS** : in localstorage, docker container , s3 backend(Minio), nfs

### Client configuration
**Browser:** : Google Chrome Version 106.0.5249.61 (Official Build) (64-bit)
**Operating system:** : Ubuntu 22.04 LTS

# Additional Information
[Screencast from 14-11-22 11:36:25 पूर्वाह्न +0545.webm](https://user-images.githubusercontent.com/33860671/201587965-e80c8db2-29ec-4927-a224-24136bf2b613.webm)

**Comment by bishwasojha** [comment] 2022-11-14 06:56
- with nfs, big file isnot seen as soon as upload is completed. But seen after a few second.

**Comment by JammingBen** [comment] 2022-11-14 08:34
I don't quite get the video. You clicked on "pause" just before the upload finished. What happened next? Did the file suddenly occur a minute later?

Is it the same behaviour without clicking "pause"?

**Comment by bishwasojha** [comment] 2022-11-15 09:38
- This time i clicked `pause`, after progress bar is completed, `Upload complete` notification comes. But file doesnot appear in web.

[Screencast from 15-11-22 03:19:37 अपराह्न +0545.webm](https://user-images.githubusercontent.com/33860671/201884278-234b5688-476c-428a-b4c5-3c87a41d48fb.webm)

**Comment by JammingBen** [comment] 2022-11-15 09:45
Okay so I can reproduce it when clicking pause right before the upload is finished. This actually makes sense:

Once the file transfer to the backend is completed, the backend still needs to write all data to the storage. During this time window, the progress bar is at 100%, but the overlay still says "1 item uploading". Which is correct, because the upload-process is technically not yet finished.

Pausing or cancelling during this time window will pause/cancel the data transfer, which already finished though. So it just leads to the request being paused/cancelled. The backend still proceeds to write the data to the storage. Once this is done, the file appears in the frontend.

We can easily overcome this by disabling the pause and cancel actions during that time window. It shouldn't be possible to perform those actions then.

In general, the time window between the progress saying 100% and the upload being successful (= the file appears in the file list) is something we can't prevent from happing.

**Comment by JammingBen** [comment] 2022-11-18 11:05
Has been fixed via: https://github.com/owncloud/web/pull/7974

**Closed by JammingBen** 2022-11-18 11:05 UTC
Labels: Type:Bug
