### ISSUE TITLE
Richdocuments opens not in the app area

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#6738] opened 2022-04-05 12:57 UTC
### Steps to reproduce
1. Open a document with Collabora

### Expected behaviour
The app uses the app frame, no scrolling needed, the header is sticky

### Actual behaviour
The app breaks out the frame, the header is vanished (need to scroll)

https://user-images.githubusercontent.com/33026403/161757814-e65bc5ef-04d4-4cf4-9154-f137012adf9c.mov

<img width="1406" alt="Screenshot 2022-04-05 at 14 53 24" src="https://user-images.githubusercontent.com/33026403/161758425-23ed5553-ce21-4b9f-9938-909a34934a34.png">

### Environment general
**Backend (ownCloud Core or Infinite Scale)**:
ownCloud Core

### Environment ownCloud Infinite Scale
**Version:**
5.3.0

**Version:** (see ownCloud admin page)
10.9.1

**Comment by tbsbdr** [comment] 2023-01-19 18:23
cant reproduce, should be fixed in the meantime

**Closed by tbsbdr** 2023-01-19 18:23 UTC
