### ISSUE TITLE
webUIDeleteFilesFolders/deleteFilesFolders.feature:170 in OC10 failed in nightly and needs further investigation

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#7451] opened 2022-08-16 05:00 UTC
Build link: https://drone.owncloud.com/owncloud/web/27562/13/20
``` 
Scenario: delete a file on a public share with problematic characters # features/webUIDeleteFilesFolders/deleteFilesFolders.feature:170
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (227ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    Given user "Alice" has created file "lorem.txt" in the server
    And user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has renamed the following file in the server
      │ from-name-parts │ to-name-parts   │
      │ lorem.txt       │ simple-folder/  │
      │                 │ 'single'        │
      │                 │ "double" quotes │
      │                 │ question?       │
      │                 │ &and#hash       │
    And user "Alice" has shared folder "simple-folder" with link with "read, update, create, delete" permissions in the server
    When the public uses the webUI to access the last public link created by user "Alice" in a new session
- Connecting to selenium on port 4444...

   Response 500 POST http://selenium:4444/wd/hub/session (191ms)
   {
     value: {
       error: [
         "  (unknown error: DevToolsActivePort file doesn't exist)",
         '  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)',
         '  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 5.4.0-122-generic x86_64) (WARNING: The server did not provide any stacktrace information)',
         'Command duration or timeout: 160 milliseconds',
         "Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'",
         "System info: host: 'cb98d3a49b93', ip: '192.168.35.7', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-122-generic', java.version: '1.8.0_292'",
         'Driver info: driver.version: unknown'
       ],
       message: 'unknown error: Chrome failed to start: exited abnormally.'
     },
     status: 13
}
⚠ Error connecting to selenium on port 4444.
    ✖ failed
      Error: An error occurred while retrieving a new session: "unknown error: Chrome failed to start: exited abnormally."
          at Selenium2Protocol.handleSessionCreateError (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/transport/transport.js:110:15)
          at HttpRequest.<anonymous> (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/transport/transport.js:166:32)
          at HttpRequest.emit (events.js:400:28)
          at HttpResponse.<anonymous> (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/http/request.js:143:19)
          at HttpResponse.emit (events.js:400:28)
          at IncomingMessage.<anonymous> (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/http/response.js:60:14)
          at IncomingMessage.emit (events.js:412:35)
          at endReadableNT (internal/streams/readable.js:1333:12)
          at processTicksAndRejections (internal/process/task_queues.js:82:21)
    And the user deletes the following file using the webUI
      │ name-parts      │
      │ 'single'        │
      │ "double" quotes │
      │ question?       │
      │ &and#hash       │
    - skipped
    Then the following file should not be listed on the webUI
      │ name-parts      │
      │ 'single'        │
      │ "double" quotes │
      │ question?       │
      │ &and#hash       │
    - skipped
    And no message should be displayed on the webUI
    - skipped
    When the user reloads the current page of the webUI
    - skipped
    Then the following file should not be listed on the webUI
      │ name-parts      │
      │ 'single'        │
      │ "double" quotes │
      │ question?       │
      │ &and#hash       │
    - skipped

  Result: FAILED

saving screenshot of failed test
 Error while running .sessionAction() protocol action: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the m...

 Error while running .getScreenshot() protocol action: The session is either terminated or not started. – No active session with ID 94802b2f5daac40a5a665e7d909d0967

 Couldn't save screenshot to "./reports/screenshots/webUIDeleteFilesFolders-deleteFilesFolders_feature-L170.png":
   Error: The session is either terminated or not started. – No active session with ID 94802b2f5daac40a5a665e7d909d0967
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by SwikritiT** [comment] 2022-08-16 05:07
This looks like a selenium problem and don't think we can do anything about it

**Comment by SwikritiT** [comment] 2022-08-16 05:47
Reoccured here as well: https://drone.owncloud.com/owncloud/web/27564/47/20 on different test though 

```
1) Scenario: Create a sub-folder inside an existing folder with problematic name # features/webUICreateFilesFolders/createFolderEdgeCases.feature:62
   ✔ Before # setup.js:38
   ✖ Before # setup.js:42
       Error: An error occurred while retrieving a new session: "unknown error: Chrome failed to start: exited abnormally."
           at Selenium2Protocol.handleSessionCreateError (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/transport/transport.js:110:15)
           at HttpRequest.<anonymous> (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/transport/transport.js:166:32)
           at HttpRequest.emit (events.js:400:28)
           at HttpResponse.<anonymous> (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/http/request.js:143:19)
           at HttpResponse.emit (events.js:400:28)
           at IncomingMessage.<anonymous> (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/http/response.js:60:14)
           at IncomingMessage.emit (events.js:412:35)
           at endReadableNT (internal/streams/readable.js:1333:12)
           at processTicksAndRejections (internal/process/task_queues.js:82:21)
   - Before # setup.js:53
   - Before # setup.js:60
   - Before # setup.js:71
   - Before # stepDefinitions/filesContext.js:17
   - Before # stepDefinitions/generalContext.js:206
   - Before # stepDefinitions/generalContext.js:244
   - Before # stepDefinitions/middlewareContext.js:46
   - Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   - And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:68
   - And the user has reloaded the current page of the webUI # stepDefinitions/filesContext.js:451
   - Given user "Alice" has created folder "strängé नेपाली folder" in the server # stepDefinitions/middlewareContext.js:66
   - And the user has reloaded the current page of the webUI # stepDefinitions/filesContext.js:451
   - When the user opens folder "strängé नेपाली folder" using the webUI # stepDefinitions/filesContext.js:155
   - And the user creates a folder with the name "sub-folder" using the webUI # stepDefinitions/filesContext.js:130
   - Then folder "sub-folder" should be listed on the webUI # stepDefinitions/filesContext.js:355
   - When the user reloads the current page of the webUI # stepDefinitions/filesContext.js:447
   - Then folder "sub-folder" should be listed on the webUI # stepDefinitions/filesContext.js:355
   - And as "Alice" folder "sub-folder" should exist inside folder "strängé नेपाली folder" in the server # stepDefinitions/middlewareContext.js:66
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:262
   ✔ After # stepDefinitions/generalContext.js:231
   ✔ After # stepDefinitions/generalContext.js:172
   ✔ After # setup.js:104
   ✔ After # setup.js:100
   ✔ After # setup.js:96
   ✔ After # setup.js:89
   ✔ After # setup.js:80
```
So maybe there's something wrong

**Comment by saw-jan** [comment] 2022-08-16 11:01
Couldn't reproduce this error.

The error seems to be with the chrome. Maybe using updated chrome (updating the selenium image) might fix such issues but not sure.
It looks like we currently use `selenium/standalone-chrome-debug:3.141.59` image which has chrome version ` 94`.
There is another image `selenium/standalone-chrome` that has updated chrome. Should we care to update selenium (mainly for chrome version) image? IMO, it would be good to test on the latest versions but also catch breaking older versions.

CC @individual-it @phil-davis

**Comment by individual-it** [comment] 2022-08-16 11:23
oh they don't update the debug version anymore, strange
yes I think we should try with newer version of Chrome

**Comment by phil-davis** [comment] 2022-08-16 11:48
Note: Also see https://github.com/owncloud/core/issues/35444 - we had some problem with using the Behat-Mink-PHP test code with newer versions of `selenium/standalone-chrome-debug` - but that should only be a problem for the "classic" oC10 webUI tests.

But we should be able to try whatever selenium docker images we like in the CI of the new web.

**Comment by saw-jan** [comment] 2022-08-17 10:42
Now, the tests are run against the latest chrome version. Hopefully, that will fix this issue.
Closing here!

**Closed by saw-jan** 2022-08-17 10:42 UTC
Labels: QA:team
