### ISSUE TITLE
Overwrite file while version tab is open

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2984] opened 2020-02-07 15:02 UTC
### Steps

1. Upload a file "test.txt"
1. Open the versions tab for it
1. Upload the same file again and overwrite

### Expected result
Versions tab updates itself with a new version

### Actual result
Versions tab stays empty, needs page refresh

### Version
v0.3.0

**Comment by LukasHirt** [comment] 2020-02-12 11:15
This might be helpful in this context - https://github.com/owncloud/phoenix/issues/2573#issuecomment-580668497

**Comment by pascalwengerter** [comment] 2021-07-28 14:49
Closed as fixed, can't reproduce

**Closed by pascalwengerter** 2021-07-28 14:49 UTC
Labels: Type:Bug, feature:files
