### ISSUE TITLE
[oC10] Issues with dockerized oC10 + vite

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#8373] opened 2023-02-05 11:13 UTC
### Actual behaviour
Currently, running oC10 via `docker compose` and `web` via `pnpm build:w` forces me to restart Docker Desktop after every change, as I end up on the "Oops, something went wrong" page after my changes have been bundled. 

### Expected behaviour
Smooth sailing, similar to the dev experience with dockerized oCIS.

### Environment general
Mac M1

**Comment by dschmidt** [comment] 2023-02-05 16:05
The problem is that Vite completely wipes the dist folder from which we mount single files into the oC 10 container. There would be no problem if we just mounted the dist folder to the oC 10 container. 
To do that we need to change how the oc10 app serves the oC Web assets. There are files provided by the app and files provided by oC Web, they are merged together in a single folder, we should put them into separate folders.

**Comment by JammingBen** [comment] 2023-08-04 06:07
I'm gonna close here since oC10 support has been dropped. It's just not worth the effort we would need to put into fixing this (at least not anymore).

**Closed by JammingBen** 2023-08-04 06:07 UTC
Labels: Topic:Docker, Category:Technical
