### ISSUE TITLE
webUITrashbinFilesFolders/trashbinFilesFolders.feature:56 intermittent

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#4755] opened 2021-02-17 22:56 UTC
See comment https://github.com/owncloud/web/pull/4754#issuecomment-780564190

https://drone.owncloud.com/owncloud/web/13229/45/14
```
runsh: Total unexpected failed scenarios throughout the test run:
webUITrashbinFilesFolders/trashbinFilesFolders.feature:56
```

But the first fail was:
```
    And as "user1" the file with original path "simple-folder/lorem.txt" should exist in the trashbin
    ✖ failed
      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
      
      false !== true
      
          + expected - actual
      
          -false
          +true
      
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/webdavContext.js:176:14
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

And on the retry:
```
    Then as "user1" file "data.zip" should exist in the trashbin
    And as "user1" file "lorem.txt" should exist in the trashbin
    And as "user1" file "sample,1.txt" should exist in the trashbin
    And as "user1" folder "simple-folder" should exist in the trashbin
    And as "user1" folder "Folder,With,Comma" should exist in the trashbin
    And as "user1" the file with original path "simple-folder/lorem.txt" should exist in the trashbin
    And the deleted elements should be listed on the webUI
√ Element <#files-list-container> was present after 22 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 39 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 31 milliseconds.
√ Element <//div[contains(@class, "file-row-name")][span/text()='data' and span/text()=".zip"]/ancestor::div[@data-is-visible="true"]//div[contains(@class, "oc-file") and (@data-preview-loaded="true" or @data-preview-loaded="disabled")]> was visible after 34 milliseconds.
√ Element <#files-list-container> was present after 25 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 25 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 37 milliseconds.
√ Element <//div[contains(@class, "file-row-name")][span/text()='lorem' and span/text()=".txt"]/ancestor::div[@data-is-visible="true"]//div[contains(@class, "oc-file") and (@data-preview-loaded="true" or @data-preview-loaded="disabled")]> was visible after 33 milliseconds.
√ Element <#files-list-container> was present after 13 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 29 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 39 milliseconds.
√ Element <//span[contains(@class, "oc-file-name") and text()='simple-folder' and not(../span[contains(@class, "oc-file-extension")])]/ancestor::div[@data-is-visible="true"]//div[contains(@class, "oc-file") and (@data-preview-loaded="true" or @data-preview-loaded="disabled")]> was visible after 26 milliseconds.
√ Element <#files-list-container> was present after 16 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 28 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 33 milliseconds.
    ✖ failed
      AssertionError [ERR_ASSERTION]: Expected resource 'sample,1.txt' to be 'present' but found 'not present'
          + expected - actual
      
          -false
          +true
      
          at _callee45$ (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:825:12)
          at tryCatch (/var/www/owncloud/web/node_modules/regenerator-runtime/runtime.js:63:40)
          at Generator.invoke [as _invoke] (/var/www/owncloud/web/node_modules/regenerator-runtime/runtime.js:293:22)
          at Generator.next (/var/www/owncloud/web/node_modules/regenerator-runtime/runtime.js:118:21)
          at asyncGeneratorStep (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:77:103)
          at _next (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:79:194)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)

  Result: failed
```

The test is failed differently on each try.

Investigate and make the test reliable.

**Comment by phil-davis** [comment] 2021-02-25 11:58
I moved this into the current QA sprint project because we really do need to look into why it is intermittent. It can't just be left until the next "sprint".

If there are other intermittent web test scenarios, then they should be listed here so that they also get looked at.

**Comment by phil-davis** [comment] 2021-02-25 20:48
Also https://drone.owncloud.com/owncloud/ocis/3753/73/7
```
runsh: Total unexpected failed scenarios throughout the test run:
webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:59
```

I know that I have seen that scenario a few times in failed CI. But I can't see an issue about it. 

Anyway, it needs looking at.

**Comment by phil-davis** [comment] 2021-02-25 20:50
https://drone.owncloud.com/owncloud/ocis/3755/45/7
```
runsh: Total unexpected failed scenarios throughout the test run:
webUIDeleteFilesFolders/deleteFilesFolders.feature:12
```

Another example that should be looked into.

**Comment by jasson99** [comment] 2021-03-02 10:22
The first failure case for this scenario: webUITrashbinFilesFolders/trashbinFilesFolders.feature:56 is https://github.com/owncloud/web/issues/4784

**Comment by jasson99** [comment] 2021-03-12 04:48
> Also https://drone.owncloud.com/owncloud/ocis/3753/73/7
> 
> ```
> runsh: Total unexpected failed scenarios throughout the test run:
> webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:59
> ```
> 
> I know that I have seen that scenario a few times in failed CI. But I can't see an issue about it.
> 
> Anyway, it needs looking at.

This test seems to be failing because of the selenium issue only. Looks like selenium wasn't started properly. I could not reproduce the failure again.

**Comment by jasson99** [comment] 2021-03-12 04:50
> https://drone.owncloud.com/owncloud/ocis/3755/45/7
> 
> ```
> runsh: Total unexpected failed scenarios throughout the test run:
> webUIDeleteFilesFolders/deleteFilesFolders.feature:12
> ```
> 
> Another example that should be looked into.

This could not be reproduced locally, I have tried running the tests multiple times in this PR: https://github.com/owncloud/ocis/pull/1797

**Comment by jasson99** [comment] 2021-03-16 10:00
We can close this now. If we encounter the issue/error again later, we can open it again.

**Closed by jasson99** 2021-03-16 10:00 UTC
Labels: QA:team
