### ISSUE TITLE
Improve ownCloud visibility in external apps

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#5959] opened 2021-10-29 13:23 UTC
## Feature Request
I would find it helpful to have an ownCloud logo in the top bar, so that I clearly notice that I am within ownCloud.

For eg. CodiMD this is currently a bit hard in my opinion.

![image](https://user-images.githubusercontent.com/34452982/135402084-61f6fa3c-5240-4ea2-a1d6-99aa84685b7a.png)

Collabora on oC10 looks like that, and you clearly notice that you're within ownCloud
![image](https://user-images.githubusercontent.com/34452982/135402389-0ceb0d0f-59ce-4018-be9c-700aeccb684a.png)

_Originally posted by @wkloucek in https://github.com/owncloud/web/issues/5805#issuecomment-930877209_

**Comment by pascalwengerter** [comment] 2021-11-05 16:34
Kinda duplicate of #3520, closing this one and yes looking forward to having it fixed with the new design 😇

**Closed by pascalwengerter** 2021-11-05 16:34 UTC
