### ISSUE TITLE
Uploaded file dialog displays incorrect folder

### ISSUE THREAD

**Issue by MattPhilpot** [owncloud/web#9536] opened 2023-08-02 18:03 UTC
## Describe the bug

If uploading to a folder with at least two periods, the displayed folder in the upload dialog always removes the first.

This doesn't affect actual behavior, it is merely a UI bug  

## Steps to reproduce

1. Create folder with at least two periods. Ex: **1.2.3.4**
2. Upload file to that folder

## Expected behavior
The upload dialog displays the correct folder: **1.2.3.4**

## Actual behavior
The upload dialog displays an incorrect folder: **12.3.4**

## Setup

ownCloud = Infinite Scale
Edition = Community
Version = 3.1.0-beta.1
Web Client Version = 7.1.0-rc.1

**Comment by kobergj** [comment] 2023-08-03 13:20
Couldn't reproduce, but looks like a web issue from the description. Transferred it to web for further inspection

**Comment by jacob-nv** [comment] 2023-09-28 15:52
Issue still exists in current stable-7.1
![Screenshot from 2023-09-28 17-47-57](https://github.com/owncloud/web/assets/138569835/c0fb2e00-54cf-45fb-9a95-8ef1b9e825bb)
Not an issue anymore in current master
![Screenshot from 2023-09-28 17-50-32](https://github.com/owncloud/web/assets/138569835/81e7b20c-0546-42fc-92b8-1dc837f820b0)

**Comment by dschmidt** [comment] 2023-09-28 16:02
Maybe fixed by #9721 ?

**Comment by JammingBen** [comment] 2023-09-28 16:21
Since it's fixed on master and not a critical thing I'm closing here.

**Closed by JammingBen** 2023-09-28 16:21 UTC
Labels: Type:Bug, Priority:p4-low
