### ISSUE TITLE
%2F in folder names  converts to "/" when clicking the breadcrumbs

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#1883] opened 2019-09-02 06:32 UTC
### Steps to reproduce
1. create a folder called `folder%2Fwith%2FSlashes`
2. navigate into that folder
3. click the breadcrumbs

### Expected behaviour
- breadcrumbs should still say `folder%2Fwith%2FSlashes`
- stay in the same folder
-  no error message

### Actual behaviour
- breadcrumbs say now `folder/with/Slashes`
- error message `Loading folder failed… File with name folder/with/Slashes could not be located`

**Comment by individual-it** [comment] 2019-09-02 06:33
same happens when simply hitting the reload-button of the browser

**Comment by skshetry** [comment] 2019-11-21 10:55
Assigned to @HariBhandari07 to cover acceptance tests

**Comment by karakayasemi** [comment] 2020-04-26 15:11
Seems like there is an issue on upstream vue-router package related to our problem: https://github.com/vuejs/vue-router/issues/2725. 

The problem is happening on only initial navigation (when page refreshed). So, if you have nested 3 folders with '%2F' on their name, navigating into parent folders from breadcrumb is working without any problem. Only navigating into last child is not working, because it is refreshing the page. I do not know, why last child need to refrash page though.

**Comment by kulmann** [comment] 2020-07-02 13:23
Original issue solved in https://github.com/owncloud/phoenix/pull/3723 but the reload part is still broken

**Comment by kulmann** [comment] 2020-12-03 10:50
This was closed when the PR was merged. It is not solved entirely, yet.

**Closed** 2021-03-25 15:31 UTC
Labels: Priority:p3-medium, Type:Bug
