### ISSUE TITLE
webUISharingPublicBasic/publicLinkEdit.feature:59 fails in nightly

### ISSUE THREAD

**Issue by Talank** [owncloud/web#6826] opened 2022-04-28 09:29 UTC
https://drone.owncloud.com/owncloud/web/24959/35/20
```
1) Scenario: user tries to delete the password of an existing public link role while enforce password for that role is enforced # features/webUISharingPublicBasic/publicLinkEdit.feature:59
   ✔ Before # setup.js:41
   ✔ Before # setup.js:45
   ✔ Before # setup.js:49
   ✔ Before # setup.js:66
   ✔ Before # setup.js:73
   ✔ Before # setup.js:84
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:199
   ✔ Before # stepDefinitions/generalContext.js:237
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given the setting "shareapi_enforce_links_password_read_write_delete" of app "core" has been set to "yes" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created folder "simple-folder" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created a public link with following settings in the server # stepDefinitions/middlewareContext.js:76
       | path        | simple-folder                |
       | name        | Public-link                  |
       | permissions | read, update, create, delete |
       | password    | 123                          |
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:64
   ✔ When the user tries to edit the public link named "Public-link" of folder "simple-folder" changing the password to "" # stepDefinitions/publicLinkContext.js:151
   ✖ Then the user should see an error message on the public link edit modal dialog saying "Password can't be empty" # stepDefinitions/publicLinkContext.js:272
       Error while running "strictEqual" command: Failed [strictEqual]: (Expected values to be strictly equal:
       + actual - expected

       + {
       +   error: 'An error occurred while running .getText() command on <.oc-modal-body-input .oc-text-input-message>: ',
       +   message: 'An error occurred while running .getText() command on <.oc-modal-body-input .oc-text-input-message>: ',
       +   stack: 'Error: \n' +
       +     '    at Proxy.getErrorMessageFromModal (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js:460:18)\n' +
       +     '    at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/publicLinkContext.js:276:62)'
       + }
       - "Password can't be empty") - expected "Password can't be empty" but got: "[object Object]" (0ms)
       + actual - expected

       + {
       +   error: 'An error occurred while running .getText() command on <.oc-modal-body-input .oc-text-input-message>: ',
       +   message: 'An error occurred while running .getText() command on <.oc-modal-body-input .oc-text-input-message>: ',
       +   stack: 'Error: \n' +
       +     '    at Proxy.getErrorMessageFromModal (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js:460:18)\n' +
       +     '    at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/publicLinkContext.js:276:62)'
       + }
       - "Password can't be empty"
           at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/publicLinkContext.js:277:26)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
   - And user "Alice" should have a share with these details in the server: # stepDefinitions/middlewareContext.js:76
       | field       | value                        |
       | share_type  | public_link                  |
       | uid_owner   | Alice                        |
       | permissions | read, update, create, delete |
       | path        | /simple-folder               |
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:255
   ✔ After # stepDefinitions/generalContext.js:224
   ✔ After # stepDefinitions/generalContext.js:165
   ✔ After # setup.js:117
   ✔ After # setup.js:113
   ✔ After # setup.js:109
   ✔ After # setup.js:102
   ✔ After # setup.js:93
```

**Comment by saw-jan** [comment] 2022-05-03 07:11
re-appeared again: https://drone.owncloud.com/owncloud/web/25140/68/15

**Comment by SwikritiT** [comment] 2022-05-03 08:28
> re-appeared again: https://drone.owncloud.com/owncloud/web/25140/68/15

I'll take a look

**Comment by saw-jan** [comment] 2022-05-03 08:34
Failing consistently.

**Comment by pascalwengerter** [comment] 2022-05-03 08:40
> Failing consistently. https://drone.owncloud.com/owncloud/web/25147/68/15 https://drone.owncloud.com/owncloud/web/25140/68/15

Yes, as described in the issue it appears "as unexpected pass" a lot recently

**Comment by pascalwengerter** [comment] 2022-05-03 09:04
Probably related to the described problematic behavior/implementation outlined in #6838

**Comment by SwikritiT** [comment] 2022-05-04 06:39
Though I don't see the message `Password can't be empty`  in the UI. This line passes sometimes 
`Then the user should see an error message on the public link edit modal dialog saying "Password can't be empty"`. That's why there are `unexpected passes`. Will try to find out why that happens.

**Comment by SwikritiT** [comment] 2022-05-04 08:04
I think we need to rewrite this scenario. Technically this scenario should pass every time in ocis as well. As in the test we are checking the message `Password can't be empty`  that is present in both `oc10` and `ocis` when you select the `edit password`, and if you select apply you'll get the message `Link was updated successfully` even though the password is not changed or updated ( this is the behavior for both backends)

https://github.com/owncloud/web/blob/141691a424e248dc1b797b59e5900d58c8e61d49/tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js#L458-L463

![dailog](https://user-images.githubusercontent.com/41103328/166640809-d00c07f6-3b58-4d8a-bf5a-038194f62026.png)


When the password is enforced for links there's no `remove password` option in oc10, we should be looking for that instead
## oc10
![oc10Link](https://user-images.githubusercontent.com/41103328/166641109-93a8357f-e5ae-4546-a271-7fc60eaccc2b.png)

##OCIS
![publicLink](https://user-images.githubusercontent.com/41103328/166641841-5f6a9806-8bd0-4a54-948c-0d000f46b7a2.png)

**Comment by kulmann** [comment] 2022-05-04 10:39
@SwikritiT checked the test code, it runs the complete `changePassword` method, including the click on the submit button of the modal, and **after** that checks if the modal contains the `Password can't be empty` message. By this time the modal is usually already gone (because the submit button closes it).

**Comment by SwikritiT** [comment] 2022-05-04 11:00
@SwikritiT 
I've refactored the related test in https://github.com/owncloud/web/pull/6869, I don't think the current implementation is doing what it is supposed to do. One thing that I noticed is that when you `enforce password` for a link with certain permission as the scenario above is doing, the `remove password` option for only the Role with that permission is not shown. 

for example - The link is created with the uploader role and a password is enforced for the uploader role, now if I change the role to `Editor` I can remove the password. Now if I try to change the role back to the `Uploader`, I'll get an error message saying something like `password is required for this role`. Is this the expected/right behavior?

**Comment by kulmann** [comment] 2022-05-04 11:09
> @kulmann I've refactored the related test in #6869, I don't think the current implementation is doing what it is supposed to do. One thing that I noticed is that when you `enforce password` for a link with certain permission as the scenario above is doing, the `remove password` option for only the Role with that permission is not shown.
> 
> for example - The link is created with the uploader role and a password is enforced for the uploader role, now if I change the role to `Editor` I can remove the password. Now if I try to change the role back to the `Uploader`, I'll get an error message saying something like `password is required for this role`. Is this the expected/right behavior?

Not the expected behaviour but unfortunately something that we have to accept for the moment. The situations where you switch between different roles and passwords are enforced/not enforced for the respective role are not covered at the moment.

**Comment by SwikritiT** [comment] 2022-05-05 03:42
The tests have been refactored in https://github.com/owncloud/web/pull/6869 so closing this now

**Closed by SwikritiT** 2022-05-05 03:42 UTC
Labels: QA:team, QA:p1
