### ISSUE TITLE
Space Overview: Sidebar gets not opened If viewport is < 960px

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10598] opened 2024-03-13 13:17 UTC
## Steps to reproduce
1. set viewport in browser to 960 or smaller 
2. go to Spaces 
3. select a single Space
4. select "open sidebar"
5. Sidebar gets not opened

## Expected behavior
- sidebar gets opened

## Actual behavior
- Sidebar gets not opened

## Visual
https://github.com/owncloud/web/assets/26610733/d879a033-17cb-4422-8929-0f7da9286840

**Comment by JammingBen** [comment] 2024-03-20 07:44
@tbsbdr I can't reproduce this, could you maybe check again if it has been fixed for you?

**Comment by tbsbdr** [comment] 2024-03-20 08:05
Will do, thx!

**Comment by tbsbdr** [comment] 2024-03-20 09:42
**still reproducible**
- tried browsers:
  - FF
  - Chromium
- instances and versions:
  - infinite.owncloud.com (ocis 5.0.0, web 8.0.1)
  - ocis.ocis-web.latest.owncloud.works (ocis 5.1.0, web 9.0.0-alpha.2)

**Comment by JammingBen** [comment] 2024-03-20 10:34
Ahhh, the error doesn't exist in dev mode, but with production builds 😖 Alright, I can work with that. Thanks for checking again!

**Comment by JammingBen** [comment] 2024-03-22 08:45
Fixed via https://github.com/owncloud/web/pull/10643.

**Closed by JammingBen** 2024-03-22 08:45 UTC
Labels: Type:Bug, Priority:p3-medium, Web-only
