### ISSUE TITLE
Bug: Errors upon logout

### ISSUE THREAD

**Issue by rpocklin** [owncloud/web#4101] opened 2020-09-23 11:53 UTC
### Steps to reproduce
1.  Visit *https://phoenix.owncloud.com/index.html#/login*
2.  Login as 'demo' / 'demo'.
3.  Click the username on the RHS and select 'logout'.
4.  It appears that you have logged out successfully, but the logout handler throws 2 errors.

One error is a UI bug relating to `$_ocDrop_close` (possibly an event handler not being unsubscribed?)
The other error is a duplicate navigation error
` NavigationDuplicated: Avoided redundant navigation to current location: "/login".`

### Expected behaviour
No errors, successful logout complete.

### Actual behaviour
See screenshots for errors.
Note that if you logout from the User settings page, only the duplicate navigation error appears, not the "hide" error.

### Server configuration
**Operating system**
N/A

**Web server:**
N/A

**Database:**
N/A

**PHP version:**
N/A

**ownCloud version:** (see ownCloud admin page)
10.5.0

**Updated from an older ownCloud or fresh install:**
Online

**Where did you install ownCloud from:**
N/A

**Signing status (ownCloud 9.0 and above):**
N/A

#### Browser log
See screenshots:
![error-console](https://user-images.githubusercontent.com/876651/94009262-90648180-fde7-11ea-9c81-152a2ba3eba0.png)
![error-network](https://user-images.githubusercontent.com/876651/94009268-935f7200-fde7-11ea-8265-a463b17dca8f.png)

**Comment by pascalwengerter** [comment] 2021-03-15 17:47
Thanks for opening this issue @rpocklin, I'll take a look once we've released & deployed the latest version of our frontend (formerly called Phoenix) :)

**Comment by fschade** [comment] 2021-06-15 11:36
the `$_ocDrop_close` and navigation duplication errors do not happen anymore, instead browser console now complains with different errors.

cc @pascalwengerter 

<img width="727" alt="Bildschirmfoto 2021-06-15 um 13 35 13" src="https://user-images.githubusercontent.com/49308105/122045896-8acc2300-cdde-11eb-8199-118e426172c5.png">

**Comment by pascalwengerter** [comment] 2021-11-11 16:53
@rpocklin can't reproduce this on https://ocis.ocis-web.latest.owncloud.works, and closing this issue for now. Please re-open if you stumble upon this again

**Closed by pascalwengerter** 2021-11-11 16:53 UTC
Labels: Type:Bug, Web-Fastlane
