### ISSUE TITLE
[oCIS] Previewing video from mediaviewer pops up a sign-in dialog

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5840] opened 2021-09-27 06:38 UTC
### Steps to reproduce
1. run `web` with `oCIS`
1. upload a video file
2. `Open in Mediaviewer` from file menu

### Expected behaviour
To see video playback without signin dialog

### Actual behaviour
![signin_dialog](https://user-images.githubusercontent.com/52366632/134855612-d280a090-fde2-402f-8386-8261b35d2d3d.png)

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
WEB_VERSION=(commit-id: a330d27b7706118d974d219d6d30776e730907ed)
BRANCH=master
```

```console
OCIS_VERSION=(commit-id: 67219f1ed1847325bb2882bc6f9600f1fa0fdfd1)
BRANCH=master
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by refs** [comment] 2021-09-29 11:17
@saw-jan as of the latest master I am not able to reproduce this one any longer 🤔

**Comment by refs** [comment] 2021-09-29 11:19
also not happening on the test deployment https://ocis.ocis-traefik.latest.owncloud.works/#/

**Comment by pascalwengerter** [comment] 2021-09-29 11:34
Probably has been fixed via https://github.com/owncloud/ocis/pull/2557 thanks to @C0rby, closing for now

**Comment by pascalwengerter** [comment] 2021-09-29 11:38
Sorry, reopen and let @refs decide when it's "done"

**Closed** 2021-09-29 12:24 UTC
Labels: Type:Bug

**Comment by pascalwengerter** [comment] 2021-09-29 12:30
We need to removed the expected failure in `web` as well, but I'll take care of this later
