### ISSUE TITLE
Cannot login to locally hosted `web` manually (latest commit)

### ISSUE THREAD

**Issue by sakshamgurung** [owncloud/web#6010] opened 2021-11-10 08:54 UTC
### Steps to reproduce
1. Pull the latest commit id of master branch `1155e0011e8fa711c7574cb12564980ddb1246ff`
2. Install dependencies: `yarn install`
3. Serve from `web` folder: `OCIS_INSECURE=true yarn serve`
4. Open browser and goto url: `http://localhost:9100/`

### Expected behaviour
In my browser I want to login and see my files page.

### Actual behaviour
Login credentials -> Authorize user -> Stuck with loading icon. I have one older branch which is working fine but latest commit is not.

![Hnet-image](https://user-images.githubusercontent.com/41365307/141080620-8e3a250b-a35e-45ae-858b-7582f71d5b1a.gif)

### Server configuration
**Operating system**:
Ubuntu 20.04.3 LTS
**Web server:**
Apache
**Database:**
mysql  Ver 8.0.26-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
**PHP version:**
PHP 7.4.3
**ownCloud version:** (see ownCloud admin page)
Latest master branch from github repo `1155e0011e8fa711c7574cb12564980ddb1246ff`
**Updated from an older ownCloud or fresh install:**
Fresh install
**Where did you install ownCloud from:**
Github

**Comment by sakshamgurung** [comment] 2021-11-12 06:48
@phil-davis After running git bisect it is found that this issue starts after the introduction of "public token" commit id: `936a57b5bfa11c4e08b27f8b98a5bcf91c9d8431` merged on 8 Nov 2021. Please checkout the problem.

**Comment by phil-davis** [comment] 2021-11-12 07:01
That commit is of PR #5924

**Comment by phil-davis** [comment] 2021-11-12 07:10
Is this related to https://github.com/owncloud/ocis/pull/2745 and the dev doc PR https://github.com/owncloud/ocis/pull/2746 ?

Set env var `OCIS_INSECURE=true` to make the dev environment work.

**Comment by pascalwengerter** [comment] 2021-11-12 07:21
Documented [here](https://owncloud.dev/ocis/development/testing/#run-ocis), @phil-davis can we close the issue then? 🤗

**Comment by sakshamgurung** [comment] 2021-11-12 08:10
@pascalwengerter This solve my problem with `web + ocis` which was prompting message `You are not allowed to use this application.`.
But with `web + oc10` the problem still persist. I am using this command:`OCIS_INSECURE=true yarn serve ` from `/web` directory.

**Comment by pascalwengerter** [comment] 2021-11-12 08:12
> @pascalwengerter This solve my problem with `web + ocis` which was prompting message `You are not allowed to use this application.`. But with `web + oc10` the problem still persist. I am using this command:`OCIS_INSECURE=true yarn serve ` from `/web` directory.

What are you doing/trying to achieve? I've been using a dockerized OC10 using the web master's dist folder yesterday without any issues

**Comment by sakshamgurung** [comment] 2021-11-12 08:26
> What are you doing/trying to achieve? I've been using a dockerized OC10 using the web master's dist folder yesterday without any issues
I am manually trying to use the `web` (not docker) for some inspection with failed webUI tests.

**Comment by pascalwengerter** [comment] 2021-11-12 08:28
> > What are you doing/trying to achieve? I've been using a dockerized OC10 using the web master's dist folder yesterday without any issues
> 
> I am manually trying to use the `web` (not docker) for some inspection with failed webUI tests.

Running them according to https://owncloud.dev/clients/web/testing/ on current master? Could you send me the tests that are failing, too?

**Comment by sakshamgurung** [comment] 2021-11-12 08:32
> > > What are you doing/trying to achieve? I've been using a dockerized OC10 using the web master's dist folder yesterday without any issues
> > 
> > 
> > I am manually trying to use the `web` (not docker) for some inspection with failed webUI tests.
> 
> Running them according to https://owncloud.dev/clients/web/testing/ on current master? Could you send me the tests that are failing, too?

`yarn test:acceptance:oc10 features/webUISharingInternalGroups/shareWithGroups.feature:255 `
PR: https://github.com/owncloud/web/issues/5992

**Comment by pascalwengerter** [comment] 2021-11-12 08:47
> > > > What are you doing/trying to achieve? I've been using a dockerized OC10 using the web master's dist folder yesterday without any issues
> > > 
> > > 
> > > I am manually trying to use the `web` (not docker) for some inspection with failed webUI tests.
> > 
> > 
> > Running them according to https://owncloud.dev/clients/web/testing/ on current master? Could you send me the tests that are failing, too?
> 
> Ok I will try. Here is the test `yarn test:acceptance:oc10 features/webUISharingInternalGroups/shareWithGroups.feature:255 ` PR: #5992

Can't reproduce, with the dockerized OC10 the test runs fine/passes :/

**Comment by sakshamgurung** [comment] 2021-11-12 08:54
> Can't reproduce, with the dockerized OC10 the test runs fine/passes :/

Yes It's intermittent fail.

**Comment by pascalwengerter** [comment] 2021-11-12 13:05
> > Can't reproduce, with the dockerized OC10 the test runs fine/passes :/
> 
> Yes It's intermittent fail.

But do you serve the web assets from the oCIS service? If so, why instead of using the dev server or a watched, build dist?

**Comment by sakshamgurung** [comment] 2021-11-12 13:28
@pascalwengerter Many of our co-worker is having same issue I will consult them and close the issue after that. I will talk them coming Monday.

**Comment by pascalwengerter** [comment] 2021-11-12 13:39
> @pascalwengerter Many of our co-worker is having same issue I will consult them and close the issue after that. I will talk them coming Monday.

Can you confirm that you're serving the web assets from oCIS when testing against OC10? If so, we can have a call on Monday and show you a different (and perhaps easier) approach to do so?

**Comment by sakshamgurung** [comment] 2021-11-12 14:46
- Everything is working well when serving `web` assets from oCIS , and testing against API tests (from `core`) and webUI tests (from `web`).
- serving `web` using  `yarn serve` (from `web` source code) is showing this issue. webUI test (from `web`) is also showing this issue

**Comment by sakshamgurung** [comment] 2021-11-12 14:52
> 
> 
> > @pascalwengerter Many of our co-worker is having same issue I will consult them and close the issue after that. I will talk them coming Monday.
> 
> Can you confirm that you're serving the web assets from oCIS when testing against OC10? If so, we can have a call on Monday and show you a different (and perhaps easier) approach to do so?

Serving the `web` assets from ocis is working fine. The issue was while using `yarn serve` from the web project itself which is using oc10.

**Comment by individual-it** [comment] 2021-11-16 06:44
@pascalwengerter we dug a bit deeper and the problem is in fetching the capabilities
Sakscham and also me, we are running core in a subfolder e.g. `http://localhost/owncloud-core`, that is also set in the config.json but in https://github.com/owncloud/web/blob/e9decfb03d610eb473a3b18a0a4a8227e9387029/packages/web-runtime/src/store/user.js#L202 the path is overwritten again
#6031 should fix it

@sakshamgurung please try it

**Closed** 2021-11-16 07:48 UTC
Labels: Type:Bug
