### ISSUE TITLE
[admin-settings] Spaces: Context menu inconsistent

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#9027] opened 2023-05-12 07:26 UTC
### Steps to reproduce
1. Go to admin settings -> Spaces
2. Right click on a space

### Expected behaviour
Context menu is more consistent regarding action item labels

### Actual behaviour
![grafik](https://github.com/owncloud/web/assets/16665512/64d54bf9-cada-4e07-941f-bc391348eb2d)

english:
![grafik](https://github.com/owncloud/web/assets/16665512/5769229b-5534-423c-b07f-63ed34350fb3)

english with 2 spaces selected:
![grafik](https://github.com/owncloud/web/assets/16665512/400c6d48-abd8-4ad8-979f-be49c02cd297)

**Comment by JammingBen** [comment] 2023-05-12 07:55
Sorry, I don't get it 🙈 Could you elaborate a bit more on what the issue is and what you mean by "more consistent"?

**Comment by hurradieweltgehtunter** [comment] 2023-05-12 08:05
sure :)

at least the german one:
Quota ändern - No counter added
Deaktiviere (1) - counter appended, conjugated verb
(1) aktivieren - counter prepended, non-conjugated verb
Lösche (1) - counter appended, conjugated verb

Proposal:
Single Selection:
Space-Quota ändern
Space deaktivieren
Space aktivieren
Space löschen

Multiple selection:
2 Space-Quotas ändern
2 Spaces deaktivieren
2 Spaces aktivieren
2 Spaces löschen

labels are always formatted in the format <entity> <verb>, like `Ordner öffnen`, `Datei löschen` so I think we should align it to that in this case too.
Not sure about the english ones, for now.

**Comment by JammingBen** [comment] 2023-05-12 08:11
Thanks for the clarification!

> labels are always formatted in the format {entity} {verb}, like Ordner öffnen, Datei löschen so I think we should align it to that in this case too.

But that's not really the case for file/space actions in general, no? When we look at the normal file actions ("Open folder" being the only exception). I find the entity is redundant in such context because you've already selected the entity beforehand.

<img width="311" alt="image" src="https://github.com/owncloud/web/assets/50302941/61f97281-77a8-40d4-b2cf-e8c7cd448d09">

**Comment by hurradieweltgehtunter** [comment] 2023-05-12 08:15
Yeah you're right 🤒  I only looked at "Open folder", which is different than the other ones.
Anyhow, in the shown screenshot there a few things mixed up IMO. So maybe better proposal:

Space-Quota ändern
Deaktivieren
Aktivieren
Löschen

Multiple selection
2 Space-Quotas ändern
2 Spaces deaktivieren
2 Spaces aktivieren
2 Spaces löschen
(Adding here the entity `Spaces` because displaying without it `2 deaktiveren` is missing context IMO)

**Comment by JammingBen** [comment] 2023-05-12 08:32
Okay, now I think I fully understood 😄  The counter should indicate that an action can't be applied to all selected resources. E.g. you select 3 spaces, but only one of them can be disabled because the other 2 already are -> It shows `Disable (1)` (in German it should say `Deaktivieren (1)`).

So, things that are not ideal currently:

* The German translations including a counter need to be adjusted to the format `{action} ({counter})` (like the English ones). The translations for the labels without counter are fine.
* Hide the counter if an action applies to all selected resources because it is redundant and is missing its purpose.

**Comment by JammingBen** [comment] 2023-10-09 15:12
The counter is gone meanwhile, hence closing here.

**Closed by JammingBen** 2023-10-09 15:12 UTC
Labels: Type:Bug, Priority:p4-low
