### ISSUE TITLE
Main menu does not work in safari

### ISSUE THREAD

**Issue by DionTimmermann** [owncloud/web#11718] opened 2024-10-04 01:34 UTC
## Describe the bug
Clicking on an item in the main menu (3-by-3 grid at top left) does not open the desired page when using safari.

Likely reason: The menu disappears on mouse down, but the link would only be clicked on mouse up.

## Steps to reproduce
1. Open OCIS in Safari (I am using the admin user created during installation).
2. Click on the main menu (3-by-3 grid at top left. 
3. The menu opens with 4 icons (Files, Text Editor, App Store, Admin Settings)
4. Click on any item in the menu.

## Expected behavior
The clicked-on page opens and the menu disappears.

## Actual behavior
The menu disappears, but the page is not changed.

## Setup
I used a fresh install of OCIS 6.5.0 with Web client version 10.3.0. I used `sudo -u ocis ocis init --config-path /containers/ocis/config --admin-password "XXXXX" --insecure true` to configure the server.
The server runs on a machine in my local network and is behind a nginx reverse proxy with the recommended additional settings:
```
        # OIDC Tokens in headers are quite large and can exceed default limits of reverse proxies
        proxy_buffers 4 256k;
        proxy_buffer_size 128k;
        proxy_busy_buffers_size 256k;

        # Disable checking of client request body size
        client_max_body_size 0;
``` 
## Additional context
- The problem only ocurs with safari [I currently use Version 16.6 (18615.3.12.11.2)]. With chrome everything works as expected.
- I do not see any errors in the safari developer console, except a failure to load `/ocs/v2.php/apps/notifications/api/v1/notifications/sse`, which I guess is not related.
- Open the pages by entering the respective url in the browser's menu bar, works. E.g. going to `admin-settings/general` loads the  "Admin Settings". The menu also does not work on these pages.

In safari, the menu disappears immediately when I press the mouse button. In chrome, the menu stays open when I press the mouse button. The menu item is only selected/clicked when I release the mouse button. I am unsure if the menu is closed on mouse up or only when the new page is loaded.

**Comment by pascalwengerter** [comment] 2024-10-04 06:55
If only every issue opened was this detailed 🙏🏽 ☺️

**Comment by kulmann** [comment] 2024-10-04 07:53
> If only every issue opened was this detailed 🙏🏽 ☺️

I second that 😍 Thank you for the detailed bug report!

Also, I can confirm the bug in Safari 17.5. And your assumption @DionTimmermann seems to be correct, when I comment out the `hide` function body on the dropdown the app switcher works as expected in Safari (without closing)... need to investigate further.

**Comment by DionTimmermann** [comment] 2024-10-06 20:54
Thank you for the quick reaction!

I was about to open a new bug report, but based on the wording in the code, the bugfix above should also solve the following issue:

The "My Account" menu at top right also does not work in Safari. It seems to be exactly same behaviour as with the "Application Switcher".

**Comment by AlexAndBear** [comment] 2024-10-06 21:21
> Thank you for the quick reaction!
> 
> I was about to open a new bug report, but based on the wording in the code, the bugfix above should also solve the following issue:
> 
> The "My Account" menu at top right also does not work in Safari. When I click on the "My Account" Menu it opens up, but clicking on e.g. "Preferences" just closes the menu. It seems to be exactly same behaviour as with the "Application Switcher".

Thank you, I identified the issue and the (not merged, yet) bugfix should solve all the issues with drop menus.

**Closed** 2024-10-07 04:08 UTC
Labels: Type:Bug, Priority:p2-high
