### ISSUE TITLE
Nightly failed on webUISharingPermissionsUsers/sharePermissionsUsers.feature

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#7409] opened 2022-08-05 06:51 UTC
Build: https://drone.owncloud.com/owncloud/web/27359/62/15
```feature
@issue-ocis-2260
  Scenario Outline: share a folder with another internal user assigning a role and the permissions # features/webUISharingPermissionsUsers/sharePermissionsUsers.feature:84
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (239ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server
    And the administrator has set the default folder for received shares to "Shares" in the server
    And these users have been created with default attributes and without skeleton files in the server:
      │ username │
      │ Alice    │
      │ Brian    │
    And user "Brian" has created folder "simple-folder" in the server
    And user "Brian" has created folder "simple-empty-folder" in the server
    And user "Brian" has created folder "simple-folder/simple-empty-folder" in the server
    And user "Brian" has uploaded file "data.zip" to "data.zip" in the server
    And user "Brian" has uploaded file "lorem.txt" to "lorem.txt" in the server
    And user "Brian" has uploaded file "lorem.txt" to "simple-folder/lorem.txt" in the server
    Given user "Brian" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 666 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 173 milliseconds.
√ Element <#files-view> was visible after 603 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 27 milliseconds.
    When the user shares folder "simple-folder" with user "Alice Hansen" as "Custom permissions" with permissions "update, share" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 21 milliseconds.
waiting for 500ms ...
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 10 milliseconds.
√ Element <#files-share-invite-input> was visible after 22 milliseconds.
√ Element <#new-collaborators-form .vs__dropdown-menu .files-collaborators-autocomplete-user-text> was visible after 27 milliseconds.
√ Element <#files-collaborators-role-button-new> was visible after 27 milliseconds.
    ✖ failed
      Error: permission update is not visible
          at Proxy.toggleSinglePermission (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js:316:15)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.changeCustomPermissionsTo (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js:300:11)
          at Proxy.changeCollaboratorRole (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js:236:9)
          at Proxy.shareWithUserOrGroup (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js:187:7)
    And user "Alice" accepts the share "Shares/simple-folder" offered by user "Brian" using the sharing API in the server
    - skipped
    Then user "Alice Hansen" should be listed as "Custom permissions" in the collaborators list for folder "simple-folder" on the webUI
    - skipped
    And custom permissions "share, update" should be set for user "Alice Hansen" for folder "simple-folder" on the webUI
    - skipped
    And user "Alice" should have received a share with these details in the server:
      │ field       │ value                 │
      │ uid_owner   │ Brian                 │
      │ share_with  │ Alice                 │
      │ file_target │ /Shares/simple-folder │
      │ item_type   │ folder                │
      │ permissions │ <permissions>         │
    - skipped
saving screenshot of failed test
```

**Comment by grgprarup** [comment] 2022-08-10 05:39
Passed in every run

**Comment by SwikritiT** [comment] 2022-08-22 04:16
This issue has not occurred in recent nightly builds, so moving in the backlog. It can be brought back if it re-appears.

**Comment by SwikritiT** [comment] 2022-11-28 04:03
This issue hasn't re-occurred in a long while, the tests need to be run for few times locally and can be closed if they don't fail.

**Comment by amrita-shrestha** [comment] 2022-11-29 03:27
can't reproduce currently so closing this issue for now.

**Closed by amrita-shrestha** 2022-11-29 03:27 UTC
Labels: QA:team
