### ISSUE TITLE
Show members sidebar doesn't adapt to the page size

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#10396] opened 2024-01-23 16:20 UTC
ocis 5.1.0-prealpha+17b14ee78
web 8.0.0-rc.1

Steps: 
- create space
- reduce page size 
- click by members
<img width="346" alt="Screenshot 2024-01-23 at 17 26 14" src="https://github.com/owncloud/web/assets/84779829/0f1905a7-21e8-4a45-a37f-eb7c266be5fc">

Actual: nothing happens. it looks like the button doesn't work.

https://github.com/owncloud/web/assets/84779829/5970f206-6b83-40e3-8551-5116be8611f8

**Comment by JammingBen** [comment] 2024-01-26 06:03
I can't reproduce it locally, which browser are you using? Does the console show anything?

**Comment by ScharfViktor** [comment] 2024-01-26 10:02
> which browser are you using? 

Web client version | 8.0.0-rc.1 
Browser: chrome Version 121.0.6167.85
 

> I can't reproduce it locally, 

open please members sidebar and try to resize page


https://github.com/owncloud/web/assets/84779829/1ffba002-137c-42db-8ce9-4ce76b3d2330



> Does the console show anything?

console log: 
```
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at x (web-app-files-eW8qBfEe.mjs:1:94026)
```

**Comment by AlexAndBear** [comment] 2024-02-27 14:30
Not reproducible on master anymore, closing as completed

**Closed by AlexAndBear** 2024-02-27 14:30 UTC
Labels: Type:Bug, Priority:p4-low
