### ISSUE TITLE
HTML lang attribute not set on load

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#9288] opened 2023-06-23 09:31 UTC
### Steps to reproduce
Make sure to have a non-english language set
1. Login
2. Check `lang` attribute on html element in dev console

### Expected behaviour
attribute should be set to same language as the page is displayed

### Actual behaviour
Attribute is initially (= after login) set to `en` although the visible language is a different one. 

AFAIK this should be set correctly for accessibility reasons.

https://ocis.ocis-wopi.latest.owncloud.works/

**Comment by JanAckermann** [comment] 2023-06-28 13:38
I can't reproduce this, please reopen and add detailed steps if you think the error still persists

**Comment by hurradieweltgehtunter** [comment] 2023-07-04 07:08
1. Make sure you have set non-english language on your account (in my example: german)
2. Login in **private tab**
3. Open dev-console, check `lang` attribute on `<html>` element

-> it is set to `en` no matter what. Changes if you change the language after login and gets set correctly if you login and login in the same browser. 
It seems that if there's no language setting stored in web storage it gets not set correctly.

**Comment by jacob-nv** [comment] 2023-10-10 13:26
@hurradieweltgehtunter
@JammingBen 
Not able to reproduce it, maybe it's fixed by now.
Did I miss any steps?

https://github.com/owncloud/web/assets/138569835/78f8cdeb-aff2-4aa5-a1f1-a6757a22a1b8

**Comment by JammingBen** [comment] 2023-10-20 14:24
I can't reproduce the issue either. @hurradieweltgehtunter could you please try again, maybe it has been fixed meanwhile? Or if the issue still exists for you, mind sharing a short screen capture? 🙂

**Comment by JammingBen** [comment] 2023-12-12 15:47
Closing here since nobody can reproduce it here. Feel free to re-open at any time if necessary.

**Closed by JammingBen** 2023-12-12 15:47 UTC
Labels: Type:Bug, Priority:p4-low
