### ISSUE TITLE
Secret File Drop: Folder Structure Gets Lost

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10403] opened 2024-01-26 09:01 UTC
## Steps to reproduce
1. on your desktop: create a folder that contains another folder like:
```
├── Folder1/
│   ├── File1.txt
│   └── File2.txt
└── Folder2/
    │   ├── File3.txt
    │   └── File4.txt
```
2. create a Secret File Drop and upload whole `Folder1`
3. Folder structure gets lost (`Folder1` and `Folder2`) is not there any more

## Expected behavior
- Folder structure is persisted
```
├── Folder1/
│   ├── File1.txt
│   └── File2.txt
└── Folder2/
    │   ├── File3.txt
    │   └── File4.txt
```

## Actual behavior
Folder structure gets lost
```
── File1.txt
── File2.txt
── File3.txt
── File4.txt
```
## Comment
likely a backend issue but let's collect all info first

**Comment by JammingBen** [comment] 2024-01-26 09:10
Duplicate of https://github.com/owncloud/web/issues/2443, hence closing in favour of this issue. Note that there is nothing we can do about this currently (https://github.com/owncloud/web/issues/2443#issuecomment-1128893759).

**Closed by JammingBen** 2024-01-26 09:10 UTC
Labels: Type:Bug
