### ISSUE TITLE
[OCIS] a shared sub folder doesn't shows the parent in sharing sidebar.

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#4168] opened 2020-10-15 08:31 UTC
## Steps to reproduce

1. as `user1` create a folder with structure `top/sub`
2. Share the folder `top` with `user2`
3. login as user2 and share `Shares/top` with `user3`
4. login as user3 and open folder `Shares/top`
5. Open people tab in sidebar for folder `top`

### Expected behavior
1. The share item should show the parent name by which it is shared.

### actual behavior
1. It doesn't shows the parent name

screenshots.

in OC10 (correct behavior)
![Screenshot from 2020-10-15 14-11-47](https://user-images.githubusercontent.com/19869344/96097681-faf17480-0ef0-11eb-9473-33b83aef4603.png)

in ocis (actual behavior)
![Screenshot from 2020-10-15 14-11-54](https://user-images.githubusercontent.com/19869344/96097710-02188280-0ef1-11eb-84d5-eba3eb7371b3.png)

**Comment by kulmann** [comment] 2021-12-03 16:13
Note: the `via` information has been moved to the `Details` some weeks ago. The bug might still apply for oCIS, just needs to be checked elsewhere.

**Comment by pascalwengerter** [comment] 2022-05-16 09:27
From the way I read the reproduction steps it looks like this is an issue with resharing, which isn't enabled in oCIS yet? 🤔

**Comment by tbsbdr** [comment] 2022-06-28 15:14
the via tag is back. closing..
![screenie_Brave Browser_2022-06-28_at_17-13-41@2x](https://user-images.githubusercontent.com/26610733/176215819-df385738-7cde-4b18-91ba-24438733faae.png)

**Closed by tbsbdr** 2022-06-28 15:14 UTC
Labels: Type:Bug, Priority:p2-high
