### ISSUE TITLE
Flaky e2e tests

### ISSUE THREAD

**Issue by kobergj** [owncloud/web#8648] opened 2023-03-20 10:21 UTC
Sorry if I duplicate, but I couldn't find another ticket for flaky e2e tests. During web bump to `v7.0.0-rc.22` the following two tests were failing. Both were failing once and got green on a retry

1 - `tests/e2e/cucumber/features/smoke/share.ocis.feature:9`  Test times out while trying to share an item through the side panel https://drone.owncloud.com/owncloud/ocis/20537/86/9 

<details>
<summary>Test log</summary>

```feature
Feature: share # tests/e2e/cucumber/features/smoke/share.ocis.feature:1

  Scenario: folder # tests/e2e/cucumber/features/smoke/share.ocis.feature:9
    Given "Admin" creates following users
      │ id    │
      │ Alice │
      │ Brian │
    Given "Alice" creates the following folder in personal space using API
      │ name                   │
      │ folder_to_shared       │
      │ folder_to_customShared │
      │ shared_folder          │
    And "Alice" logs in
    And "Alice" opens the "files" app
    And "Alice" uploads the following resource
      │ resource      │ to                     │
      │ lorem.txt     │ folder_to_shared       │
      │ lorem-big.txt │ folder_to_customShared │
    When "Alice" shares the following resource using the sidebar panel
      │ resource               │ recipient │ type │ role                                  │ resourceType │
      │ folder_to_shared       │ Brian     │ user │ editor                                │ folder       │
      │ shared_folder          │ Brian     │ user │ editor                                │ folder       │
      │ folder_to_customShared │ Brian     │ user │ custom_permissions:read,create,delete │ folder       │
    And "Brian" logs in
    And "Brian" opens the "files" app
    And "Brian" navigates to the shared with me page
    And "Brian" accepts the following share
      │ name                   │
      │ folder_to_shared       │
      │ folder_to_customShared │
    And "Brian" declines the following share
      │ name          │
      │ shared_folder │
    Then "Brian" should not be able to open the folder "shared_folder"
    When "Brian" accepts the following share from the context menu
      │ name          │
      │ shared_folder │
    And "Brian" copies quick link of the resource "shared_folder" from the context menu
    And "Brian" declines the following share from the context menu
      │ name          │
      │ shared_folder │
    And "Brian" renames the following resource
      │ resource                   │ as            │
      │ folder_to_shared/lorem.txt │ lorem_new.txt │
    And "Brian" uploads the following resource
      │ resource        │ to                     │
      │ simple.pdf      │ folder_to_shared       │
      │ testavatar.jpeg │ folder_to_customShared │
    When "Brian" deletes the following resources using the sidebar panel
      │ resource      │ from                   │
      │ lorem-big.txt │ folder_to_customShared │
    ✖ failed
      page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
          at clickResource (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/resource/actions.ts:70:18)
          at deleteResource (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/resource/actions.ts:375:17)
          at Resource.delete (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/resource/index.ts:57:9)
          at processDelete (/drone/src/webTestRunner/tests/e2e/cucumber/steps/ui/resources.ts:196:9)
          at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/ui/resources.ts:38:5)
    And "Alice" opens the "files" app
    - skipped
    And "Alice" uploads the following resource
      │ resource          │ to               │ option  │
      │ PARENT/simple.pdf │ folder_to_shared │ replace │
    - skipped
    And "Brian" downloads old version of the following resource
      │ resource   │ to               │
      │ simple.pdf │ folder_to_shared │
    - skipped
    And "Brian" restores following resources
      │ resource   │ to               │ version │
      │ simple.pdf │ folder_to_shared │ 1       │
    - skipped
    And "Alice" removes following sharee
      │ resource               │ recipient │
      │ folder_to_customShared │ Brian     │
    - skipped
    When "Alice" deletes the following resources using the sidebar panel
      │ resource         │ from             │
      │ lorem_new.txt    │ folder_to_shared │
      │ folder_to_shared │                  │
    - skipped
    And "Alice" logs out
    - skipped
    Then "Brian" should not be able to see the following shares
      │ resource               │ owner        │
      │ folder_to_customShared │ Alice Hansen │
      │ folder_to_shared       │ Alice Hansen │
    - skipped
    And "Brian" logs out
    - skipped
```
</details>

2 - `tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature:3`  User unable to log in https://drone.owncloud.com/owncloud/ocis/20540/86/9 

Two types of error while logging in 

<details>
<summary>Test log</summary>

```feature
Scenario: unstructured collection of testable space interactions, # tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature:3

....
And "Alice" uploads the following resources
      │ resource  │ to           │
      │ lorem.txt │ folderPublic │
    And "Alice" creates a public link for the resource "folderPublic" using the sidebar panel
    And "Alice" renames the most recently created public link of resource "folderPublic" to "team.2"
    And "Alice" edits the public link named "team.2" of resource "folderPublic" changing role to "uploader"
    And "Alice" sets the expiration date of the public link named "team.2" of resource "folderPublic" to "+5 days"
    And "Alice" sets the password of the public link named "team.2" of resource "folderPublic" to "54321"
    When "Anonymous" opens the public link "team.1"
    And "Anonymous" unlocks the public link with password "12345"
    And "Anonymous" drop uploads following resources
      │ resource     │
      │ textfile.txt │
    And "Brian" logs in
    ✖ failed
      locator.fill: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for locator('#oc-login-username')
      ============================================================
          at Ocis.login (/drone/src/webTestRunner/tests/e2e/support/objects/runtime/session.ts:12:56)
          at Session.login (/drone/src/webTestRunner/tests/e2e/support/objects/runtime/session.ts:43:29)
          at World.LogInUser (/drone/src/webTestRunner/tests/e2e/cucumber/steps/ui/session.ts:20:25)
```
```feature
Feature: spaces public link # tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature:1

  Scenario: public link for space # tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature:3
    Given "Admin" creates following users
      │ id    │
      │ Alice │
      │ Brian │
      │ Carol │
      │ Marie │
    And "Admin" assigns following roles to the users using API
      │ id    │ role        │
      │ Alice │ Space Admin │
    And "Alice" creates the following project space using API
      │ name │ id     │
      │ team │ team.1 │
    When "Alice" logs in
    ✖ failed
      page.goto: Timeout 30000ms exceeded.
      =========================== logs ===========================
      navigating to "https://ocis-server:9200/", waiting until "load"
      ============================================================
          at World.LogInUser (/drone/src/webTestRunner/tests/e2e/cucumber/steps/ui/session.ts:19:16)
    And "Alice" navigates to the projects space page
    - skipped
```
</details>

cc @individual-it

**Comment by SwikritiT** [comment] 2023-03-21 03:52
The login one should have been fixed by https://github.com/owncloud/web/pull/8631, I don't see those errors in web these days maybe the fix commit hasn't been bumped in ocis?

**Comment by ScharfViktor** [comment] 2023-03-22 11:44
2. need check that all DELETE requests are OKAY

https://drone.owncloud.com/owncloud/ocis/20666/66/10

`npx playwright show-trace https://cache.owncloud.com/public/owncloud/ocis/20666/tracing/user-group-assignments-can-be-handled-via-batch-actions-admin-2023-3-22-09-42-00.zip`

<img width="1366" alt="Screenshot 2023-03-22 at 12 44 08" src="https://user-images.githubusercontent.com/84779829/226894156-2d7161ac-6cf6-4313-b55b-f8d4ccdcfb3f.png">

```
Scenario: user group assignments can be handled via batch actions # tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature:45
    Given "Admin" creates following users
      │ id    │
      │ Alice │
      │ Brian │
      │ Carol │
    And "Admin" creates following groups using API
      │ id      │
      │ sales   │
      │ finance │
    When "Admin" logs in
    And "Admin" opens the "admin-settings" app
    And "Admin" navigates to the users management page
    And "Admin" adds the following users to the groups "sales department,finance department" using the batch actions
      │ user  │
      │ Alice │
      │ Brian │
      │ Carol │
    When "Admin" sets the following filter
      │ filter │ values                              │
      │ groups │ sales department,finance department │
    Then "Admin" should see the following users
      │ user  │
      │ Alice │
      │ Brian │
      │ Carol │
    And "Admin" removes the following users from the groups "sales department,finance department" using the batch actions
      │ user  │
      │ Alice │
      │ Brian │
    When "Admin" reloads the page
    Then "Admin" should see the following users
      │ user  │
      │ Carol │
    And "Admin" should not see the following users
      │ user  │
      │ Alice │
      │ Brian │
    ✖ failed
      Error: expect(received).not.toContain(expected) // indexOf

      Expected value: not "b24822a7-855c-4fac-8e84-7b16dd15096c"
      Received array:     [null, "b24822a7-855c-4fac-8e84-7b16dd15096c", "bdd56985-c5ea-49ef-860a-799ac2a7bd6c", null]
          at Proxy.<anonymous> (/drone/src/webTestRunner/node_modules/.pnpm/@playwright+test@1.29.1/node_modules/@playwright/test/lib/expect.js:130:37)
          at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/ui/adminSettings.ts:150:47)
    And "Admin" logs out
    - skipped
```

**Comment by ScharfViktor** [comment] 2023-03-22 12:21
3. `npx playwright show-trace https://cache.owncloud.c/public/owncloud/ocis/20666/tracing/multiple-spaces-can-be-managed-at-once-in-the-admin-settings-via-the-batch-actions-alice-2023-3-22-09-40-44.zip`

`const count = await result.count()` gets 7 items (expect 2) and fails when 




<img width="1127" alt="Screenshot 2023-03-22 at 13 17 46" src="https://user-images.githubusercontent.com/84779829/226902740-18f74897-eaa0-4f6a-92df-0bb22700dbcc.png">

<img width="330" alt="image" src="https://user-images.githubusercontent.com/84779829/226902662-926f3ee3-c280-4417-8b66-4e13d3ae3e3b.png">

**Comment by saw-jan** [comment] 2023-03-23 07:22
We also have some issues with element selectors as well as the race condition. I will push possible fixes for some tests.

**Comment by saw-jan** [comment] 2023-03-23 09:23
Test: `tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature:39`
Scenario: `Scenario: multiple spaces can be managed at once in the admin settings via the batch actions`
Error:
```bash
✖ Then "Alice" should not see the following spaces # tests/e2e/cucumber/steps/ui/adminSettings.ts:11
       | id     |
       | team.a |
       | team.b |
       | team.c |
       | team.d |
       locator.getAttribute: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('tr').nth(3)
       ============================================================
           at getDisplayedSpaces (/drone/src/webTestRunner/tests/e2e/support/objects/app-admin-settings/spaces/actions.ts:23:41)
           at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/ui/adminSettings.ts:14:24)
```

<details>

<summary>Full log</summary>

```bash
Scenario: multiple spaces can be managed at once in the admin settings via the batch actions (attempt 2) # tests/e2e/cucumber/features/smoke/admin-settings/spaces.ocis.feature:39
   ✔ Before # tests/e2e/cucumber/environment/index.ts:36
   ✔ Given "Admin" creates following users # tests/e2e/cucumber/steps/api.ts:10
       | id    |
       | Alice |
   ✔ And "Admin" assigns following roles to the users using API # tests/e2e/cucumber/steps/api.ts:24
       | id    | role        |
       | Alice | Space Admin |
   ✔ And "Alice" creates the following project spaces using API # tests/e2e/cucumber/steps/api.ts:125
       | name   | id     |
       | team A | team.a |
       | team B | team.b |
       | team C | team.c |
       | team D | team.d |
   ✔ When "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   ✔ And "Alice" opens the "admin-settings" app # tests/e2e/cucumber/steps/ui/application.ts:6
   ✔ And "Alice" navigates to the project spaces management page # tests/e2e/cucumber/steps/ui/adminSettings.ts:6
   ✔ And "Alice" disables the following spaces using the batch-actions # tests/e2e/cucumber/steps/ui/adminSettings.ts:72
       | id     |
       | team.a |
       | team.b |
       | team.c |
       | team.d |
   ✔ And "Alice" enables the following spaces using the batch-actions # tests/e2e/cucumber/steps/ui/adminSettings.ts:72
       | id     |
       | team.a |
       | team.b |
       | team.c |
       | team.d |
   ✔ And "Alice" updates quota of the following spaces to "50" using the batch-actions # tests/e2e/cucumber/steps/ui/adminSettings.ts:60
       | id     |
       | team.a |
       | team.b |
       | team.c |
       | team.d |
   ✔ And "Alice" disables the following spaces using the batch-actions # tests/e2e/cucumber/steps/ui/adminSettings.ts:72
       | id     |
       | team.a |
       | team.b |
       | team.c |
       | team.d |
   ✔ And "Alice" deletes the following spaces using the batch-actions # tests/e2e/cucumber/steps/ui/adminSettings.ts:72
       | id     |
       | team.a |
       | team.b |
       | team.c |
       | team.d |
   ✖ Then "Alice" should not see the following spaces # tests/e2e/cucumber/steps/ui/adminSettings.ts:11
       | id     |
       | team.a |
       | team.b |
       | team.c |
       | team.d |
       locator.getAttribute: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('tr').nth(3)
       ============================================================
           at getDisplayedSpaces (/drone/src/webTestRunner/tests/e2e/support/objects/app-admin-settings/spaces/actions.ts:23:41)
           at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/ui/adminSettings.ts:14:24)
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ After # tests/e2e/cucumber/environment/index.ts:83
```
</details>

**Comment by ScharfViktor** [comment] 2023-03-23 11:23
>    ✔ And "Alice" deletes the following spaces using the batch-actions # tests/e2e/cucumber/steps/ui/adminSettings.ts:72
>        | id     |
>        | team.a |
>        | team.b |
>        | team.c |
>        | team.d |

I think if we set waitForResponse for each deleting space next step will be work

>    ✖ Then "Alice" should not see the following spaces # tests/e2e/cucumber/steps/ui/adminSettings.ts:11
>        | id     |
>        | team.a |
>        | team.b |
>        | team.c |
>        | team.d |

**Comment by saw-jan** [comment] 2023-03-23 11:27
yeah, we do have `waitForResponse` but I think that checks only one space-id during batch action deletion.
I will look if we can somehow check for all the spaces. Thanks!

**Comment by ScharfViktor** [comment] 2023-03-23 11:38
![Screenshot 2023-03-23 at 11 15 46](https://user-images.githubusercontent.com/84779829/227192406-287bd4b3-aeec-4c27-b172-38f266b36105.png)

**Comment by ScharfViktor** [comment] 2023-03-23 11:39
<img width="619" alt="Clipboard - March 23, 2023 12_36 PM" src="https://user-images.githubusercontent.com/84779829/227192564-dbe26519-4e49-48c5-a4d8-1102253ea2b8.png">

**Comment by saw-jan** [comment] 2023-03-24 06:23
Test: `tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature:3`
Scenario: `Scenario: user login can be managed in the admin settings`
Error:
```bash
✖ Then "Alice" fails to log in # tests/e2e/cucumber/steps/ui/session.ts:34
       locator.fill: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('#oc-login-username')
       ============================================================
           at Ocis.login (/var/www/owncloud/web/tests/e2e/support/objects/runtime/session.ts:12:56)
           at Session.login (/var/www/owncloud/web/tests/e2e/support/objects/runtime/session.ts:43:29)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:39:25)
```

<details>

<summary>Full log</summary>

```bash
Scenario: user login can be managed in the admin settings (attempt 1, retried) # tests/e2e/cucumber/features/smoke/admin-settings/users.ocis.feature:3
   ✔ Before # tests/e2e/cucumber/environment/index.ts:36
   ✔ Given "Admin" creates following user using API # tests/e2e/cucumber/steps/api.ts:10
       | id    |
       | Alice |
   ✔ When "Admin" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   ✔ And "Admin" opens the "admin-settings" app # tests/e2e/cucumber/steps/ui/application.ts:6
   ✔ And "Admin" navigates to the users management page # tests/e2e/cucumber/steps/ui/adminSettings.ts:96
   ✔ And "Admin" forbids the login for the following user "Alice" using the sidebar panel # tests/e2e/cucumber/steps/ui/adminSettings.ts:101
   ✔ And "Admin" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   ✖ Then "Alice" fails to log in # tests/e2e/cucumber/steps/ui/session.ts:34
       locator.fill: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('#oc-login-username')
       ============================================================
           at Ocis.login (/var/www/owncloud/web/tests/e2e/support/objects/runtime/session.ts:12:56)
           at Session.login (/var/www/owncloud/web/tests/e2e/support/objects/runtime/session.ts:43:29)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:39:25)
   - When "Admin" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   - And "Admin" opens the "admin-settings" app # tests/e2e/cucumber/steps/ui/application.ts:6
   - And "Admin" navigates to the users management page # tests/e2e/cucumber/steps/ui/adminSettings.ts:96
   - And "Admin" allows the login for the following user "Alice" using the sidebar panel # tests/e2e/cucumber/steps/ui/adminSettings.ts:101
   - And "Admin" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   - Then "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ After # tests/e2e/cucumber/environment/index.ts:83
```
</details>

Speculated cause: 
Fix:

**Comment by saw-jan** [comment] 2023-03-24 06:25
Test: `tests/e2e/cucumber/features/smoke/tiles.feature:6`
Scenario: `Scenario: Users can navigate web via tiles`
Error:
```bash
✖ And "Alice" sees the resources displayed as tiles # tests/e2e/cucumber/steps/ui/resources.ts:174
       Error: expect(received).toBe(expected) // Object.is equality
       Expected: true
       Received: false
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/@playwright+test@1.29.1/node_modules/@playwright/test/lib/expect.js:130:37)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:178:35)
```

<details>

<summary>Full log</summary>

```bash
Scenario: Users can navigate web via tiles (attempt 1, retried) # tests/e2e/cucumber/features/smoke/tiles.feature:6
   ✔ Before # tests/e2e/cucumber/environment/index.ts:36
   ✔ Given "Admin" creates following user using API # tests/e2e/cucumber/steps/api.ts:10
       | id    |
       | Alice |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:6
   ✔ And "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:12
       | resource    | type   |
       | tile_folder | folder |
   ✔ And "Alice" switches to the tiles-view # tests/e2e/cucumber/steps/ui/resources.ts:169
   ✖ And "Alice" sees the resources displayed as tiles # tests/e2e/cucumber/steps/ui/resources.ts:174
       Error: expect(received).toBe(expected) // Object.is equality
       Expected: true
       Received: false
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/@playwright+test@1.29.1/node_modules/@playwright/test/lib/expect.js:130:37)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:178:35)
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ After # tests/e2e/cucumber/environment/index.ts:83
```
</details>

Speculated cause: 
Fix:

**Comment by SwikritiT** [comment] 2023-03-27 08:42
Test- tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature:3
Scenario: unstructured collection of testable space interactions, # 
```feature
    And "Alice" updates the space "team.1" image to "testavatar.jpeg"
    ✖ failed
      Error: function timed out, ensure the promise resolves within 60000 milliseconds
          at Timeout._onTimeout (/drone/src/webTestRunner/node_modules/.pnpm/@cucumber+cucumber@7.3.2/node_modules/@cucumber/cucumber/src/user_code_runner.ts:80:18)
          at listOnTimeout (node:internal/timers:559:17)
          at processTimers (node:internal/timers:502:7)
```
```feature
And "Alice" updates the space "team.1" name to "developer team"
    ✖ failed
      Error: function timed out, ensure the promise resolves within 60000 milliseconds
          at Timeout._onTimeout (/drone/src/webTestRunner/node_modules/.pnpm/@cucumber+cucumber@7.3.2/node_modules/@cucumber/cucumber/src/user_code_runner.ts:80:18)
          at listOnTimeout (node:internal/timers:559:17)
          at processTimers (node:internal/timers:502:7)
```
Build: https://drone.owncloud.com/owncloud/ocis/20850/87/9

This step also seems falky

**Comment by saw-jan** [comment] 2023-04-05 07:26
> Test- tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature:3 Scenario: unstructured collection of testable space interactions, # Error:
> 
> ```
>     And "Alice" updates the space "team.1" image to "testavatar.jpeg"
>     ✖ failed
>       Error: function timed out, ensure the promise resolves within 60000 milliseconds
>           at Timeout._onTimeout (/drone/src/webTestRunner/node_modules/.pnpm/@cucumber+cucumber@7.3.2/node_modules/@cucumber/cucumber/src/user_code_runner.ts:80:18)
>           at listOnTimeout (node:internal/timers:559:17)
>           at processTimers (node:internal/timers:502:7)
> ```
> 
> Full log
> Error:
> 
> ```
> And "Alice" updates the space "team.1" name to "developer team"
>     ✖ failed
>       Error: function timed out, ensure the promise resolves within 60000 milliseconds
>           at Timeout._onTimeout (/drone/src/webTestRunner/node_modules/.pnpm/@cucumber+cucumber@7.3.2/node_modules/@cucumber/cucumber/src/user_code_runner.ts:80:18)
>           at listOnTimeout (node:internal/timers:559:17)
>           at processTimers (node:internal/timers:502:7)
> ```
> 
> Full log
> Build: https://drone.owncloud.com/owncloud/ocis/20850/87/9
> 
> This step also seems falky Fix: @SwikritiT

Couldn't reproduce this one and haven't seen recently.
So I will close it here and we can create another issue if it reappears

**Closed by saw-jan** 2023-04-05 07:26 UTC
