### ISSUE TITLE
Feature to keep both new and existing file

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5418] opened 2021-06-30 05:52 UTC
### Steps to reproduce
1. user uploads file `sample.txt`
2. user again tries to upload same file  `sample.txt`

### Expected behaviour
dialog to keep both new and existing file like in `oC10`
![overwrite](https://user-images.githubusercontent.com/52366632/123908402-28a31e80-d997-11eb-8842-df2921afc088.png)

### Actual behaviour
Cann only create new version of existing file
![newversion](https://user-images.githubusercontent.com/52366632/123908489-4f615500-d997-11eb-98ee-828ab1e03160.png)

### Server configuration
**Operating system**:
**Web server:**
**Database:*
**PHP version:**
**ownCloud version:** (see ownCloud admin page)

**Comment by kulmann** [comment] 2021-06-30 07:42
Duplicate of https://github.com/owncloud/web/issues/5106 , closing here. Thanks for the screenshots, I'll add them to the original ticket.

**Closed by kulmann** 2021-06-30 07:42 UTC
Labels: Type:Discussion

**Comment by saw-jan** [comment] 2021-06-30 08:02
I didn't find that one so created the new one.
Thanks
