### ISSUE TITLE
Search field regression in 7.0.0-rc.5 

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#8180] opened 2023-01-03 23:56 UTC
### Expected behaviour
Like in 6.0.0 the search field has to have rounded corners and the search term has spacing from the left side

<img width="523" alt="image" src="https://user-images.githubusercontent.com/33026403/210460750-6914deb4-af05-4ed9-bf54-9e97ab83d599.png">

### Actual behaviour

<img width="531" alt="image" src="https://user-images.githubusercontent.com/33026403/210460772-945835f7-5f70-4582-8073-80057800e36d.png">

**Comment by dschmidt** [comment] 2023-01-04 00:07
Duplicate of https://github.com/owncloud/web/issues/8158

**Closed by dschmidt** 2023-01-04 00:07 UTC

**Comment by ChrisEdS** [comment] 2023-01-04 00:08
> Duplicate of #8158

What about the rounded corners?

**Comment by dschmidt** [comment] 2023-01-04 00:15
I assume it's the same issue, but can't verify right now

**Comment by dschmidt** [comment] 2023-01-04 00:24
Checked. Corners are rounded in vite, so it's just a production build issue as the linked issue states.
