### ISSUE TITLE
Investigate the `rename` related nightly failure

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6999] opened 2022-05-18 03:53 UTC
Build: https://drone.owncloud.com/owncloud/web/25679/57/15

<details>
<summary>webUIRenameFiles/renameFiles.feature:269</summary>

```
Scenario: User tries to rename a file that used to exist but does not anymore # features/webUIRenameFiles/renameFiles.feature:269
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (227ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has uploaded file "lorem.txt" to "lorem.txt" in the server
    And user "Alice" has uploaded file "data.zip" to "data.zip" in the server
    And user "Alice" has uploaded file "lorem-big.txt" to "lorem-big.txt" in the server
    Given user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 726 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 144 milliseconds.
√ Element <#files-view> was visible after 572 milliseconds.
    And the following files have been deleted by user "Alice" in the server
      │ name      │
      │ lorem.txt │
    When the user tries to rename file "lorem.txt" to "new-lorem.txt" using the webUI
   NoSuchElementError: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]>: 
   {"sessionId":"aac68bcab75b26057f9b36cf12cf6a95","status":0,"value":[]}
       at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:365:18)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:18)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:282:18)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:272:18)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:249:7)
       at Proxy.renameFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:88:7)
    ✖ failed
      AssertionError [ERR_ASSERTION]: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]>:
          at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:375:16)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:7)
          at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:282:7)
          at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:272:7)
          at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:249:7)
          at Proxy.renameFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:88:7)
    Then the error message with header 'Failed to rename "lorem.txt" to "new-lorem.txt"' should be displayed on the webUI
    - skipped
    When the user reloads the current page of the webUI
    - skipped
    Then file "lorem.txt" should not be listed on the webUI
    - skipped
    And file "new-lorem.txt" should not be listed on the webUI
    - skipped
    And as "Alice" file "lorem.txt" should not exist in the server
    - skipped
    And as "Alice" file "new-lorem.txt" should not exist in the server
    - skipped
saving screenshot of failed test
```
</details>

<details>
<summary>webUIRenameFolders/renameFolders.feature:151</summary>

```
Scenario: User tries to rename a folder that used to exist but does not anymore # features/webUIRenameFolders/renameFolders.feature:151
- Connecting to selenium on port 4444...

  Using: chrome (94.0.4606.61) on Linux platform.

ℹ Connected to selenium on port 4444 (274ms).
    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has created folder "simple-empty-folder" in the server
    And user "Alice" has uploaded file "lorem.txt" to "lorem.txt" in the server
    Given user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 749 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 202 milliseconds.
√ Element <#files-view> was visible after 683 milliseconds.
    And the following files have been deleted by user "Alice" in the server
      │ name          │
      │ simple-folder │
    When the user tries to rename folder "simple-folder" to "new-simple-folder" using the webUI
   NoSuchElementError: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]>: 
   {"sessionId":"0e5fe972e99bb90dcbcbb4ade2da8bda","status":0,"value":[]}
       at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:365:18)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:18)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:282:18)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:272:18)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:249:7)
       at Proxy.renameFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:88:7)
    ✖ failed
      AssertionError [ERR_ASSERTION]: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]>:
          at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:375:16)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:7)
          at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:282:7)
          at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:272:7)
          at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:249:7)
          at Proxy.renameFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:88:7)
    Then the error message with header 'Failed to rename "simple-folder" to "new-simple-folder"' should be displayed on the webUI
    - skipped
    When the user reloads the current page of the webUI
    - skipped
    Then folder "simple-folder" should not be listed on the webUI
    - skipped
    And folder "new-simple-folder" should not be listed on the webUI
    - skipped
    And as "Alice" folder "simple-folder" should not exist in the server
    - skipped
    And as "Alice" folder "new-simple-folder" should not exist in the server
    - skipped
saving screenshot of failed test
```
</details>

**Comment by saw-jan** [comment] 2022-05-18 05:00
failed on restarted build: https://drone.owncloud.com/owncloud/web/25680/56/15

**Comment by saw-jan** [comment] 2022-05-18 09:16
Could not reproduce the CI fail locally. Have no idea why the nightly failed.

**Comment by saw-jan** [comment] 2022-05-19 11:24
CI seems pretty stable. 100 runs passed (https://drone.owncloud.com/owncloud/web/25721/10/15)
Couldn't figure out why the nightly is failing.

**Comment by SwikritiT** [comment] 2022-05-20 04:32
the recent nightly build has also passed https://drone.owncloud.com/owncloud/web/25737. Haven't seen this test fail in other builds either. Maybe we can close it for now and re-open it if it arises again? Or we can keep it open for a few days and close it if the failure isn't seen.

**Comment by saw-jan** [comment] 2022-05-20 11:19
Let's see what the nightly on the weekends will be and then we can decide.

**Comment by saw-jan** [comment] 2022-05-23 03:29
Couldn't reproduce it and haven't seen it in recent nightlies.
Closing for now!

**Comment by saw-jan** [comment] 2022-05-27 07:10
This test failed again today https://drone.owncloud.com/owncloud/web/25887/56/15

**Comment by sushmita56** [comment] 2022-05-31 05:38
Tried to reproduce it locally but is not reproducible.

**Comment by saw-jan** [comment] 2022-05-31 05:44
> Tried to reproduce it locally but is not reproducible.

I will take a look from here.

**Comment by saw-jan** [comment] 2022-05-31 06:37
File `lorem.txt` is not in the files list.

![test-test_feature-L12](https://user-images.githubusercontent.com/52366632/171108057-eeeedb54-a6f5-4193-8998-f968e87dca13.png)

SR:

https://user-images.githubusercontent.com/52366632/171108167-978e7461-cb90-4ca4-8d74-2ba38faeb571.mp4

**Closed** 2022-05-31 12:50 UTC
Labels: QA:team
