### ISSUE TITLE
Project space have public links from the personal space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7268] opened 2022-07-12 12:31 UTC
ownCloud Web UI 5.7.0-rc.5:

Prerequisite: 
- create a folder with the file in your personal space
- create a public link to the folder

Steps: 
- create new project space
- go to the members

Actual: here we have a public link from personal space

https://user-images.githubusercontent.com/84779829/178489798-85034c95-2b2f-4092-baeb-756c358efe76.mov

**Comment by pascalwengerter** [comment] 2022-07-15 19:05
> Can confirm, this is critical and needs investigation

When investigating, I have started the recently released `beta.4`
- with the embedded `web` it brings and the problem does not arise
- with the current `web` master (aka close to `v5.7.0-rc.5`) and the problem shows up
which leads me to the conclusion that this is a frontend issue, most likely related to either the auth (or resharing?) refactorings

**Comment by pascalwengerter** [comment] 2022-07-15 19:21
> > Can confirm, this is critical and needs investigation
> 
> When investigating, I have started the recently released `beta.4`
> 
>     * with the embedded `web` it brings and the problem does not arise
> 
>     * with the current `web` master (aka close to `v5.7.0-rc.5`) and the problem shows up
>       which leads me to the conclusion that this is a frontend issue, most likely related to either the auth (or resharing?) refactorings

Checked out https://github.com/owncloud/web/commit/434a622b6d77d4c3040a973fd08535f0e2d97e7d (merge commit of the auth PR) and the issue is present there (resharing was merged a day later IIRC so it shouldn't be the culprint)

**Comment by pascalwengerter** [comment] 2022-07-15 19:56
> > > > Can confirm, this is critical and needs investigation
> > > 
> > > 
> > > When investigating, I have started the recently released `beta.4`
> > > ```
> > > * with the embedded `web` it brings and the problem does not arise
> > > 
> > > * with the current `web` master (aka close to `v5.7.0-rc.5`) and the problem shows up
> > >   which leads me to the conclusion that this is a frontend issue, most likely related to either the auth (or resharing?) refactorings
> > > ```
> > 
> > 
> > Checked out [434a622](https://github.com/owncloud/web/commit/434a622b6d77d4c3040a973fd08535f0e2d97e7d) (merge commit of the auth PR) and the issue is present there (resharing was merged a day later IIRC so it shouldn't be the culprint)
> 
> Also checked [94b0538](https://github.com/owncloud/web/commit/94b05386fbd4ec255bb59266d4952b02e1802e10) which was right before the auth PR got merged and it's fine there, so I guess #7072 caused the regression

Looks like `currentFolder.path` is an empty string in https://github.com/owncloud/web/blob/434a622b6d77d4c3040a973fd08535f0e2d97e7d/packages/web-app-files/src/services/folder/spaces/loaderProject.ts#L76 which leads to _all_ shares being fetched upon navigating into a project space?

**Closed** 2022-07-19 11:54 UTC
Labels: Type:Bug, Priority:p2-high
