### ISSUE TITLE
UX:  No option to share a folder when inside it

### ISSUE THREAD

**Issue by labkode** [owncloud/web#3919] opened 2020-08-06 06:54 UTC

**Comment by PVince81** [comment] 2020-08-06 07:07
related https://github.com/owncloud/phoenix/issues/2061

**Comment by pascalwengerter** [comment] 2021-05-17 13:49
@tbsbdr can we discuss this in the design initiative?

**Comment by kulmann** [comment] 2021-05-17 13:55
We already have a concept for this, and a story, but somehow it doesn't appear in github. Issue in Jira is WEB-29. The idea is to give the option to the user to open the right sidebar without having a file/folder selected. With that sharing becomes available for the current folder. As of now the Issue is planned for the next sprint, to be released end of June.

**Comment by kulmann** [comment] 2021-06-11 21:19
Will be solved when https://github.com/owncloud/web/issues/5165 is implemented. Still planned for end of June.

**Comment by kulmann** [comment] 2021-08-18 08:50
Will be fixed when https://github.com/owncloud/web/pull/5678 is merged

**Closed** 2021-08-19 14:33 UTC
Labels: Category:Enhancement, Type:Design, Early-Adopter:CERN, p3-medium
