### ISSUE TITLE
Project Space is not visible for user who have got access

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#7288] opened 2022-07-19 05:13 UTC
### Steps to reproduce
1. Create user `User1` and `User2`
2. As user `admin`, Grant `spaceAdmin` role to `User1`
3. Login as `User1`
4. Navigate to `Spaces` from sidebar
5. Create new project space `team`
6. Add `User2` to space `team` with `Editor` role
7. Login as `User2`
8. Navigate to `Spaces` from sidebar

### Expected behaviour
project space `team` must be visible
![seen_team](https://user-images.githubusercontent.com/8559121/179499858-e68dc59d-c7cf-4be2-ac4c-6b1eed376ce1.png)

### Actual behaviour
From this video, we can see that the space `team` is seen for a while and it gets disappear. 
[721a2c1f440d26ad7f13346d0d5ae94e.webm](https://user-images.githubusercontent.com/8559121/179495351-1d9b7796-a8bd-4bbb-8c9d-ffc288b5cdda.webm)

![notseen-team](https://user-images.githubusercontent.com/8559121/179500060-9119852d-3aec-45b2-a46a-742223d324c4.png)
But after the space page reload we can see space `team`

### Extra Findings
When the user logs in these requests are created:
![image](https://user-images.githubusercontent.com/8559121/179668684-8fb57eb7-c3a0-4ab8-879a-07ef71face4e.png)

When the user navigates to Spaces from the sidebar this request is created:
![image](https://user-images.githubusercontent.com/8559121/179669048-102a3f1e-7a08-4b1b-9c2a-1148d94c4035.png)

But for the failure case, the order of requests is not sequentially done:
![unsuccessful_tst](https://user-images.githubusercontent.com/8559121/179664260-dbb75aaf-336d-4957-bffd-fd870dc082db.jpg)

The request `200 GET drives?%24top=0&%24skip=0&%24orderby=name+asc&%24filter=driveType+eq+project` is created before the request `207 PROPFIND 1284d238-aa92-42ce-bdc4-0b0000009157%24fab37c7a-8dbd-4365-b0b9-32d6b860868a` 

And for the success case, the order of requests is sequentially done:
![successful_test](https://user-images.githubusercontent.com/8559121/179664390-6027e8a9-5677-4285-a115-4e3ba98659e7.jpg)

### Environment general
**Operating system**: Ubuntu 20.04 LTS

**Backend (ownCloud Core or Infinite Scale)**: OCIS

### Environment ownCloud Infinite Scale
**Version:**
Latest Master

**Comment by grgprarup** [comment] 2022-07-19 05:17
Nightly failure of this issue: https://drone.owncloud.com/owncloud/web/26735/10/12

**Comment by kulmann** [comment] 2022-07-21 08:22
@grgprarup so far I'm unable to reproduce the issue. Neither with current ocis master (a538b985977ccdb0eb838da5482f3cc2fea37114) nor with the commit id of the nightly run that you referenced (d54712b9017f7ac23baddbf52e46678c95493e44).
Do you have additional details on the issue?
- when you try to reproduce it yourself, does it have the shown behaviour reliably? Or only from time to time?
- which browser did you use?
- any additional setup than just `make clean generate build` in the `ocis` dir and then running `./bin/ocis server`?
- did you run the steps on a fresh instance (~/.ocis folder deleted) or with data from older ocis versions?

**Comment by JanAckermann** [comment] 2022-07-22 06:26
Agree, not able to reproduce

**Comment by grgprarup** [comment] 2022-07-26 05:22
> @grgprarup so far I'm unable to reproduce the issue. Neither with current ocis master (`a538b985977ccdb0eb838da5482f3cc2fea37114`) nor with the commit id of the nightly run that you referenced (`d54712b9017f7ac23baddbf52e46678c95493e44`). Do you have additional details on the issue?
> 
> * when you try to reproduce it yourself, does it have the shown behaviour reliably? Or only from time to time?
> * which browser did you use?
> * any additional setup than just `make clean generate build` in the `ocis` dir and then running `./bin/ocis server`?
> * did you run the steps on a fresh instance (~/.ocis folder deleted) or with data from older ocis versions?

@kulmann This issue cannot be reproduced manually, the issue was seen when running the e2e test for feature file `tests/e2e/cucumber/features/integrations/spaces/participantManagement.ocis.feature`. 
The behavior was seen intermittently. Only minimal setup for web+ocis was done, and no additional setup.

**Comment by phil-davis** [comment] 2022-08-23 06:28
Also see an example in issue #7507

**Comment by phil-davis** [comment] 2022-08-23 06:51
https://drone.owncloud.com/owncloud/ocis/14799/75/9 - happened again

**Comment by grgprarup** [comment] 2022-08-30 07:49
Failing in recent PRs: 
https://drone.owncloud.com/owncloud/web/27900/12/12
https://drone.owncloud.com/owncloud/web/27899/12/12
https://drone.owncloud.com/owncloud/web/27898/10/12

**Comment by grgprarup** [comment] 2022-09-05 04:59
Failed on Today's Nightly: https://drone.owncloud.com/owncloud/web/28059/10/12

**Comment by ScharfViktor** [comment] 2022-09-05 15:49
and https://drone.owncloud.com/owncloud/ocis/15208/76/9

**Comment by phil-davis** [comment] 2022-09-12 04:19
and https://drone.owncloud.com/owncloud/ocis/15368/76/9
```
1) Scenario: public link for space (attempt 1, retried) # tests/e2e/cucumber/features/integrations/spaces/publicLink.ocis.feature:3
   ✔ Before # tests/e2e/cucumber/environment/index.ts:45
   ✔ Given "Admin" creates following users # tests/e2e/cucumber/steps/api.ts:6
       | id    |
       | Alice |
       | Brian |
       | Carol |
       | Marie |
   ✔ And "Admin" assigns following roles to the users # tests/e2e/cucumber/steps/api.ts:24
       | id    | role       |
       | Alice | SpaceAdmin |
   ✔ When "Alice" logs in # tests/e2e/cucumber/steps/runtime/session.ts:24
   ✔ And "Alice" navigates to the projects space page # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:6
   ✔ And "Alice" creates the following project spaces # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:15
       | name | id     |
       | team | team.1 |
   ✔ And "Alice" navigates to the project space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:27
   ✔ And "Alice" creates a public link for the space using the sidebar panel # tests/e2e/cucumber/steps/app-files/link.ts:18
   ✔ And "Alice" renames the most recently created public link of space to "spaceLink" # tests/e2e/cucumber/steps/app-files/link.ts:37
   ✔ And "Alice" creates the following resources # tests/e2e/cucumber/steps/app-files/resource.ts:8
       | resource    | type   |
       | spaceFolder | folder |
   ✔ And "Alice" creates a public link for the resource "spaceFolder" using the sidebar panel # tests/e2e/cucumber/steps/app-files/link.ts:6
   ✔ And "Alice" renames the most recently created public link of resource "spaceFolder" to "folderLink" # tests/e2e/cucumber/steps/app-files/link.ts:27
   ✔ And "Alice" adds following users to the project space # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:75
       | user  | role    |
       | Brian | editor  |
       | Carol | viewer  |
       | Marie | manager |
   ✔ And "Alice" logs out # tests/e2e/cucumber/steps/runtime/session.ts:37
   ✔ When "Brian" logs in # tests/e2e/cucumber/steps/runtime/session.ts:24
   ✔ And "Brian" navigates to the projects space page # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:6
   ✔ And "Brian" navigates to the project space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:27
   ✔ Then public link named "spaceLink" should be visible to "Brian" # tests/e2e/cucumber/steps/app-files/link.ts:102
   ✔ But "Brian" should not be able to edit the public link named "spaceLink" # tests/e2e/cucumber/steps/app-files/link.ts:122
   ✔ And "Brian" logs out # tests/e2e/cucumber/steps/runtime/session.ts:37
   ✔ When "Marie" logs in # tests/e2e/cucumber/steps/runtime/session.ts:24
   ✔ And "Marie" navigates to the projects space page # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:6
   ✔ And "Marie" navigates to the project space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:27
   ✔ And "Marie" edits the public link named "spaceLink" of the space changing role to "editor" # tests/e2e/cucumber/steps/app-files/link.ts:137
   ✔ And "Marie" edits the public link named "folderLink" of resource "spaceFolder" changing role to "editor" # tests/e2e/cucumber/steps/app-files/link.ts:77
   ✔ And "Marie" logs out # tests/e2e/cucumber/steps/runtime/session.ts:37
   ✔ When "Carol" logs in # tests/e2e/cucumber/steps/runtime/session.ts:24
   ✔ And "Carol" navigates to the projects space page # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:6
   ✖ And "Carol" navigates to the project space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:27
       locator.click: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for selector "[data-space-id="1284d238-aa92-42ce-bdc4-0b0000009157$b8af85fd-c783-4c9a-a87a-4626af120dda"]"
         selector resolved to visible <div data-v-7756294b="" class="spaces-list-card oc-ca…>…</div>
       attempting click action
         waiting for element to be visible, enabled and stable
       element was detached from the DOM, retrying
       waiting for selector "[data-space-id="1284d238-aa92-42ce-bdc4-0b0000009157$b8af85fd-c783-4c9a-a87a-4626af120dda"]"
       ============================================================
           at openSpace (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/spaces/actions.ts:65:56)
           at Spaces.open (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/spaces/index.ts:51:20)
           at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:33:24)
   - And public link named "spaceLink" should be visible to "Carol" # tests/e2e/cucumber/steps/app-files/link.ts:102
   - But "Carol" should not be able to edit the public link named "spaceLink" # tests/e2e/cucumber/steps/app-files/link.ts:122
   - And public link named "folderLink" of the resource "spaceFolder" should be visible to "Carol" # tests/e2e/cucumber/steps/app-files/link.ts:112
   - And "Carol" logs out # tests/e2e/cucumber/steps/runtime/session.ts:37
   ✔ After # tests/e2e/cucumber/environment/index.ts:98
```

**Comment by amrita-shrestha** [comment] 2022-09-16 04:17
re-occured: https://drone.owncloud.com/owncloud/web/28369/10/12

**Comment by JammingBen** [comment] 2023-04-18 10:14
Closing here as no one is able to reproduce the issue and apparently it doesn't occur anymore. We changed quite a few things when loading spaces, so it could very well be that this issue has been fixed meanwhile. Feel free to re-open if it pops up again!

**Closed by JammingBen** 2023-04-18 10:14 UTC
Labels: Type:Bug, Priority:p3-medium
