### ISSUE TITLE
Search by shares jail works incorrect

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7212] opened 2022-06-22 11:24 UTC
ocis: Infinite Scale 2.0.0-beta.4

Steps: 

- admin creates folder "f1" and shares to marie
- marie acceptes incomming folder and tries to find "f1" in search line

Actual: folder was found, but with the wrong name. After clicking on the folder, you go to your personal space at home and there is nothing there

![Screenshot 2022-06-22 at 13 14 44](https://user-images.githubusercontent.com/84779829/175017431-cc22564d-f54a-49e2-a395-734a8ebc392a.png)

**Comment by ScharfViktor** [comment] 2022-07-15 10:41
update: The search does not return search results for share jail. Now it backend problem: https://github.com/owncloud/ocis/issues/4210. 
After fixing maybe it will be actual

**Comment by ScharfViktor** [comment] 2022-07-19 08:17
They may be related: https://github.com/owncloud/web/issues/7292

**Comment by ScharfViktor** [comment] 2022-08-02 14:22
> update: The search does not return search results for share jail. Now it backend problem: [owncloud/ocis#4210](https://github.com/owncloud/ocis/issues/4210). After fixing maybe it will be actual

Re-test with Web UI 5.7.0-rc.7
Search returns result, but works incorrect as in bugs description
![Screenshot 2022-08-02 at 16 20 19](https://user-images.githubusercontent.com/84779829/182397964-a98a8cf4-3155-4e4e-98d7-da6842c81a2e.png)

**Comment by JanAckermann** [comment] 2022-08-10 09:45
Duplicate of https://github.com/owncloud/web/issues/7043, closing

**Closed by JanAckermann** 2022-08-10 09:45 UTC
Labels: Type:Bug, Priority:p3-medium
