### ISSUE TITLE
Broken shared with me/others views

### ISSUE THREAD

**Issue by diocas** [owncloud/web#8351] opened 2023-02-02 08:56 UTC
With the latest "space-ification" of the shares, the shared with me view broke for single files shares (as compared to some months old version).
As a reminder, our sharing behaviour is a little different than the default (but you support that), in the sense that opening a shared folder redirects the user back to the "all files" view (takes the file target option).
What is happening, is that opening a single file share, opens the file app in the wrong path, i.e:

`index.html#/draw-io/share/europe%20map.drawio/eos/user/d/diocas/europe%20map.drawio`
 instead of 
`index.html#/draw-io/personal/dalvesde/eos/user/d/diocas/europe%20map.drawio`

---

At the same time, the shared with others is also broken, as its entries try to open `index.html#/f/eoshome-d!42369307` instead of using the the target as well.

---

And in the shared publicly, I see the same as above, when clicking in folders, and `index.html#/f/[object%20Object]` when clicking in the parent folder.

**Comment by tbsbdr** [comment] 2023-06-12 12:35
realtes to https://github.com/owncloud/web/pull/9159/commits/6b774f2dfad7f8097b80539db30cfa27a355d299

**Comment by dschmidt** [comment] 2023-10-31 15:44
basically a duplicate of #9308

**Closed by dschmidt** 2023-10-31 15:44 UTC
Labels: Type:Bug, Early-Adopter:CERN
