### ISSUE TITLE
Make Directly Shared with People icon appears consistently

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5086] opened 2021-05-07 06:04 UTC
The Directly Shared with People icon on the file list view is only shown right after sharing, if you refresh the view or move inside the directory and back with the breadcrumbs, it disappears

**Comment by pascalwengerter** [comment] 2021-05-17 16:27
Couldn't reproduce, @labkode could you provide me with a step-for-step guide on how you achieved it so I can solve it? :)

**Comment by diocas** [comment] 2021-05-21 07:42
I'm closing this ticket for now as it seems an issue with our deployment. I'll re-open if we find otherwise.

**Closed by diocas** 2021-05-21 07:42 UTC
Labels: Early-Adopter:CERN, p3-medium

**Comment by kulmann** [comment] 2021-05-21 07:48
@pascalwengerter  was in fact able to reproduce it for the `link` share indicator on the root level. That one is only appearing when you create a public link if I remember correctly. Only valid for the root level though. On with oc10 it works, with ocis/reva it doesn't. In subfolders it works correctly.

**Comment by diocas** [comment] 2021-05-21 08:45
Then it might be a ocis issue?

**Comment by kulmann** [comment] 2021-05-21 08:48
> Then it might be an ocis issue?

Asked @C0rby, apparently it's a reva issue. According to him it would need quite some refactoring in reva to make it possible to have properly working link share information in the root level. Don't know the technical details though.

**Comment by kulmann** [comment] 2021-05-21 08:48
@C0rby could you take care of opening a reva issue with the details?
