### ISSUE TITLE
Release 4.5.0

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6017] opened 2021-11-11 11:49 UTC
## PRs to merge
- [x] #5956
- [x] #5970
- [x] #5996
- [x] #6020 (since @fschade pulled some last-minute magic)

## Release checklist
- [x] pin release issue @pascalwengerter 
- [x] prepare release rc: @pascalwengerter
  - [x] create a branch `release-4.5.0` @pascalwengerter
  - [x] update the version in `packages/web-integration-oc10/appinfo/info.xml` @pascalwengerter
  - [x] update the version in `package.json` @pascalwengerter
  - [x] update the version in `sonar-project.properties` @pascalwengerter 
  - [x] move changelog/unreleased/* to changelog/VERSION_YYYY-MM-DD @pascalwengerter
  - [x] update the ocis commit id in `.drone.env` to the most recent one from ocis master (i.e. let the web UI tests run on most recent ocis master) @pascalwengerter
  - [x]  commit, push and create **draft** PR for this branch @pascalwengerter
- [x] create pre release tag `v4.5.0-rc1` from the release branch @pascalwengerter 
- [x] smoke test 
  - [x] against oCIS @ScharfViktor 
  - [x] against oc10 standalone @pascalwengerter 
  - [x] against oc10 as app installation @kulmann 
  - [ ] against oCIS wopi example / app provider
- [x] if needed, fix issues or write down known issues 
- [x] update `YYYY-MM-DD` to current date in `changelog/VERSION_YYYY-MM-DD`
- [x] Make sure translations are up to date
- repeat above steps if a new rc is needed
- [x] Run translations sync job once again
- [ ] go to the releases section and click `Draft a new Release`. Use `v4.5.0` as a tag (the v prefix is important) and `4.5.0` as name and publish it
- [ ] ping in internal #btr channel to create a signed release and ask them to upload it to a) the github release page, b) marketplace.owncloud.com, c) portal.owncloud.com, d) customer.owncloud.com
- [ ] merge release branch https://github.com/owncloud/web/pull/6032 back to master (CI must be green)

**Comment by pascalwengerter** [comment] 2021-11-16 12:17
## Smoke test standalone against oc10

- ❌ as admin - upload 20.000 files in 7 folders to home (Firefox on Ubuntu)
    - upload via `New files` button just completely freezes the tab and doesn't even start uploading according to backend logs
    - upload via `Dropzone` takes forever, has all CPUs at 100% and eventually doesn't upload anything anymore according to backend logs
- ✔️ as admin - share the folder as viewer
- ✔️ as alice - share is already accepted. declining and accepting again works as expected (buttons in shared with me table, batch action, right sidebar)
- ✔️ as alice - try do delete file from shared folder
        - individual delete action not visible, good
        - batch delete action not visible, good
        - context menu action not visible, good
- ✔️ as alice - try to add file
        - not possible (which is expected) but drag & drop doesnt work, which is acceptable
- ✔️ as alice - copy 100 files from share to home
    move from shared folder makes browser lag alot sometimes freeze
- ✔️ as admin - add new file to share
- ✔️ as alice - receive new file in existing share
- ✔️ as admin - unshare folder from shared with others 
- ✔️ as alice - try to revisit old share
	- shows `resource not found` upon page reload, good
	- going back to `All files` or `Shared with me` doesn't list the share anymore, good
- ✔️ as admin - share folder with alice again, but as editor
- ✔️ as alice - rename file
	- via right sidebar, works, good
	- via context menu, works, good
- ✔️ as admin - add file
- ✔️ as alice - delete file
	- via right sidebar, works, good
	- via context menu, works, good

- ✔️ as alice - create public link on any folder
- ✔️ as alice delete file and recover it
- ✔️ as alice create version of textfile
- ✔️ as alice view version history of text file
- ✔️ as alice download newest version of text file
- ✔️ download older version of text file
- ✔️ restore older version of text file
	- no visible feedback about the success
	- preview is updated

- ✔️ as alice - upload avatar in classic UI
	- login as admin, having a share with alice
	- `shared with others` page loads and shows avatars

- ✔️ as alice, move a file into subfolder via drag and drop
- ✔️ as alice, navigate into a folder, open right sidebar without selection, share current folder with admin

**Comment by ScharfViktor** [comment] 2021-11-16 14:29
#  SmokeTest  against ocis
branch: v4.5.0-rc1

### Case 1: admin share folder(with file) to marie:

Admin:
- [ ]  upload big file 30gb - backend error: `507 {"level":"error","service":"storage","pkg":"rgrpc","error":"error: insufficient storage: quota exceeded","time":"2021-11-16T13:24:25Z","caller":"/go/pkg/mod/github.com/cs3org/reva@v1.12.0/internal/grpc/services/storageprovider/storageprovider.go:353","message":"insufficient storage"}
ocis_1      | {"level":"error","service":"storage","pkg":"rhttp","host":"127.0.0.1","method":"PUT","uri":"/remote.php/webdav/temp_30GB_file","url":"/remote.php/webdav/temp_30GB_file","proto":"HTTP/1.1","status":507,"size":0,"start":"16/Nov/2021:13:24:25 +0000","end":"16/Nov/2021:13:24:25 +0000","time_ns":4386500,"time":"2021-11-16T13:24:25Z","message":"http"}`
- [ ]  upload big file 10gb - very slow
- [x] upload folder with 848 files. 
- [x] Check pagination, count items per page. 
- [x] upload folder(drag folder) "folder_to_share" with file.pdf
- [x] share folder "folder_to_share" to marie with edit right

Marie:
- [x] accept "folder_to_share"
- [x] rename "folder_to_share" (?admin don't see)
- [x] upload new file "file.txt" to "folder_to_share" (admin see new file)
- [x] rename file.pdf (use rigth click) (admin see that file changed name)
- [x] try to move "folder_to_share" to "/" (400)
- [x] copy "folder_to_share" to "/"

Admin:
- [x] add new file.jpeg to "folder_to_share" (marie can see file without access)
- [x] move file.pdf to "/" (marie can not see file.pdf)
- [x] add new "file.txt" create new version. (marie can see new version)

Marie:
- [ ] can download both versions (!error 501)
- [x] restore old version

Admin:
- [x] change share "folder_to_share" from "edit" to "viewer" (marie cannot rename/move/delete/download file in folder and cannot create new document in the folder)

Marie:
- [x] decline folder (but folder exist in Shares - bug) - existing bug

Admin:
- [x] delete folder "folder_to_share" (marie: folder Shares empty)

## Case 2: admin share file to marie:

Admin:
- [x] upload file.jpeg
- [x] share file.jpeg to marie with rigth viewer (use main menu. find marie by email marie@example.org)

Marie:
- [x] accept file (marie can open/download/copy file but cannot delete/move/rename)
- [x] copy file to "/"
- [x] open file in Mediaviewer
- [x] download file

Admin:
- [x] change share "file.jpeg" from "viewer" to "edit"(marie can open/download/copy/rename file)

Marie:
- [x] rename file (admin don't see)

Admin:
- [x] unshare "file.jpeg" (marie cannot see "file.jpeg" in Shares/Shared for me but see the copied file)

## Case 3: admin create public links to folder

Admin:
- [x] create folder "for upload"
- [x] add link with name "to_upload" with role "Uploader" with pass and expiration date
- [x] open link (can only upload)
- [x] upload file (admin can see new file)
- [x] refresh page(page is empty)
- [x] change share "for upload" from "Uploader" to "edit" 
- [x] open old link (it work as upload)
- [x] open new link (can open/download/copy/rename/move files)
- [x] admin add new file to "for upload"
- [x] refresh link (file exist)
- [x] admin change pass (refresh link)

## Case 4: admin create link to file

Admin:
- [x] create file png
- [x] add link with main menu
- [ ] open link(can open, download, see) in the incognito tab
![image](https://user-images.githubusercontent.com/84779829/141999782-871daf52-313e-4c15-8aa9-5f2375afca25.png)

- [x] change link, add pass
- [x] refresh page (input pass)
- [x] delete link
- [x] refresh page (resource not found)
- [x] delete file
- [x] restore
- [x] delete
- [x] Empty trash

## Case 5: create new user:

Admin:
- [x] create new account "tom"

Tom:
- [x] go to account
- [x] change language

Admin:
- [x] block user (Login Error access denied)
- [x] delete user (Logon failed)
- [x] logout

**Comment by kulmann** [comment] 2021-11-16 14:36
## Smoke test rc1 against oc10 app

- :heavy_check_mark: as gunter - upload arch/mips folder from linux kernel (1945 files)
	- progress bar is not sticky
	- expanding the upload progress section slows down browser & upload time significantly
- :heavy_check_mark: as gunter - share the folder to alice as viewer
        - sharing is not possible before the upload finished (user invite field doesn't stay focussed) 
- :heavy_check_mark: as alice - share is already accepted. declining and accepting again works as expected (buttons in shared with me table, batch action, right sidebar)
        - ❌ as alice, selecting an accepted share, right-click-declining it will not remove it from the selection, leading to weird batch action buttons being displayed
- :heavy_check_mark: as alice - try do delete file from shared folder
        - individual delete action not visible, good
        - batch delete action not visible, good
        - context menu action not visible, good
- :heavy_check_mark: as alice - try to add file
        - not possible (which is expected) but drag & drop upload didn't handle it. opened file in new tab instead.
- ❌ as alice - copy 16 folders from share to home
	- no visible feedback that it's in progress
	- UI still weirdly usable, ended up in an active upload drop zone. Needed a page reload to be usable again.
	- folder listing after copy shows `?` as folder size on some of the copied folders.
- :heavy_check_mark: as gunter - add new file to share
- :heavy_check_mark: as alice - receive new file in existing share
- :heavy_check_mark: as gunter - unshare folder from shared with others 
- :heavy_check_mark: as alice - try to revisit old share
	- shows `resource not found` upon page reload, good
	- going back to `All files` or `Shared with me` doesn't list the share anymore, good
- :heavy_check_mark: as gunter - share folder with alice again, but as editor
- :heavy_check_mark: as alice - rename file
	- via right sidebar, works, good
	- via context menu, works, good
- :heavy_check_mark: as gunter - add file
- :heavy_check_mark: as alice - delete file
	- via right sidebar, works, good
	- via context menu, works, good
	- via batch action, works, good
- :heavy_check_mark: as alice - create public link on any folder
- :heavy_check_mark: as alice delete file and recover it
- :heavy_check_mark: as alice create version of textfile
- :heavy_check_mark: as alice view version history of text file
- ❌ as alice download newest version of text file
        - download as default action in file list (triggered on left click on a file) doesn't work (see remarks below)
- :heavy_check_mark: download older version of text file
- :heavy_check_mark: restore older version of text file
	- no visible feedback about the success
	- preview is not updated

- :heavy_check_mark: as alice - upload avatar in classic UI
	- see own avatar in top bar (far right) 
	- login as gunter, having a share with alice
		- `shared with others` page loads and shows avatars

- :heavy_check_mark: as alice, move a file into subfolder via drag and drop
- :heavy_check_mark: as alice, move multiple files & folders into subfolder via drag and drop
- :heavy_check_mark: as alice, navigate into a folder, open right sidebar without selection, share current folder with gunter

Remarks about smoke testing findings from previous release:
- FIXED :heavy_check_mark: mouse drop event doesn't trigger the upload dropzone anymore. Instead the dropped file opens in a new tab and the web ui shows a `successfully moved 0 items` message (unchanged, will be fixed in next release). https://github.com/owncloud/web/issues/5808
- FIXED :heavy_check_mark: coming back from mediaviewer doesn't highlight the selected file anymore in the files list (unchanged)

Findings from smoke testing:
- selecting an accepted share, right-click-declining it will not remove it from the selection, leading to weird batch action buttons being still displayed. This is not a regression of this release, was broken before. But it's an easy fix and should be included.
- download as default action (triggered on left click on a file) doesn't work, because the `.handler` is called on an array instead of a single action. This is a regression of this release. Easy fix, should be included.

**Closed** 2021-11-16 16:33 UTC
Labels: Interaction:Minor-Release
