### ISSUE TITLE
Optimize tiles view

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10040] opened 2023-11-22 15:36 UTC
## Description

The tiles view is an eyecatcher in every demo situation; still there is a visual flaw: On many screens quite big whitespace shows up on the right:
![screenshot_002003](https://github.com/owncloud/web/assets/26610733/af558b50-b848-4d90-bb4d-ae888775c73e)

## Steps to reproduce
1. create 10+ resources, switch to tiles view
2. resize the browser window until
3. whitespace shows up on the right

## Expected behavior
- regardless of the browser size, there should no extra whitespace show up on the right
- See video from box attached how the expected behaviour is

![screenshot_002004](https://github.com/owncloud/web/assets/26610733/4d195752-aadd-439a-8cb7-eb9169bb3ac1)

https://github.com/owncloud/web/assets/26610733/b69a39e7-cbaf-4b1e-8430-d5bfc19eba7b

## Actual behavior
- whitespace shows up on the right

**Comment by lookacat** [comment] 2023-11-30 12:43
I think the problem is that we need to resize the tiles in that case in order to fit on the screen, let me take a look

**Comment by JammingBen** [comment] 2023-12-20 14:02
Fixed via https://github.com/owncloud/web/pull/10118

**Closed by JammingBen** 2023-12-20 14:02 UTC
Labels: Category:Enhancement, Priority:p3-medium
