### ISSUE TITLE
[spaces] Expiration date on group members missing

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8754] opened 2023-03-30 10:32 UTC
### Steps to reproduce
1. Go to files -> spaces
2. Right click on space -> members
3. Invite group as member
4. Set expiration date
5. Click "Add"
6. Open context menu of added group

### Expected behaviour
As used from invited persons, the set expiration date is deletable and editable

### Actual behaviour
The calendar icon is displayed when an expiration date is set when adding the group as member. But the expiration date is not editable or deletable. 

![grafik](https://user-images.githubusercontent.com/16665512/228809164-79e9093a-009a-4861-91f0-59d7100ffdf7.png)

Addition: It is also not possible to add an expiration date to already added groups (possible for persons)

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works/

**Comment by JammingBen** [comment] 2023-03-31 10:45
Closing as duplicate of https://github.com/owncloud/web/issues/8419.

**Closed by JammingBen** 2023-03-31 10:45 UTC
Labels: Type:Bug
