### ISSUE TITLE
Files table header overlapping the first file item

### ISSUE THREAD

**Issue by hosy** [owncloud/web#4596] opened 2021-01-08 14:36 UTC
Table header in the file list is misaligned and overlapping the first file list item.

### Steps to reproduce
1. Open the new web UI
2. Have a look at the table header

### Expected behaviour
Table header is above the first file item cell

### Actual behaviour
Table header is overlapping the first cell item

<img width="1366" alt="Bildschirmfoto 2021-01-08 um 15 27 58" src="https://user-images.githubusercontent.com/736109/104027026-19e96500-51c7-11eb-8005-014e77dc2d42.png">

### Server configuration
**ownCloud version:** (see ownCloud admin page)
10.6.0

**Where did you install ownCloud from:**
Docker

**Client:**
Safari/Mac Version 14.0.2

**Comment by pascalwengerter** [comment] 2021-06-15 12:38
Can't reproduce on current `master`, closing as fixed

**Closed by pascalwengerter** 2021-06-15 12:38 UTC
