### ISSUE TITLE
right sidebar stays empty when navigating from a details view to "All Files"

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#5742] opened 2021-08-27 07:42 UTC
### Steps to reproduce
1. open the right sidebar for any item
2. click on "People" (or any other details item like Actions or Links)
3. click on "All files"

### Expected behaviour
right sidebar should show "Select a file or folder to view details."

### Actual behaviour
right sidebar is blank

**Comment by pascalwengerter** [comment] 2021-09-30 12:39
Can't reproduce on current master, closing for now

**Closed by pascalwengerter** 2021-09-30 12:39 UTC
Labels: Type:Bug, Web-Fastlane, bug

**Comment by kulmann** [comment] 2021-09-30 12:43
Was solved in https://github.com/owncloud/web/pull/5793
