### ISSUE TITLE
WEB interface not working with Only Office and custom Theme

### ISSUE THREAD

**Issue by gpapaiko** [owncloud/web#5114] opened 2021-05-18 03:49 UTC
Hi,

I have just enable the new WEB interface as per the instructions and at first glance it looks great.
BUT I have come across some issues:

1.  There are no potion to create new documents with Only Office. I have Only office installed and working, and in the classical mode everything is working I can create and edit documents in Only Office with out any issues.
2. I use a app call Draw IO (*.io) in the classical interface this works with out any issues, but in the new WEB interface it does not seem to be able to find it.  https://cloud.xx.info/index.php/apps/web/index.html#/draw-io/edit/%2FNew%20file.drawio and give an error "This content is blocked. Contact the site owner to fix the issue."
3. When I set my theme in the json config file it does not seem to load it, but loads the owncloud default theme.

Any help to resolve these issues is appreciated.

Thanks
George

**Comment by pascalwengerter** [comment] 2021-07-27 14:23
Hey George,

sorry this took a while. Regarding your points:
1. Not sure what the current state on OnlyOffice in the new web is, let me get back to you about it 
2. We're shipping a Draw IO extension with the `web` frontend, so enabling it in the `config.json` as shown in the [sample config](https://github.com/owncloud/web/blob/master/config/config.json.sample-oc10) under the `external_apps` should make it work
3. I linked the theming docs and some guidance in #5116, could you make it work by now?

Best,
Pascal

**Comment by pascalwengerter** [comment] 2021-08-24 12:38
@gpapaiko here's [a link to the guide](https://owncloud.dev/clients/web/deployments/oc10-app/#onlyoffice) on making `web` work with an OnlyOffice in OC10. I'll close the issue for now since all your questions are answered, please feel free to file new issues if you come across unexpected behaviour or [join our public chat](https://talk.owncloud.com/channel/web) for further support!

**Closed by pascalwengerter** 2021-08-24 12:38 UTC
Labels: Type:Theme, Web-Fastlane
