### ISSUE TITLE
Right sidebar is broken inside share jail

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10742] opened 2024-04-08 07:30 UTC
## Describe the bug
The right sidebar is broken inside the share jail.

## Steps to reproduce
1. Go into a folder that has been shared with you
2. Open the right sidebar

## Expected behavior
The right sidebar gets opened and displays information about the current folder.

## Actual behavior
The right sidebar stays blank, oC Web is in a broken state afterwards.

**Comment by AlexAndBear** [comment] 2024-04-08 11:23
Can't reproduce,

any special steps required ? 

![Screenshot 2024-04-08 at 13 22 37](https://github.com/owncloud/web/assets/26169327/0d47e1f0-602c-4a9e-a53c-5da75fb1ec0a)

**Comment by AlexAndBear** [comment] 2024-04-08 11:30
has been fixed intermediate

**Closed by AlexAndBear** 2024-04-08 11:30 UTC
Labels: Type:Bug, Priority:p3-medium
