### ISSUE TITLE
[QA] webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:154 failing randomly

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#5660] opened 2021-08-11 13:20 UTC
Another randomly failing scenario. Example https://drone.owncloud.com/owncloud/web/18187/28/14

**Comment by sakshamgurung** [comment] 2021-08-25 07:49
After investigating it was found the problem with stale DOM reference.

![Screenshot from 2021-08-25 13-24-57](https://user-images.githubusercontent.com/41365307/130749182-e7da3811-0749-48cf-82d5-b10d3d979bd2.png)

So, what can we do? Refresh page after uploading file? or any other way?

**Comment by saw-jan** [comment] 2021-09-29 09:43
I can confirm that the cause of the failure for this scenario is `stale element reference`. This might occur due to DOM refresh.
For this particular case, I suspect, file preview is causing the DOM refresh.
I duplicated the scenario multiple times and tried adding `@disablePreviews` to the feature file, all the tests passed.

**Comment by saw-jan** [comment] 2021-09-29 09:52
> Just had a debugging session on another CI issue (in #5725) with @kulmann and we saw a `stale element reference` also, but it turned out it wasn't the actual reason for failure. Maybe that is the case here also?

For shareIndicator test step, the function that gets share-indicator will get retried once if the share-indicator is not found for the first time. If that happens then you are likely to see `stale element reference` error but the test will pass (if the retry passes).

**Comment by individual-it** [comment] 2021-09-29 16:40
>  For this particular case, I suspect, file preview is causing the DOM refresh.
this seems to be the case, according to @fschade the whole row is re-rendered when the preview is loaded

**Comment by individual-it** [comment] 2021-09-29 18:47
hopefully fixed in #5852

**Closed** 2021-09-30 02:16 UTC
Labels: QA, QA:team
