### ISSUE TITLE
webUIPreview/imageMediaViewer.feature:35 test is flaky

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5454] opened 2021-07-06 07:26 UTC
test: `webUIPreview/imageMediaViewer.feature:35`
scenario: `image preview in public share`

CI log https://drone.owncloud.com/owncloud/web/16985/6/14
(including the CI log as older CI logs will be archived)
```
Then the file "testavatar.jpg" should be displayed in the media viewer webUI
--
622 | Timed out while waiting for element <//div[contains(@class, "media-viewer-file-name") and contains(text(),"testavatar.jpg")]> to be present for 20000 milliseconds. - expected "visible" but got: "not found" (20002ms)
623 | undefined    ✖ failed
624 | Timed out while waiting for element <//div[contains(@class, "media-viewer-file-name") and contains(text(),"testavatar.jpg")]> to be present for 20000 milliseconds. - expected "visible" but got: "not found" (20002ms)
625 | at Proxy.waitForMediaViewerLoaded (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/mediaViewerPage.js:15:10)
626 | at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/previewContext.js:37:26)
```
Possible cause: files are not visible at the time when the test step tries to get the file

**Comment by dpakach** [comment] 2021-07-15 04:29
The browser logs give
```
8:49:41 AM - SEVERE - http://web/js/web-app-files-21bc6fb9.js 0:116794 Uncaught TypeError: Cannot read property 'contains' of null | 393s
-- | --
634 | 8:49:41 AM - SEVERE - http://owncloud/remote.php/dav/public-files/GUSBEA9ySLGcdwR/testavatar.jpg?a=1&c=3a23435dd7d34b68d29e22f1a101dd9c&preview=1&scalingup=0&x=1280&y=1280&undefined - Failed to load resource: the server responded with a status of 400 (Bad Request) | 393s
635 | 8:49:41 AM - SEVERE - http://web/js/web-app-media-viewer-1699714c.js 0:5841 Response
```
also in the server logs it gives
```

{"reqId":"fDrvSlZkGmsqAnwkp2tH","level":4,"time":"2021-07-01T08:49:41+00:00","remoteAddr":"192.168.29.2","user":"--","app":"webdav","method":"GET","url":"\/remote.php\/dav\/public-files\/GUSBEA9ySLGcdwR\/testavatar.jpg?a=1&c=3a23435dd7d34b68d29e22f1a101dd9c&preview=1&scalingup=0&x=1280&y=1280&undefined","message":"Exception: HTTP\/1.1 400 \"\/thumbnails\" must be relative to \"files\": {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"\\\"\\\/thumbnails\\\" must be relative to \\\"files\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\Files\\\\PreviewPlugin->httpGet()\\n#1 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#2 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#3 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Server.php(332): Sabre\\\\DAV\\\\Server->start()\\n#4 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/server\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Files\\\/PreviewPlugin.php\",\"Line\":157}"}
{"reqId":"fDrvSlZkGmsqAnwkp2tH","level":4,"time":"2021-07-01T08:49:41+00:00","remoteAddr":"192.168.29.2","user":"--","app":"webdav","method":"GET","url":"\/remote.php\/dav\/public-files\/GUSBEA9ySLGcdwR\/testavatar.jpg?a=1&c=3a23435dd7d34b68d29e22f1a101dd9c&preview=1&scalingup=0&x=1280&y=1280&undefined","message":"Caused by: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"\\\"\\\/thumbnails\\\" must be relative to \\\"files\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/View.php(2051): OC\\\\Files\\\\View->getPathRelativeToFiles()\\n#1 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/View.php(2148): OC\\\\Files\\\\View->lockPath()\\n#2 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/View.php(1212): OC\\\\Files\\\\View->lockFile()\\n#3 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/View.php(280): OC\\\\Files\\\\View->basicOperation()\\n#4 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(*** sensitive parameters replaced ***)\\n#5 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/View.php(282): OC\\\\Files\\\\View->emittingCall()\\n#6 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Preview.php(1160): OC\\\\Files\\\\View->mkdir()\\n#7 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Preview.php(769): OC\\\\Preview->generatePreview()\\n#8 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(170): OC\\\\Preview->getPreview()\\n#9 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Files\\\/PreviewPlugin.php(116): OC\\\\Files\\\\Node\\\\File->getThumbnail()\\n#10 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\Files\\\\PreviewPlugin->httpGet()\\n#11 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#12 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#13 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Server.php(332): Sabre\\\\DAV\\\\Server->start()\\n#14 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#15 \\\/var\\\/www\\\/owncloud\\\/server\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/View.php\",\"Line\":2219}"}
```
seems like a problem on the server to me. But I could not reproduce it locally even running tests multiple times on loop.

**Comment by dpakach** [comment] 2021-07-15 08:12
could not reproduce it running on loop in CI so closing it for now
https://drone.owncloud.com/owncloud/web/17430/6/15

**Closed by dpakach** 2021-07-15 08:12 UTC
Labels: QA:team
