### ISSUE TITLE
Shared with me view: error on changing status of files

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/web#4946] opened 2021-04-09 13:54 UTC
### Steps to reproduce
1. Installing ocis from binary, installing web from source code
2. Go to "Shared with me" section
2. Click on "Accept" or "Decline"

### Expected behaviour
Status of clicked file changes to selected

### Actual behaviour
Error "Cannot read property "length" of undefined" appears, file status is only updated on page reload. Sometimes error "unexpected end of JSON input" appears

Console output: vendor.js:77546 POST https://localhost:9200/ocs/v2.php/apps/files_sharing/api/v1/shares/pending/a327b315-e26f-4dd4-8325-4eb9e0fbd876?format=json 500 (Internal Server Error)

**Web server:** OCIS 1.4.0, also tested with OCIS 1.3.0-rc1

**Updated from an older ownCloud or fresh install:** Web: latest master commit (ddc72b5c20561ab3992156702619cc554a67c1a8), commit from yesterday (33888cc833784d383896c1856cd42d614492aef9), works in last release version (2.1.0)

![Bildschirmfoto vom 2021-04-09 15-18-45](https://user-images.githubusercontent.com/7430156/114190664-d6300400-994b-11eb-984b-3d673b4dfc99.png)

```

**Comment by individual-it** [comment] 2021-04-20 07:30
is this a duplicate of https://github.com/owncloud/product/issues/276 ?

**Comment by kulmann** [comment] 2021-04-20 08:09
With recent changes in web we wanted to be clever and use the response of the accept/decline request for updating the respective row of the shared-with-me page. For oc10 this works fine, for oCIS the response is empty, so we cannot use it. As a quick fix we have two options:
a) go back to reloading the shared with me list (that's what we had in place in the past)
b) request the respective share and apply it to the row in the list

I prefer b) as it's less payload, but a) is the quickest solution. Looking into it right now.

**Comment by kulmann** [comment] 2021-04-20 08:10
IMO the best solution would be to actually return the share in the response, like we had it for oc10. But that's also the one that takes the most time to implement. Will work on a quick fix for now.

**Comment by kulmann** [comment] 2021-04-21 15:33
@butonic since you looked into it today, how much effort are we talking about with returning the share in the response in reva?

**Comment by butonic** [comment] 2021-04-27 13:21
after changing a share the endpoints need to reread the share and do a stat to fill in all necessary data. quite a bit of logic and testing. rough estimation 3 days.

**Comment by kulmann** [comment] 2021-05-06 21:26
For now mitigated in web by fetching the share by id after accepting/declining if the response was empty: https://github.com/owncloud/web/pull/4988

**Comment by kulmann** [comment] 2021-05-06 21:28
@elizavetaRa could you check if we can close this ticket for now? A fix in reva would be good and is in progress AFAIK. Web will be compatible with that out of the box, as the fix in reva will resemble the oc10 behaviour, which is already working.

**Comment by labkode** [comment] 2021-05-21 07:58
@kulmann the Reva PR is already there since  some weeks but the error the behaviour is still wrong. We'll give you more details today in the go-live meeting.

**Comment by kulmann** [comment] 2021-05-21 13:13
I looked into this again after the meeting. The fix in reva is merged, but `ocs.data` in the response is not an array (like with oc10), but an object. Should ideally be fixed in reva. @C0rby is taking a look.

**Comment by kulmann** [comment] 2021-05-23 08:23
Thanks to the recent fixes from @C0rby this is fixed now. Tested with most recent reva master, works like a charm. Closing this issue.

**Closed by kulmann** 2021-05-23 08:23 UTC
Labels: Early-Adopter:CERN, Type:Story

**Comment by kulmann** [comment] 2021-06-19 08:22
For the record, there is an unrelated issue https://github.com/owncloud/ocis/issues/2011 when accepting an already declined share in ocis.

**Comment by kulmann** [comment] 2021-07-02 12:22
For the record, there is an API issue in ocis when declining a previously accepted share https://github.com/owncloud/ocis/issues/2128
