### ISSUE TITLE
deleteFilesFolders.feature:59 test flaky

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#5439] opened 2021-07-02 06:14 UTC
the test in `webUIDeleteFilesFolders/deleteFilesFolders.feature:59` (batch deleting multiple files) fails sometimes with `data.zip` still being present in the UI
There is a check that the file is gone from the server before the check that its gone from the UI and strangely the server replies with 500 `7:27:17 AM - SEVERE - http://owncloud/remote.php/webdav/data.zip - Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by dpakach** [comment] 2021-07-09 06:33
This error happens because the file is locked in the server when it is trying to delete 

It gives http 500 error with following body
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Doctrine\DBAL\Exception\LockWaitTimeoutException</s:exception>
  <s:message>An exception occurred while executing 'UPDATE "oc_file_locks" SET "lock" = 0 WHERE "key" = ? AND "lock" = -1' with params ["files\/f12563bdc04e9e3c1bd7c189830fd05f"]:

SQLSTATE[HY000]: General error: 5 database is locked</s:message>
</d:error>
```

the logs in the server give this

```
{
  "reqId": "ea7ffb22-0b2d-4ead-be50-0e923b467d56",
  "level": 4,
  "time": "2021-07-09T06:30:43+00:00",
  "remoteAddr": "::1",
  "user": "admin",
  "app": "webdav",
  "method": "DELETE",
  "url": "/core/remote.php/webdav/test",
  "message": "Exception: An exception occurred while executing 'UPDATE \"oc_file_locks\" SET \"lock\" = 0 WHERE \"key\" = ? AND \"lock\" = -1' with params [\"files\\/f12563bdc04e9e3c1bd7c189830fd05f\"]:\n\nSQLSTATE[HY000]: General error: 5 database is locked: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\LockWaitTimeoutException\",\"Message\":\"An exception occurred while executing 'UPDATE \\\"oc_file_locks\\\" SET \\\"lock\\\" = 0 WHERE \\\"key\\\" = ? AND \\\"lock\\\" = -1' with params [\\\"files\\\\\\/f12563bdc04e9e3c1bd7c189830fd05f\\\"]:\\n\\nSQLSTATE[HY000]: General error: 5 database is locked\",\"Code\":0,\"Trace\":\"#0 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(182): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException()\\n#1 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(159): Doctrine\\\\DBAL\\\\DBALException::wrapException()\\n#2 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(2212): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery()\\n#3 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(1524): Doctrine\\\\DBAL\\\\Connection->handleExceptionDuringQuery()\\n#4 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/DB\\/Connection.php(238): Doctrine\\\\DBAL\\\\Connection->executeStatement()\\n#5 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(1473): OC\\\\DB\\\\Connection->executeStatement()\\n#6 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/DB\\/Connection.php(216): Doctrine\\\\DBAL\\\\Connection->executeUpdate()\\n#7 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Lock\\/DBLockingProvider.php(206): OC\\\\DB\\\\Connection->executeUpdate()\\n#8 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/Storage\\/Common.php(678): OC\\\\Lock\\\\DBLockingProvider->releaseLock()\\n#9 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Common->releaseLock()\\n#10 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#11 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#12 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(2124): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#13 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(2174): OC\\\\Files\\\\View->unlockPath()\\n#14 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(1230): OC\\\\Files\\\\View->unlockFile()\\n#15 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(370): OC\\\\Files\\\\View->basicOperation()\\n#16 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/public\\/Events\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(*** sensitive parameters replaced ***)\\n#17 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(381): OC\\\\Files\\\\View->emittingCall()\\n#18 \\/home\\/dipakacharya\\/www\\/core\\/apps\\/dav\\/lib\\/Connector\\/Sabre\\/Directory.php(348): OC\\\\Files\\\\View->rmdir()\\n#19 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#20 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(281): Sabre\\\\DAV\\\\Tree->delete()\\n#21 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/event\\/lib\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpDelete()\\n#22 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#23 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#24 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n#25 \\/home\\/dipakacharya\\/www\\/core\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(66): Sabre\\\\DAV\\\\Server->exec()\\n#26 \\/home\\/dipakacharya\\/www\\/core\\/remote.php(165): require_once('\\/home\\/dipakacha...')\\n#27 {main}\",\"File\":\"\\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractSQLiteDriver.php\",\"Line\":39}"
}
{
  "reqId": "ea7ffb22-0b2d-4ead-be50-0e923b467d56",
  "level": 4,
  "time": "2021-07-09T06:30:43+00:00",
  "remoteAddr": "::1",
  "user": "admin",
  "app": "webdav",
  "method": "DELETE",
  "url": "/core/remote.php/webdav/test",
  "message": "Caused by: {\"Exception\":\"Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception\",\"Message\":\"SQLSTATE[HY000]: General error: 5 database is locked\",\"Code\":\"HY000\",\"Trace\":\"#0 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/PDOStatement.php(114): Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception::new()\\n#1 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(1513): Doctrine\\\\DBAL\\\\Driver\\\\PDOStatement->execute()\\n#2 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/DB\\/Connection.php(238): Doctrine\\\\DBAL\\\\Connection->executeStatement()\\n#3 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(1473): OC\\\\DB\\\\Connection->executeStatement()\\n#4 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/DB\\/Connection.php(216): Doctrine\\\\DBAL\\\\Connection->executeUpdate()\\n#5 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Lock\\/DBLockingProvider.php(206): OC\\\\DB\\\\Connection->executeUpdate()\\n#6 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/Storage\\/Common.php(678): OC\\\\Lock\\\\DBLockingProvider->releaseLock()\\n#7 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Common->releaseLock()\\n#8 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#9 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#10 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(2124): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#11 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(2174): OC\\\\Files\\\\View->unlockPath()\\n#12 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(1230): OC\\\\Files\\\\View->unlockFile()\\n#13 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(370): OC\\\\Files\\\\View->basicOperation()\\n#14 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/public\\/Events\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(*** sensitive parameters replaced ***)\\n#15 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(381): OC\\\\Files\\\\View->emittingCall()\\n#16 \\/home\\/dipakacharya\\/www\\/core\\/apps\\/dav\\/lib\\/Connector\\/Sabre\\/Directory.php(348): OC\\\\Files\\\\View->rmdir()\\n#17 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#18 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(281): Sabre\\\\DAV\\\\Tree->delete()\\n#19 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/event\\/lib\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpDelete()\\n#20 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#21 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#22 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n#23 \\/home\\/dipakacharya\\/www\\/core\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(66): Sabre\\\\DAV\\\\Server->exec()\\n#24 \\/home\\/dipakacharya\\/www\\/core\\/remote.php(165): require_once('\\/home\\/dipakacha...')\\n#25 {main}\",\"File\":\"\\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/PDO\\/Exception.php\",\"Line\":18}"
}
{
  "reqId": "ea7ffb22-0b2d-4ead-be50-0e923b467d56",
  "level": 4,
  "time": "2021-07-09T06:30:43+00:00",
  "remoteAddr": "::1",
  "user": "admin",
  "app": "webdav",
  "method": "DELETE",
  "url": "/core/remote.php/webdav/test",
  "message": "Caused by: {\"Exception\":\"PDOException\",\"Message\":\"SQLSTATE[HY000]: General error: 5 database is locked\",\"Code\":\"HY000\",\"Trace\":\"#0 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/PDOStatement.php(112): PDOStatement->execute()\\n#1 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(1513): Doctrine\\\\DBAL\\\\Driver\\\\PDOStatement->execute()\\n#2 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/DB\\/Connection.php(238): Doctrine\\\\DBAL\\\\Connection->executeStatement()\\n#3 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(1473): OC\\\\DB\\\\Connection->executeStatement()\\n#4 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/DB\\/Connection.php(216): Doctrine\\\\DBAL\\\\Connection->executeUpdate()\\n#5 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Lock\\/DBLockingProvider.php(206): OC\\\\DB\\\\Connection->executeUpdate()\\n#6 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/Storage\\/Common.php(678): OC\\\\Lock\\\\DBLockingProvider->releaseLock()\\n#7 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Common->releaseLock()\\n#8 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#9 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(611): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#10 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(2124): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->releaseLock()\\n#11 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(2174): OC\\\\Files\\\\View->unlockPath()\\n#12 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(1230): OC\\\\Files\\\\View->unlockFile()\\n#13 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(370): OC\\\\Files\\\\View->basicOperation()\\n#14 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/public\\/Events\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(*** sensitive parameters replaced ***)\\n#15 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/private\\/Files\\/View.php(381): OC\\\\Files\\\\View->emittingCall()\\n#16 \\/home\\/dipakacharya\\/www\\/core\\/apps\\/dav\\/lib\\/Connector\\/Sabre\\/Directory.php(348): OC\\\\Files\\\\View->rmdir()\\n#17 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#18 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(281): Sabre\\\\DAV\\\\Tree->delete()\\n#19 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/event\\/lib\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpDelete()\\n#20 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#21 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#22 \\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n#23 \\/home\\/dipakacharya\\/www\\/core\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(66): Sabre\\\\DAV\\\\Server->exec()\\n#24 \\/home\\/dipakacharya\\/www\\/core\\/remote.php(165): require_once('\\/home\\/dipakacha...')\\n#25 {main}\",\"File\":\"\\/home\\/dipakacharya\\/www\\/core\\/lib\\/composer\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/PDOStatement.php\",\"Line\":112}"
}
```

**Comment by individual-it** [comment] 2021-07-09 07:12
Then it looks like (again) an issue with locking on the server. Are there any other actions pending in the UI tests that we have to wait for to be finished e.g. thumbnail downloads or is the server locking the file for some other reason? If so, we have to move the issue to core repo and think how to make the tests be still stable

**Comment by dpakach** [comment] 2021-07-09 08:50
@individual-it it fails even when previews are disabled and I cant find any other tasks pending

**Comment by individual-it** [comment] 2021-07-09 09:01
maybe it would be best to leave this issue here, so that we can use it to work around the core-bug and create a new one in core repo (if there is no one yet that covers it)

CC @micbar

**Comment by pascalwengerter** [comment] 2021-09-21 09:53
Haven't seen this one being flaky in a long time, closing for now. Feel free to reopen if applicable

**Comment by phil-davis** [comment] 2021-11-19 05:57
Happened again in the nightly CI:
https://drone.owncloud.com/owncloud/web/20377/44/18
```
    Then as "Alice" file "data.zip" should not exist
    And as "Alice" file "lorem.txt" should not exist
    And as "Alice" folder "simple-folder" should not exist
    And the deleted elements should not be listed on the webUI
    ✖ failed
      AssertionError [ERR_ASSERTION]: Expected resource 'lorem.txt' to be 'not present' but found 'present'
          + expected - actual

          -false
          +true

          at assertElementsAreNotListed (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:962:12)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I check the nightly each morning, so I will report here each time I see it fail.

**Comment by individual-it** [comment] 2021-11-22 05:07
It might be that the real issue is in core, see https://github.com/owncloud/core/issues/38221

**Comment by sakshamgurung** [comment] 2021-11-22 08:52
After analyzing the logs and behavior it seems to be caused by bug in `core` project which introduces deadlock as mentioned in this PR https://github.com/owncloud/core/issues/38221.  Failed logs are available herehttps://drone.owncloud.com/owncloud/web/20377/44/13 .
This PR: https://github.com/owncloud/web/pull/6043 skips the test in OC10 for now.

**Comment by phil-davis** [comment] 2021-11-22 08:54
After #6043 is merged we can close this issue. The core issue will remain open and is referenced in the feature file here, so it can be found...

**Comment by phil-davis** [comment] 2021-11-22 11:44
Test has been skipped.

**Closed by phil-davis** 2021-11-22 11:44 UTC
Labels: QA:team
