### ISSUE TITLE
View options closing right sidebar

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#5489] opened 2021-07-08 22:40 UTC
### Steps to reproduce
1. Open the right sidebar for any file/folder
2. Click on `View` options menu

### Expected behaviour
The view options dropdown menu appears without any other visual changes

### Actual behaviour
The right sidebar closes, because this is counted as an `outside click` (see directive).

### Screenshot
<img width="2593" alt="Screenshot 2021-07-09 at 00 37 43" src="https://user-images.githubusercontent.com/3532843/124999363-3e2adf00-e04e-11eb-8ea5-ed4140fbc178.png">

**Comment by LukasHirt** [comment] 2021-07-09 09:02
@tbsbdr current behaviour is closing the sidebar if user clicks anywhere outside of it. TBH it feels strange. It's no dropdown or overlay but actually becomes a "part" of the content if it's opened as it even squashes the files list. If it is closed if I click anywhere else, it just feels broken to me.

What would you say about removing this behaviour? If we anyway go with permanently visible sidebar then it wouldn't make any sense to close it anywhere else than via designated buttons :shrug: /cc @kulmann

**Comment by tbsbdr** [comment] 2021-07-09 11:53
> TBH it feels strange.

fully agree. clicking outside should just deselect the item(s)
issue should be addressed by https://github.com/owncloud/web/issues/5497

since the issue is just "strange" but doesn't prevent users from doing their task, i would suggest to postpone fixing the bug until we have the show-sidebar switch. what do you think?

**Comment by LukasHirt** [comment] 2021-07-09 12:30
@tbsbdr I agree that it should be mainly taken care of in issues you mentioned. There's still the bug that clicking the view options closes it and then the position of the dropdown is wrong (as seen on the screenshot). Would "not deselecting and closing the sidebar" be okay until the new behaviour is implemented?

**Comment by pascalwengerter** [comment] 2021-08-23 12:51
Thought this was resolved by #5678, but changing the number of items to paginate still clears the selection (show-hidden-files checkbox doesn't). Neither close the sidebar anymore though

**Comment by pascalwengerter** [comment] 2021-12-08 16:13
Can't reproduce on https://ocis.ocis-web.latest.owncloud.works, also we don't close the sidebar on outside clicks anymore for quite some time

**Closed by pascalwengerter** 2021-12-08 16:13 UTC
Labels: Type:Bug, Priority:p2-high, Category:Defect
