### ISSUE TITLE
Upload in file-drop public link flattens folder hierarchy

### ISSUE THREAD

**Issue by skshetry** [owncloud/web#2443] opened 2019-11-12 08:45 UTC
### Steps to reproduce
1. Create a files-drop link.
2. Open the files-drop link.

### Expected behaviour
Some way to upload folder

### Actual behaviour
No way to upload a folder. Dragging a folder uploads the contents of the folder (recurse through it and flattens them).
Also, using `setValue` and trying to upload folder through `Nightwatch` creates an empty file.

**Comment by PVince81** [comment] 2019-11-12 08:46
@skshetry mind trying this with OC 10 ?

as far as I remember we don't support subdirectories in files drop mode so this might be expected behavior

**Comment by skshetry** [comment] 2019-11-14 06:36
@PVince81, Folder uploads in OC 10 are not supported at all. Close this or is this a requirement (it is listed on #2222)?

Also, `phoenix` should not upload folder as an `empty` file and nor should it flatten them and upload..

**Comment by PVince81** [comment] 2019-11-14 08:40
not a requirement imo, it would mess up the concept and make it more complex as we'd need to avoid file name collisions even across folders.

@pmaier1 thoughts ?

**Comment by PVince81** [comment] 2019-11-14 08:55
@pmaier1 please reopen if you think we want to change how it works in Phoenix

**Comment by skshetry** [comment] 2019-11-15 05:38
@PVince81, then, I would not expect the contents of sub-folders getting uploaded in the root of the publicly-shared folder (at least they should be in their respective sub-folders).

**Comment by PVince81** [comment] 2019-11-15 09:49
@skshetry you're right. We need to block this with a warning.

**Comment by pascalwengerter** [comment] 2021-04-06 10:07
@skshetry could you retry this with all the changes that have occured in the last ~1,5 years? Should work fine now 😉

**Comment by dpakach** [comment] 2021-04-12 03:47
@pascalwengerter, uploading folders seems to work but all the files in the folder will be flattened.
for example, if we upload a folder with the following structure
```
├── upload
│   ├── file1.pdf
│   ├── file.ttf
│   └── sub
│       └── file2.pdf
```
it will upload all 3 files `file1.pdf`, `file.ttf`, and `file2.pdf` will be uploaded in the same folder. Is that correct behavior?

Uploading a similar folder in the main files section keeps the folder structure of the originally uploaded folder.

**Comment by saw-jan** [comment] 2021-06-28 05:10
@pascalwengerter 
Is the current behavior the expected one?

**Comment by pascalwengerter** [comment] 2021-07-09 10:29
> @pascalwengerter
> Is the current behavior the expected one?

No, should upload the folder including files & subfolders the way they were structured before

**Comment by kulmann** [comment] 2022-05-09 14:51
Uploads have been mostly re-implemented in a recent pull request (https://github.com/owncloud/web/pull/6202). Issue still seems to be present. Since this corrupts uploaded data / modifies uploaded data in an unexpected way I've decided to elevate this to a P1.

**Comment by JammingBen** [comment] 2022-05-10 09:56
@pmaier1 

We noticed some inconsistencies between oC10 and oCIS when uploading contents to a public drop-page:

When uploading a file that already exists, oC10 will create a new file with a suffix (e.g. `file (1)`). oCIS in the other hand just overwrites the existing file by creating a new version. What is the desired behavior here? Also, how do we deal with folder uploads in this case? The classic UI does not support folder uploads on public drop-pages, but the new WebUI does.

**Comment by pmaier1** [comment] 2022-05-12 13:38
> When uploading a file that already exists, oC10 will create a new file with a suffix (e.g. file (1)). oCIS in the other hand just overwrites the existing file by creating a new version. What is the desired behavior here?

Thanks for pointing at this. IMO the oC10 behavior is correct. Main reason for that is that we should cover for the case that occurs when multiple people upload files with the same name to a file drop link. In that case it does not make sense to create versions as the files most probably really are distinct except that they have the same name. Same behavior for folders then.
IIRC there was some ticket in ocis or reva repo discussion this behavior but I can't find it atm.

Apart from that, I think the versioning feature should not be exposed at all in the context of a (public) link.

**Comment by pmaier1** [comment] 2022-05-12 13:40
Found it
- https://github.com/cs3org/reva/issues/2480
- https://github.com/cs3org/reva/pull/2510

The behavior is described, discussed and agreed there. cc @micbar

**Comment by phil-davis** [comment] 2022-05-12 14:21
The response to the initial create of a folder is going to return some HTTP status 2nn. The response could also have the actual "allocated" resource name as a data item in the response body. Then the client can know what name the folder has, and can then create the rest of the folder structure under that folder name.

The other approach would be that if the folder already exists, then the server can respond with something like 409 "conflict", and in the response body provide a suggested alternative folder name `xyz (1)` for example. The problem with that is that the client has to loop possibly multiple times. By the time the client gets the response and then sends a request to create `xyz (1)`, some other client might have done the same, and the server will now respond again with 409 and suggest `xyz (2)` ...

**Comment by pascalwengerter** [comment] 2022-05-12 14:26
> The response to the initial create of a folder is going to return some HTTP status 2nn. The response could also have the actual "allocated" resource name as a data item in the response body. Then the client can know what name the folder has, and can then create the rest of the folder structure under that folder name.
> 
> The other approach would be that if the folder already exists, then the server can respond with something like 409 "conflict", and in the response body provide a suggested alternative folder name `xyz (1)` for example. The problem with that is that the client has to loop possibly multiple times. By the time the client gets the response and then sends a request to create `xyz (1)`, some other client might have done the same, and the server will now respond again with 409 and suggest `xyz (2)` ...

There is also a security concern about not disclosing what files&folders are present in whatever folder you create a dropLink for - which means the backend should "silently swallow" whatever the public uploads there and then handle renaming backend-only

**Comment by JammingBen** [comment] 2022-05-12 14:27
I'm all in favor of letting the backend handle this, hence the first approach sounds good to me:

> The response to the initial create of a folder is going to return some HTTP status 2nn. The response could also have the actual "allocated" resource name as a data item in the response body. Then the client can know what name the folder has, and can then create the rest of the folder structure under that folder name.

However, either way, the client will know that there is a resource with that exact name. I'm not sure if that is information we want to publish to the outside world.

**Comment by pascalwengerter** [comment] 2022-05-12 14:30
> I'm all in favor of letting the backend handle this, hence the first approach sounds good to me:
> 
> > The response to the initial create of a folder is going to return some HTTP status 2nn. The response could also have the actual "allocated" resource name as a data item in the response body. Then the client can know what name the folder has, and can then create the rest of the folder structure under that folder name.
> 
> However, either way, the client will know that there is a resource with that exact name. I'm not sure if that is information we want to publish to the outside world.

Can't we handle subsequent (child folder) uploads based on the resourceId of the previously uploaded (parent) resource, hence not disclosing anything about potential renaming happening?

**Comment by pmaier1** [comment] 2022-05-12 14:30
> There is also a security concern about not disclosing what files&folders are present in whatever folder you create a dropLink for - which means the backend should "silently swallow" whatever the public uploads there and then handle renaming backend-only

Exactly, this is important. Clients must not have any way to infer the content of the file drop folder.

**Comment by phil-davis** [comment] 2022-05-12 14:32
> Can't we handle subsequent (child folder) uploads based on the resourceId of the previously uploaded (parent) resource, hence not disclosing anything about potential renaming happening?

That sounds promising - the response to the "create resource" request provides a resourceId which is a "magic string" unrelated to the resource name. The client can then create child resource under that.

**Comment by JammingBen** [comment] 2022-05-12 14:35
Good idea, AFAIK this would need to be implemented first though. The ownCloud SDK (and oCIS itself?) only works with paths.

**Comment by PrajwolAmatya** [comment] 2024-02-14 05:45
This issue doesn't seem to occur in latest master. Checked manually by uploading the folder with following structure in a public link share.
```
├── upload
│   ├── file1.txt
│   ├── file2.txt
│   └── sub
│       ├── file1.pdf
│       └── file2.pdf
```
The folder is uploaded with the same folder structure. The folder upload is currently not supported in playwright, so only tested manually. So, closing this issue for now.
CC @ScharfViktor

**Closed by PrajwolAmatya** 2024-02-14 05:45 UTC
Labels: Type:Bug, feature:files, Status:Blocked
