### ISSUE TITLE
Nightly failure `webUIFilesCopy/copy.feature:38`

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#7403] opened 2022-08-04 05:04 UTC
Nightly build: https://drone.owncloud.com/owncloud/web/27333/47/20
Scenario: `webUIFilesCopy/copy.feature:38`
```feature
- Connecting to selenium on port 4444...
ℹ Connected to selenium on port 4444 (423ms).
  Using: chrome (94.0.4606.61) on Linux platform.
INFO: setting screen resolution to 375x812

  Scenario: Copy multiple files at once # features/webUIFilesCopy/copy.feature:38
    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server
    And the administrator has set the default folder for received shares to "Shares" in the server
    And user "Alice" has been created with default attributes and without skeleton files in the server
    Given user "Alice" has uploaded file "data.zip" to "data.zip" in the server
    And user "Alice" has uploaded file "lorem.txt" to "lorem.txt" in the server
    And user "Alice" has uploaded file "new-data.zip" to "testapp.zip" in the server
    And user "Alice" has created folder "simple-empty-folder" in the server
    And user "Alice" has logged in using the webUI
√ Element <#user> was visible after 1371 milliseconds.
√ Element <#user> was not present after 42 milliseconds.
√ Element <#files-view> was visible after 1436 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 287 milliseconds.
    And the user has reloaded the current page of the webUI
    When the user batch copies these files into folder "simple-empty-folder" using the webUI
      │ file_name   │
      │ data.zip    │
      │ lorem.txt   │
      │ testapp.zip │
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='data.zip' or @data-test-resource-path='/data.zip')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 38 milliseconds.
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 33 milliseconds.
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='testapp.zip' or @data-test-resource-path='/testapp.zip')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 43 milliseconds.
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-empty-folder' or @data-test-resource-path='/simple-empty-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 44 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 85 milliseconds.
√ Element <button#location-picker-btn-confirm> was visible after 43 milliseconds.
Timed out while waiting for element <button#location-picker-btn-confirm> to be removed for 200 milliseconds. - expected "not found" but got: "found" (209ms)
Timed out while waiting for element <button#location-picker-btn-confirm> to be removed for 200 milliseconds. - expected "not found" but got: "found" (209ms)
    at Proxy.selectFolderAndConfirm (/var/www/owncloud/web/tests/acceptance/pageObjects/locationPicker.js:12:20)
    at Proxy.copyMultipleResources (/var/www/owncloud/web/tests/acceptance/pageObjects/personalPage.js:265:14)
    at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:1321:12) {
  showDiff: false,
  name: 'NightwatchAssertError',
  abortOnFailure: true
}
undefined    ✖ failed
      Error: ElementPresentError
          at Proxy.selectFolderAndConfirm (/var/www/owncloud/web/tests/acceptance/pageObjects/locationPicker.js:18:15)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.copyMultipleResources (/var/www/owncloud/web/tests/acceptance/pageObjects/personalPage.js:265:14)
          at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:1321:12)
    Then breadcrumb for folder "simple-empty-folder" should be displayed on the webUI
    - skipped
    And the following files should be listed on the webUI
      │ file_name   │
      │ data.zip    │
      │ lorem.txt   │
      │ testapp.zip │
    - skipped

  Result: FAILED
```

**Comment by SwikritiT** [comment] 2022-08-04 06:41
```
56 scenarios (56 passed)
672 steps (672 passed)
```
passed in every run. 😭

**Comment by SwikritiT** [comment] 2022-08-05 07:54
couldn't reproduce it locally, the tests passed in CI on multiple runs as well https://drone.owncloud.com/owncloud/web/27360
Won't be investigating a lot of time in this for now. If this reappears I'll look at it again

**Comment by SwikritiT** [comment] 2022-08-18 03:39
This failure hasn't been encountered lately moving to the backlog

**Comment by amrita-shrestha** [comment] 2022-09-16 07:16
this PR https://github.com/owncloud/web/pull/7309 has fixed this failure so closing this issue

**Closed by amrita-shrestha** 2022-09-16 07:16 UTC
Labels: QA:team
