### ISSUE TITLE
Responses are rendered in different places

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5085] opened 2021-05-07 06:03 UTC
If I send a request to list a large directory /`A/B/C`.
In the mean time I change path to `/Z`.
Request to `/A/B/C` finished and shows the content of `C` inside `Z`.

The expected behaviour is that the response should not be rendered as this is not the original path it was requested.

**Comment by pascalwengerter** [comment] 2021-07-12 08:11
@labkode could you check if this is still the case? Should have been fixed by our recent changes

**Comment by pascalwengerter** [comment] 2021-07-28 15:30
Closed as fixed (due to various performance improvements) unless @labkode can reproduce

**Comment by labkode** [comment] 2021-10-14 14:15
@kulmann @dragotin 
This is a major blocker for our roll-out and needs to be fixed in short-time (days).
By manually testing it you end up with: browsing into a directory and is empty, browsing into a directory that contains contents from other places, clicking on shared with me and listing your home files rather than your shares, etc ...

**Comment by kulmann** [comment] 2021-10-15 04:49
> @kulmann @dragotin
> This is a major blocker for our roll-out and needs to be fixed in short-time (days).
> By manually testing it you end up with: browsing into a directory and is empty, browsing into a directory that contains contents from other places, clicking on shared with me and listing your home files rather than your shares, etc ...

Thank you for your comment, I was finally able to reproduce it locally. We only solved edge cases within one view so far (so if you navigate into sub- or parent-folders in the `All files` list). That all works fine now as far as I know, because those requests are resolved sequentially. BUT: across views requests for loading resources can indeed overlap. So a slow loading "shared with me" will render into a fast loading "All files" view and vice versa. "render" is not 100% correct because there are also some error cases, where you'll see "resource not found". With that I'll shift priority back onto https://github.com/owncloud/web/pull/5892 immediately (now).

**Comment by fschade** [comment] 2021-10-17 10:00
@labkode can you please test https://github.com/owncloud/web/pull/5917. Should fix it, i hope i spotted all places.

**Comment by fschade** [comment] 2021-10-20 07:40
thanks @diocas

**Comment by elizavetaRa** [comment] 2022-08-30 14:53
We can reproduce this issue again 
![Files shared with me - CERNBox](https://user-images.githubusercontent.com/7430156/187469460-ad44a684-2148-4529-b51a-9275ebe2520f.gif)

**Comment by kulmann** [comment] 2022-08-31 07:43
Please provide steps to reproduce. If I do what you show in the screen capture, even with throttled connection and large folders, I can't reproduce it.

**Comment by dragotin** [comment] 2023-02-13 12:10
Seems fixed, if not @elizavetaRa please reopen.

**Closed by dragotin** 2023-02-13 12:10 UTC
Labels: Type:Bug, Category:Defect, Early-Adopter:CERN
