### ISSUE TITLE
Return to the main menu after closing the Mediaviewer does not work correctly on public links

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6127] opened 2021-12-10 13:46 UTC
### Steps to reproduce
1. add file jpeg and create public link 
2. open public link 
3. open file jpeg in mediaviewer 
4. close mediaviewer and return to main page

### Expected behaviour
you go back to the "public link" directory and see the "jpg" file.

BUT: If you create a public link to a folder with a file, it works correctly

### Actual behaviour

https://user-images.githubusercontent.com/84779829/145582192-4d939729-e73c-4a89-9b5a-986b50d3f739.mov

Env:
up ocis local
OCIS_VERSION=v1.16.0
Web_version= v4.6.1
BRANCH=v1.16.0-rc2

**Comment by pascalwengerter** [comment] 2022-02-09 08:58
Can't reproduce on current master, seems like https://github.com/owncloud/web/pull/6331 closed it? Can someone confirm it's resolved?

**Comment by kulmann** [comment] 2022-02-09 09:04
> Can't reproduce on current master, seems like #6331 closed it? Can someone confirm it's resolved?

Yep, was fixed in that PR. Closing here

**Closed by kulmann** 2022-02-09 09:04 UTC
Labels: feature:files, Priority:p2-high, feature:media-viewer, bug
