### ISSUE TITLE
[oC10] "Copy quicklink" always creates a new link

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#8033] opened 2022-11-28 14:06 UTC
### Steps to reproduce
1. Create a folder `someFolder`, including some files
2. Create a quicklink for `someFolder` via "Copy quicklink"
3. Click "Copy quicklink" again
4. Navigate into `someFolder`, select a file and open the "indirect links" section of the sharing sidebar

### Expected behaviour
The link from the already existing quicklink will be taken. No new quicklink will be created

### Actual behaviour
A new quicklink is being created. You can't notice this on the resource `someFolder` directly, but in the indirect link. Navigate into the folder and check the resources within.

![image](https://user-images.githubusercontent.com/50302941/204297292-d41eb094-b8fa-4b0f-ae04-b621f5427838.png)

**Comment by JammingBen** [comment] 2022-11-28 14:19
oCIS handles this on the server side, I guess oC10 should do the same.

**Comment by kulmann** [comment] 2022-11-29 23:31
I can't reproduce this with oC 10 🤔

**Comment by JammingBen** [comment] 2022-11-30 07:34
Are you sure you checked the indirect links? Again, the multiple links are not visible on the resource itself, but on its children.

**Comment by kulmann** [comment] 2022-11-30 07:40
> Are you sure you checked the indirect links? Again, the multiple links are not visible on the resource itself, but on its children.

Urgh.... didn't pay enough attention to the expected behaviour. Maybe you could add a `navigate into subfolder and open the "indirect links" section of the sharing sidebar` step to the steps to reproduce for the impatient reader 🤣 

True, I see the multiple quicklinks as well on a subfolder.

**Comment by JanAckermann** [comment] 2023-08-17 13:59
Closing as OC10 Support has been discontinued with version 7.1.0

**Closed by JanAckermann** 2023-08-17 13:59 UTC
Labels: Type:Bug, Priority:p4-low
