### ISSUE TITLE
Public link in mobile shows gray bar and no longer the title

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/web#10938] opened 2024-05-21 11:19 UTC
## Describe the bug
When shrinking the view to mobile scale the title of the public link is no longer visible but only a gray bar.

## Steps to reproduce
1. Upload file
2. Create public link to file
3. Open public link

e.g. https://infinite.owncloud.com/s/yAinlUxqEFjxpBT
![image](https://github.com/owncloud/web/assets/1005065/fd5782bc-508f-4e25-b781-64388aa18901)

**Comment by AlexAndBear** [comment] 2024-05-22 09:33
Not showing the title 'Public link' is intended on small displays.
The grey background issue can't be reproduced on master, so I will close the issue as completed

**Comment by AlexAndBear** [comment] 2024-05-22 10:03
Reopening, was able to reproduce

**Closed** 2024-05-22 20:30 UTC
Labels: Type:Bug, Priority:p3-medium
