### ISSUE TITLE
no zoom functionality in the mediaviewer in new web UI

### ISSUE THREAD

**Issue by mcarioscio-ownCloud** [owncloud/web#5571] opened 2021-07-27 12:36 UTC
### Steps to reproduce
1.open photo in new web UI
2.look for zoom buttons (couldn't find)
3.Crtl+ to zoom Firefox browser (didn't work)

### Expected behaviour
There should be a button to zoom in or out on a photo

### Actual behaviour
there is no buttons for zoom

### Server configuration
demo.owncloud.com

### Client configuration
**Browser:** Firefox 90.0.2 (64)

**Operating system:** Windows 10

**Comment by kulmann** [comment] 2022-08-22 16:15
Closing in favor / as duplicate of https://github.com/owncloud/web/issues/7160

**Closed by kulmann** 2022-08-22 16:15 UTC
