### ISSUE TITLE
Web crashes after sharing project space with `Secure viewer` permission

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#10891] opened 2024-05-10 09:58 UTC
## Describe the bug
Share project space with `Secure viewer` role cause web crash. In ocis there is bug report regarding secure view https://github.com/owncloud/ocis/issues/9128

## Steps to reproduce
1. user `Alice` create project space `new-space`
2. user `Alice` share project space `new-space` with user `einstein` with permission role `Secure viewer`
3. reload web in browser than page stuck at loading

## Expected behavior
Personal WebUI page should be visible

## Actual behavior
![Screenshot from 2024-05-10 15-27-52](https://github.com/owncloud/web/assets/54478846/b0adffac-5fee-49fc-b1d2-6e2cb9ebfa04)

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
ownCloud	Infinite Scale
Edition	Community
Version	5.1.0-prealpha+ceeb4ed71d
Web client version	9.0.0-alpha.5
```

</p>
</details>

**Comment by JammingBen** [comment] 2024-05-21 09:39
Has been fixed in Web via https://github.com/owncloud/web/pull/10925. Now waiting for the backend issue to be closed/fixed, I'm closing here meanwhile.

**Comment by S-Panta** [comment] 2024-06-03 08:54
Building Ocis on latest commit, the web seems to crash when space is shared via `Secure Viewer`. 

![image](https://github.com/owncloud/web/assets/64484313/143c4433-8eb7-4970-ae2c-f94bab3829e1)

**Comment by saw-jan** [comment] 2024-06-03 11:06
Maybe fixed by https://github.com/owncloud/web/pull/10973

**Comment by S-Panta** [comment] 2024-06-03 11:09
> Maybe fixed by #10973

It's still showing on my latest build.

**Comment by saw-jan** [comment] 2024-06-03 11:15
Couldn't reproduce. believed to be fixed by https://github.com/owncloud/web/pull/10973

**Closed by saw-jan** 2024-06-03 11:15 UTC
Labels: Type:Bug

**Comment by S-Panta** [comment] 2024-06-03 11:18
If the role is changed from `Secure Viewer`, then the crash UI will be `uncrashed` and back to Normal.

**Comment by saw-jan** [comment] 2024-06-03 11:24
> Has been fixed in Web via https://github.com/owncloud/web/pull/10925. Now waiting for the backend issue to be closed/fixed, I'm closing here meanwhile.

The above fix was sufficient.
The reports were just due to setup mismatch between web and ocis
