### ISSUE TITLE
webUITrashbinDelete/trashbinDelete.feature:112 test is flaky

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5453] opened 2021-07-06 07:19 UTC
test: `webUITrashbinDelete/trashbinDelete.feature:112`
scenario: `Delete single file from deleted files list`

CI log https://drone.owncloud.com/owncloud/web/16985/60/9
(including the CI log as older CI logs will be archived)
```
When the user deletes the file "lorem.txt" from the deleted files list
--
720 | Timed out while waiting for element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> to be present for 20000 milliseconds. - expected "found" but got: "not found" (20005ms)
721 | undefined    ✖ failed
722 | Timed out while waiting for element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> to be present for 20000 milliseconds. - expected "found" but got: "not found" (20005ms)
723 | at Proxy._callee20$ (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:288:18)
724 | at asyncGeneratorStep (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:27:103)
725 | at _next (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:29:194)
```
Possible cause: files are not visible in the files-list at the time when the test step tries to get the file

**Comment by jasson99** [comment] 2021-07-21 08:46
I could not reproduce it, locally as well as in CI. We can re-open it if we encounter this again. Closing this issue for now.

**Closed by jasson99** 2021-07-21 08:46 UTC
Labels: QA:team
