### ISSUE TITLE
Multiline breadcrumb with long folder names looks not well formatted

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7579] opened 2022-09-02 09:13 UTC
### Steps to reproduce
1. Create deep nested folders with long folder names

### Expected behaviour
Breadcrumb adapts responsively

### Actual behaviour
![grafik](https://user-images.githubusercontent.com/16665512/188103054-e410ab08-9f17-4a23-8bea-ae87ac66a7b2.png)

Also: Cog wheel and right sidebar switch is misplaced

Maybe 
- reduce font size
- add ellipsis for long folder names
- adapt folder name max length (= where the name is cut off and `…` is shown) responsively

![grafik](https://user-images.githubusercontent.com/16665512/188105768-a395978a-6a73-44bb-8531-e60f5cf62850.png)

Happened to me in a real live working situation.
Tested in Firefox, Chrome, Safari

https://ocis.ocis-wopi.latest.owncloud.works

**Comment by kulmann** [comment] 2022-09-02 09:14
Closing as duplicate of https://github.com/owncloud/web/issues/6731

**Comment by hurradieweltgehtunter** [comment] 2022-09-02 09:15
whoops. ty.

**Closed by kulmann** 2022-09-02 09:14 UTC
Labels: Type:Bug
