### ISSUE TITLE
webUISharingAcceptShares/acceptShares.feature:100 test is flaky

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5457] opened 2021-07-06 07:38 UTC
test: `webUISharingAcceptShares/acceptShares.feature:100`
scenario: `decline an offered (pending) share`

CI log https://drone.owncloud.com/owncloud/web/17049/9/14
(including the CI log as older CI logs will be archived)
```
And user "Alice" has uploaded file with content "test" to "anotherfile.txt"
--
166 | ✖ failed
167 | Error: function timed out, ensure the promise resolves within 180000 milliseconds
168 | at Timeout._onTimeout (/var/www/owncloud/web/node_modules/cucumber/lib/user_code_runner.js:76:18)
169 | at listOnTimeout (node:internal/timers:557:17)
170 | at processTimers (node:internal/timers:500:7)
```
Possible cause: TBD

**Comment by dpakach** [comment] 2021-07-15 05:20
line number changed to webUISharingAcceptShares/acceptShares.feature:93

**Comment by dpakach** [comment] 2021-07-15 06:18
I could not reproduce it so I'm closing this for now we will revisit this if this starts happening again.

**Closed by dpakach** 2021-07-15 06:18 UTC
Labels: QA:team
