### ISSUE TITLE
Unit test failure in recent nightly build and needs investigation

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6764] opened 2022-04-11 03:43 UTC
https://drone.owncloud.com/owncloud/web/24623/8/6
https://drone.owncloud.com/owncloud/web/24624/8/6

```console
Summary of all failing tests
FAIL packages/web-app-files/tests/unit/views/shares/SharedWithOthers.spec.js (29.552 s)
  ● SharedWithOthers view › when the wrapper is not loading anymore › when length of paginated resources is greater than zero › should load the resource table with correct props

    expect(received).toMatchSnapshot()

    Snapshot name: `SharedWithOthers view when the wrapper is not loading anymore when length of paginated resources is greater than zero should load the resource table with correct props 1`

    - Snapshot  - 4
    + Received  + 4

    @@ -32,11 +32,11 @@
            <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-sharedWith">
              <oc-button-stub type="button" size="medium" submit="button" variation="inverse" appearance="raw" justifycontent="center" gapsize="medium">
                <oc-avatars-stub items="[object Object]" stacked="true" istooltipdisplayed="true" maxdisplayed="3" accessibledescription=" This folder is shared via 1 link" class="resource-table-people"></oc-avatars-stub>
              </oc-button-stub>
            </td>
    -       <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-sdate" aria-label="9 months ago (June 9, 2021, 12:44 PM UTC)"><span tabindex="0">9 months ago</span></td>
    +       <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-sdate" aria-label="10 months ago (June 9, 2021, 12:44 PM UTC)"><span tabindex="0">10 months ago</span></td>
            <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-actions oc-pr-m">
              <div class="resource-table-actions">
                <oc-button-stub type="button" size="medium" arialabel="Show context menu" submit="button" variation="passive" appearance="raw" justifycontent="center" gapsize="medium" id="context-menu-trigger-38" class="resource-table-btn-action-dropdown"><span class="oc-icon oc-icon-m oc-icon-passive"><!----></span></oc-button-stub>
                <oc-drop-stub dropid="context-menu-drop-38" popperoptions="[object Object]" toggle="#context-menu-trigger-38" position="bottom-start" mode="click" closeonclick="true" paddingsize="small"></oc-drop-stub>
              </div>
    @@ -55,11 +55,11 @@
            <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-sharedWith">
              <oc-button-stub type="button" size="medium" submit="button" variation="inverse" appearance="raw" justifycontent="center" gapsize="medium">
                <oc-avatars-stub items="[object Object]" stacked="true" istooltipdisplayed="true" maxdisplayed="3" accessibledescription=" This folder is shared via 1 link" class="resource-table-people"></oc-avatars-stub>
              </oc-button-stub>
            </td>
    -       <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-sdate" aria-label="9 months ago (June 9, 2021, 12:44 PM UTC)"><span tabindex="0">9 months ago</span></td>
    +       <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-sdate" aria-label="10 months ago (June 9, 2021, 12:44 PM UTC)"><span tabindex="0">10 months ago</span></td>
            <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-actions oc-pr-m">
              <div class="resource-table-actions">
                <oc-button-stub type="button" size="medium" arialabel="Show context menu" submit="button" variation="passive" appearance="raw" justifycontent="center" gapsize="medium" id="context-menu-trigger-64" class="resource-table-btn-action-dropdown"><span class="oc-icon oc-icon-m oc-icon-passive"><!----></span></oc-button-stub>
                <oc-drop-stub dropid="context-menu-drop-64" popperoptions="[object Object]" toggle="#context-menu-trigger-64" position="bottom-start" mode="click" closeonclick="true" paddingsize="small"></oc-drop-stub>
              </div>
    @@ -78,11 +78,11 @@
            <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-sharedWith">
              <oc-button-stub type="button" size="medium" submit="button" variation="inverse" appearance="raw" justifycontent="center" gapsize="medium">
                <oc-avatars-stub items="[object Object]" stacked="true" istooltipdisplayed="true" maxdisplayed="3" accessibledescription=" This folder is shared via 1 link" class="resource-table-people"></oc-avatars-stub>
              </oc-button-stub>
            </td>
    -       <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-sdate" aria-label="9 months ago (June 9, 2021, 12:44 PM UTC)"><span tabindex="0">9 months ago</span></td>
    +       <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-sdate" aria-label="10 months ago (June 9, 2021, 12:44 PM UTC)"><span tabindex="0">10 months ago</span></td>
            <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-actions oc-pr-m">
              <div class="resource-table-actions">
                <oc-button-stub type="button" size="medium" arialabel="Show context menu" submit="button" variation="passive" appearance="raw" justifycontent="center" gapsize="medium" id="context-menu-trigger-39" class="resource-table-btn-action-dropdown"><span class="oc-icon oc-icon-m oc-icon-passive"><!----></span></oc-button-stub>
                <oc-drop-stub dropid="context-menu-drop-39" popperoptions="[object Object]" toggle="#context-menu-trigger-39" position="bottom-start" mode="click" closeonclick="true" paddingsize="small"></oc-drop-stub>
              </div>
    @@ -101,11 +101,11 @@
            <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-sharedWith">
              <oc-button-stub type="button" size="medium" submit="button" variation="inverse" appearance="raw" justifycontent="center" gapsize="medium">
                <oc-avatars-stub items="[object Object],[object Object]" stacked="true" istooltipdisplayed="true" maxdisplayed="3" accessibledescription="This file is shared via 1 invite This file is shared via 1 link" class="resource-table-people"></oc-avatars-stub>
              </oc-button-stub>
            </td>
    -       <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-sdate" aria-label="9 months ago (June 9, 2021, 12:37 PM UTC)"><span tabindex="0">9 months ago</span></td>
    +       <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-sdate" aria-label="10 months ago (June 9, 2021, 12:37 PM UTC)"><span tabindex="0">10 months ago</span></td>
            <td class="oc-td oc-table-cell oc-table-cell-align-right oc-table-cell-align-middle oc-table-cell-width-auto oc-text-nowrap oc-table-data-cell oc-table-data-cell-actions oc-pr-m">
              <div class="resource-table-actions">
                <oc-button-stub type="button" size="medium" arialabel="Show context menu" submit="button" variation="passive" appearance="raw" justifycontent="center" gapsize="medium" id="context-menu-trigger-30" class="resource-table-btn-action-dropdown"><span class="oc-icon oc-icon-m oc-icon-passive"><!----></span></oc-button-stub>
                <oc-drop-stub dropid="context-menu-drop-30" popperoptions="[object Object]" toggle="#context-menu-trigger-30" position="bottom-start" mode="click" closeonclick="true" paddingsize="small"></oc-drop-stub>
              </div>

      78 |
      79 |         expect(filesTable.exists()).toBeTruthy()
    > 80 |         expect(filesTable).toMatchSnapshot()
         |                            ^
      81 |
      82 |         stubs['resource-table'] = true
      83 |       })

      at Object.<anonymous> (packages/web-app-files/tests/unit/views/shares/SharedWithOthers.spec.js:80:28)


Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or re-run jest with `-u` to update them.

Test Suites: 1 failed, 167 passed, 168 total
Tests:       1 failed, 33 todo, 1021 passed, 1055 total
Snapshots:   1 failed, 131 passed, 132 total
Time:        53.761 s
Ran all test suites.
```

**Comment by individual-it** [comment] 2022-04-11 03:59
was this caused by transiflex update or by what?

**Comment by kiranparajuli589** [comment] 2022-04-11 04:18
tests started failing since this build https://drone.owncloud.com/owncloud/web/24622, but the failure is not related to translations.

resource sdate, relative time is now 10 months, was 9 months before.

maybe we've to avoid this check because it will keep on rising every month.

I've adjusted the tests in #6765 to check only props from the `ResourceTable` component rather checking whole html snap.

**Comment by kiranparajuli589** [comment] 2022-04-11 06:29
Git bisect shows 53693ceb9734ef77dbd9a8dca05a73b21f7ceec5 as the first bad commit. the issue might be with new introduced `buildSharedResource` map

**Comment by individual-it** [comment] 2022-04-11 06:45
> Git bisect shows [53693ce](https://github.com/owncloud/web/commit/53693ceb9734ef77dbd9a8dca05a73b21f7ceec5) as the first bad commit. the issue might be with new introduced `buildSharedResource` map

that is really strange, how did it pass in the PR? and that commit was already merged 17 days ago

**Comment by kiranparajuli589** [comment] 2022-04-11 07:37
yes, quite strange. tests only started failing recently in the CI. locally the current tests pass if I go before the mentioned commit.

I've updated the tests to check props separately in the fix pr.

**Comment by kulmann** [comment] 2022-04-11 08:17
As already statet in the PR by @kiranparajuli589, the tests use fixtures (also for dates) and don't mock the current date. With that relative dates change on a regular basis (now from `9 months ago` to `10 months ago`). We need to mock the current date when doing such tests. Otherwise this will reoccur frequently.

**Closed** 2022-04-11 09:37 UTC
Labels: QA:team
