### ISSUE TITLE
Trash bin shows incorrect parent folder

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9791] opened 2023-10-10 13:43 UTC
### Steps to reproduce
1. Create a folder in the root of your personal space
2. Delete it
3. Go to the trash bin of your personal space and look for that folder -> the parent folder below should be "Personal", but it's actually the name of the folder itself. The link is correct though. Also, the issue only exists for resources which were deleted from the root level.

<img width="244" alt="image" src="https://github.com/owncloud/web/assets/50302941/dc78ac7c-3957-473e-95c2-3136d0811474">

**Comment by jacob-nv** [comment] 2023-10-20 18:08
I'm not really sure about how to go fixing this.
"Personal" is default return value if all checks fail. This applies even to files in shared space that are deleted
![image](https://github.com/owncloud/web/assets/138569835/cc0390fc-7455-4fe9-9d87-3f8cdc5f137b)
![image](https://github.com/owncloud/web/assets/138569835/e1888eb6-59a6-4586-8836-ab3366876540)
While getting space for resource in trash bin (trying to get parent folder name), "storageId" is null, which builds default share space resource with name set to name of resource.
I can check for in addition for shareId etc to skip the condition, which returns name of space, but this sets file from shared space and personal with parent folder "Personal".

Those 2 resources from 2 different places, both in fairly same don't really indicate where they comes from and how to distinguish those two.

One possible option I see is using space passed to ResourceTable as prop

**Comment by JanAckermann** [comment] 2023-10-30 06:59
![image](https://github.com/owncloud/web/assets/26169327/018c0df0-4851-497a-a2b2-ce4c3220008f)

Closing as the issue is not present anymore, this might have been fixed due to changes on our new createFolderLink 
composable

**Closed by JanAckermann** 2023-10-30 06:59 UTC
Labels: Type:Bug, Priority:p3-medium
