### ISSUE TITLE
OCM app for CERN

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9888] opened 2023-10-30 13:28 UTC
- bring the CERN OCM app to the web repo (disabled by default)
- make it work for CERN

**Comment by kulmann** [comment] 2023-10-30 13:31
duplicate of https://github.com/owncloud/web/issues/9268

**Closed by kulmann** 2023-10-30 13:31 UTC

**Comment by micbar** [comment] 2023-10-30 21:15
I removed the story point to avoid double counting.
