### ISSUE TITLE
Error message when uploading a file with a name with same folder name exist

### ISSUE THREAD

**Issue by Talank** [owncloud/web#3015] opened 2020-02-12 11:04 UTC
### Steps to reproduce
1. Create a folder with name "a1.txt"
2. Try to upload a file named "a1.txt" where the folder is created

### Expected behaviour
Nice error message saying what is wrong

### Actual behaviour
```
File upload failed…
PUT is not allowed on non-files.
```

### Server configuration
**Current core master**
**Current phoenix master**

**Comment by PVince81** [comment] 2020-02-12 14:45
The UI is simply forwarding the error message from the server.

This needs the JS code to be extended and detect such message and display a better one instead.

**Comment by pascalwengerter** [comment] 2021-03-15 18:59
@Talank couldn't reproduce, could you check if this issue is still open with the current version?

**Comment by HariBhandari07** [comment] 2021-04-19 09:24
@pascalwengerter  the issue still exists. We also have a test demonstrating the issue https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUIUpload/uploadEdgecases.feature#L109

**Comment by JanAckermann** [comment] 2023-08-02 23:03
Conflict handling is enabled now, closing

**Closed by JanAckermann** 2023-08-02 23:03 UTC
