### ISSUE TITLE
Usermanagement: Edit user is empty for new users (needs refresh to work)

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7813] opened 2022-10-17 11:53 UTC
### Steps to reproduce
1. Create a new user
2. click on the "edit" pencil-icon
3. `Edit user` section is empty
![Screenshot 000845@2x](https://user-images.githubusercontent.com/26610733/196169924-47ca0324-a7e1-4d7b-973d-e8c4ca5133be.png)

### Expected behaviour
`Edit user` section should show edit option

### Actual behaviour
`Edit user` section is empty

**Comment by JammingBen** [comment] 2022-10-17 12:35
Closing because this is a duplicate of https://github.com/owncloud/web/issues/7761.

**Closed by JammingBen** 2022-10-17 12:35 UTC
Labels: Type:Bug, Priority:p2-high

**Comment by tbsbdr** [comment] 2022-10-17 13:45
ah. thx. was searching for patricks issue but didn't find it...
