### ISSUE TITLE
Always show already present collaborator in autocomplete

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2923] opened 2020-01-28 11:39 UTC
### Steps

1. Create two users "user1" and "user2"
1. Login as "user1"
1. Share an arbitrary resource with "user2"
1. Open the collaborators panel and see that it is shared with "user2"
1. Click "Add collaborator"
1. Type "us" in the autocomplete

### Actual result
User "user2" is not appearing because the user already has access.
Feeling confused because it feels broken, also because said user is not visible directly in the panel.

### Expected result
User "user2" appears in the dropdown but is greyed out and has a hint text behind "Already a collaborator"

@pmaier1 @michaelstingl some design improvement cross-client.

CC @kulmann as discussed

**Comment by JanAckermann** [comment] 2023-08-02 23:02
duplicate of: https://github.com/owncloud/web/issues/9408

**Closed by JanAckermann** 2023-08-02 23:02 UTC
Labels: Type:Design, Topic:UX-Design
